# etl/spec/s1/s1_bookshape.py
# ==============================================================================
# S1 Feature Specs: Bookshape
#
# Binance-only pipeline | Source: S0 features (parquet)
# 68 features | Feature IDs: 1040-1107
# ==============================================================================

from typing import List
from etl.spec import FeatureSpec, Dep


S1_BOOKSHAPE_FEATURES: List[FeatureSpec] = [

    # === l2.book_asymmetry ===
    FeatureSpec(
        name="book_asymmetry_fut_struct100_1s",
        stage="S1",
        operator="l2.book_asymmetry",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Bookshape",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Struct book asymmetry.",
        depends_on=(Dep(name="depth_notional_bid_struct100_fut_1s", kind="col"), Dep(name="depth_notional_ask_struct100_fut_1s", kind="col"),),
        feature_id=1040,
    ),
    FeatureSpec(
        name="book_asymmetry_fut_struct50_1s",
        stage="S1",
        operator="l2.book_asymmetry",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Bookshape",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Struct book asymmetry.",
        depends_on=(Dep(name="depth_notional_bid_struct50_fut_1s", kind="col"), Dep(name="depth_notional_ask_struct50_fut_1s", kind="col"),),
        feature_id=1041,
    ),
    FeatureSpec(
        name="book_asymmetry_spot_struct100_1s",
        stage="S1",
        operator="l2.book_asymmetry",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Bookshape",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Struct book asymmetry.",
        depends_on=(Dep(name="depth_notional_bid_struct100_spot_1s", kind="col"), Dep(name="depth_notional_ask_struct100_spot_1s", kind="col"),),
        feature_id=1042,
    ),
    FeatureSpec(
        name="book_asymmetry_spot_struct50_1s",
        stage="S1",
        operator="l2.book_asymmetry",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Bookshape",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Struct book asymmetry.",
        depends_on=(Dep(name="depth_notional_bid_struct50_spot_1s", kind="col"), Dep(name="depth_notional_ask_struct50_spot_1s", kind="col"),),
        feature_id=1043,
    ),

    # === l2.depth_gradient_ask ===
    FeatureSpec(
        name="depth_gradient_ask_fut_struct100_1s",
        stage="S1",
        operator="l2.depth_gradient_ask",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Bookshape",
        description="Ask depth gradient: (outer - inner) / outer. Fraction of depth beyond inner band.",
        depends_on=(Dep(name="depth_notional_ask_struct50_fut_1s", kind="col"), Dep(name="depth_notional_ask_struct100_fut_1s", kind="col"),),
        feature_id=1044,
    ),
    FeatureSpec(
        name="depth_gradient_ask_fut_struct50_1s",
        stage="S1",
        operator="l2.depth_gradient_ask",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Bookshape",
        description="Ask depth gradient: (outer - inner) / outer. Fraction of depth beyond inner band.",
        depends_on=(Dep(name="depth_notional_ask_10bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_struct50_fut_1s", kind="col"),),
        feature_id=1045,
    ),
    FeatureSpec(
        name="depth_gradient_ask_spot_struct100_1s",
        stage="S1",
        operator="l2.depth_gradient_ask",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Bookshape",
        description="Ask depth gradient: (outer - inner) / outer. Fraction of depth beyond inner band.",
        depends_on=(Dep(name="depth_notional_ask_struct50_spot_1s", kind="col"), Dep(name="depth_notional_ask_struct100_spot_1s", kind="col"),),
        feature_id=1046,
    ),
    FeatureSpec(
        name="depth_gradient_ask_spot_struct50_1s",
        stage="S1",
        operator="l2.depth_gradient_ask",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Bookshape",
        description="Ask depth gradient: (outer - inner) / outer. Fraction of depth beyond inner band.",
        depends_on=(Dep(name="depth_notional_ask_10bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_struct50_spot_1s", kind="col"),),
        feature_id=1047,
    ),

    # === l2.depth_gradient_bid ===
    FeatureSpec(
        name="depth_gradient_bid_fut_struct100_1s",
        stage="S1",
        operator="l2.depth_gradient_bid",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Bookshape",
        description="Bid depth gradient: (outer - inner) / outer. Fraction of depth beyond inner band.",
        depends_on=(Dep(name="depth_notional_bid_struct50_fut_1s", kind="col"), Dep(name="depth_notional_bid_struct100_fut_1s", kind="col"),),
        feature_id=1048,
    ),
    FeatureSpec(
        name="depth_gradient_bid_fut_struct50_1s",
        stage="S1",
        operator="l2.depth_gradient_bid",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Bookshape",
        description="Bid depth gradient: (outer - inner) / outer. Fraction of depth beyond inner band.",
        depends_on=(Dep(name="depth_notional_bid_10bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_struct50_fut_1s", kind="col"),),
        feature_id=1049,
    ),
    FeatureSpec(
        name="depth_gradient_bid_spot_struct100_1s",
        stage="S1",
        operator="l2.depth_gradient_bid",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Bookshape",
        description="Bid depth gradient: (outer - inner) / outer. Fraction of depth beyond inner band.",
        depends_on=(Dep(name="depth_notional_bid_struct50_spot_1s", kind="col"), Dep(name="depth_notional_bid_struct100_spot_1s", kind="col"),),
        feature_id=1050,
    ),
    FeatureSpec(
        name="depth_gradient_bid_spot_struct50_1s",
        stage="S1",
        operator="l2.depth_gradient_bid",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Bookshape",
        description="Bid depth gradient: (outer - inner) / outer. Fraction of depth beyond inner band.",
        depends_on=(Dep(name="depth_notional_bid_10bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_struct50_spot_1s", kind="col"),),
        feature_id=1051,
    ),

    # === derived.roll_mean ===
    FeatureSpec(
        name="depth_notional_ask_struct100_fut_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_ask_struct100_fut_1s", kind="col"),),
        feature_id=1052,
    ),
    FeatureSpec(
        name="depth_notional_ask_struct100_fut_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_ask_struct100_fut_1s", kind="col"),),
        feature_id=1053,
    ),
    FeatureSpec(
        name="depth_notional_ask_struct100_fut_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_ask_struct100_fut_1s", kind="col"),),
        feature_id=1054,
    ),
    FeatureSpec(
        name="depth_notional_ask_struct100_spot_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_ask_struct100_spot_1s", kind="col"),),
        feature_id=1055,
    ),
    FeatureSpec(
        name="depth_notional_ask_struct100_spot_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_ask_struct100_spot_1s", kind="col"),),
        feature_id=1056,
    ),
    FeatureSpec(
        name="depth_notional_ask_struct100_spot_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_ask_struct100_spot_1s", kind="col"),),
        feature_id=1057,
    ),
    FeatureSpec(
        name="depth_notional_ask_struct50_fut_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_ask_struct50_fut_1s", kind="col"),),
        feature_id=1058,
    ),
    FeatureSpec(
        name="depth_notional_ask_struct50_fut_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_ask_struct50_fut_1s", kind="col"),),
        feature_id=1059,
    ),
    FeatureSpec(
        name="depth_notional_ask_struct50_fut_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_ask_struct50_fut_1s", kind="col"),),
        feature_id=1060,
    ),
    FeatureSpec(
        name="depth_notional_ask_struct50_spot_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_ask_struct50_spot_1s", kind="col"),),
        feature_id=1061,
    ),
    FeatureSpec(
        name="depth_notional_ask_struct50_spot_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_ask_struct50_spot_1s", kind="col"),),
        feature_id=1062,
    ),
    FeatureSpec(
        name="depth_notional_ask_struct50_spot_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_ask_struct50_spot_1s", kind="col"),),
        feature_id=1063,
    ),
    FeatureSpec(
        name="depth_notional_bid_struct100_fut_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_bid_struct100_fut_1s", kind="col"),),
        feature_id=1064,
    ),
    FeatureSpec(
        name="depth_notional_bid_struct100_fut_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_bid_struct100_fut_1s", kind="col"),),
        feature_id=1065,
    ),
    FeatureSpec(
        name="depth_notional_bid_struct100_fut_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_bid_struct100_fut_1s", kind="col"),),
        feature_id=1066,
    ),
    FeatureSpec(
        name="depth_notional_bid_struct100_spot_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_bid_struct100_spot_1s", kind="col"),),
        feature_id=1067,
    ),
    FeatureSpec(
        name="depth_notional_bid_struct100_spot_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_bid_struct100_spot_1s", kind="col"),),
        feature_id=1068,
    ),
    FeatureSpec(
        name="depth_notional_bid_struct100_spot_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_bid_struct100_spot_1s", kind="col"),),
        feature_id=1069,
    ),
    FeatureSpec(
        name="depth_notional_bid_struct50_fut_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_bid_struct50_fut_1s", kind="col"),),
        feature_id=1070,
    ),
    FeatureSpec(
        name="depth_notional_bid_struct50_fut_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_bid_struct50_fut_1s", kind="col"),),
        feature_id=1071,
    ),
    FeatureSpec(
        name="depth_notional_bid_struct50_fut_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_bid_struct50_fut_1s", kind="col"),),
        feature_id=1072,
    ),
    FeatureSpec(
        name="depth_notional_bid_struct50_spot_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_bid_struct50_spot_1s", kind="col"),),
        feature_id=1073,
    ),
    FeatureSpec(
        name="depth_notional_bid_struct50_spot_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_bid_struct50_spot_1s", kind="col"),),
        feature_id=1074,
    ),
    FeatureSpec(
        name="depth_notional_bid_struct50_spot_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="depth_notional_bid_struct50_spot_1s", kind="col"),),
        feature_id=1075,
    ),

    # === l2.liq_cluster_asymmetry ===
    FeatureSpec(
        name="liq_cluster_asymmetry_fut_struct100_300s",
        stage="S1",
        operator="l2.liq_cluster_asymmetry",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling CV difference between bid/ask depth. Cluster asymmetry.",
        depends_on=(Dep(name="depth_notional_ask_struct100_fut_1s", kind="col"), Dep(name="depth_notional_bid_struct100_fut_1s", kind="col"),),
        feature_id=1076,
    ),
    FeatureSpec(
        name="liq_cluster_asymmetry_fut_struct100_60s",
        stage="S1",
        operator="l2.liq_cluster_asymmetry",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling CV difference between bid/ask depth. Cluster asymmetry.",
        depends_on=(Dep(name="depth_notional_ask_struct100_fut_1s", kind="col"), Dep(name="depth_notional_bid_struct100_fut_1s", kind="col"),),
        feature_id=1077,
    ),
    FeatureSpec(
        name="liq_cluster_asymmetry_fut_struct50_300s",
        stage="S1",
        operator="l2.liq_cluster_asymmetry",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling CV difference between bid/ask depth. Cluster asymmetry.",
        depends_on=(Dep(name="depth_notional_ask_struct50_fut_1s", kind="col"), Dep(name="depth_notional_bid_struct50_fut_1s", kind="col"),),
        feature_id=1078,
    ),
    FeatureSpec(
        name="liq_cluster_asymmetry_fut_struct50_60s",
        stage="S1",
        operator="l2.liq_cluster_asymmetry",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling CV difference between bid/ask depth. Cluster asymmetry.",
        depends_on=(Dep(name="depth_notional_ask_struct50_fut_1s", kind="col"), Dep(name="depth_notional_bid_struct50_fut_1s", kind="col"),),
        feature_id=1079,
    ),
    FeatureSpec(
        name="liq_cluster_asymmetry_spot_struct100_300s",
        stage="S1",
        operator="l2.liq_cluster_asymmetry",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling CV difference between bid/ask depth. Cluster asymmetry.",
        depends_on=(Dep(name="depth_notional_ask_struct100_spot_1s", kind="col"), Dep(name="depth_notional_bid_struct100_spot_1s", kind="col"),),
        feature_id=1080,
    ),
    FeatureSpec(
        name="liq_cluster_asymmetry_spot_struct100_60s",
        stage="S1",
        operator="l2.liq_cluster_asymmetry",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling CV difference between bid/ask depth. Cluster asymmetry.",
        depends_on=(Dep(name="depth_notional_ask_struct100_spot_1s", kind="col"), Dep(name="depth_notional_bid_struct100_spot_1s", kind="col"),),
        feature_id=1081,
    ),
    FeatureSpec(
        name="liq_cluster_asymmetry_spot_struct50_300s",
        stage="S1",
        operator="l2.liq_cluster_asymmetry",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling CV difference between bid/ask depth. Cluster asymmetry.",
        depends_on=(Dep(name="depth_notional_ask_struct50_spot_1s", kind="col"), Dep(name="depth_notional_bid_struct50_spot_1s", kind="col"),),
        feature_id=1082,
    ),
    FeatureSpec(
        name="liq_cluster_asymmetry_spot_struct50_60s",
        stage="S1",
        operator="l2.liq_cluster_asymmetry",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling CV difference between bid/ask depth. Cluster asymmetry.",
        depends_on=(Dep(name="depth_notional_ask_struct50_spot_1s", kind="col"), Dep(name="depth_notional_bid_struct50_spot_1s", kind="col"),),
        feature_id=1083,
    ),

    # === l2.liq_concentration_ask ===
    FeatureSpec(
        name="liq_concentration_ask_fut_struct100_1s",
        stage="S1",
        operator="l2.liq_concentration_ask",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Bookshape",
        description="Ask liquidity concentration: inner/outer depth ratio. High = concentrated near mid.",
        depends_on=(Dep(name="depth_notional_ask_struct50_fut_1s", kind="col"), Dep(name="depth_notional_ask_struct100_fut_1s", kind="col"),),
        feature_id=1084,
    ),
    FeatureSpec(
        name="liq_concentration_ask_fut_struct50_1s",
        stage="S1",
        operator="l2.liq_concentration_ask",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Bookshape",
        description="Ask liquidity concentration: inner/outer depth ratio. High = concentrated near mid.",
        depends_on=(Dep(name="depth_notional_ask_10bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_struct50_fut_1s", kind="col"),),
        feature_id=1085,
    ),
    FeatureSpec(
        name="liq_concentration_ask_spot_struct100_1s",
        stage="S1",
        operator="l2.liq_concentration_ask",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Bookshape",
        description="Ask liquidity concentration: inner/outer depth ratio. High = concentrated near mid.",
        depends_on=(Dep(name="depth_notional_ask_struct50_spot_1s", kind="col"), Dep(name="depth_notional_ask_struct100_spot_1s", kind="col"),),
        feature_id=1086,
    ),
    FeatureSpec(
        name="liq_concentration_ask_spot_struct50_1s",
        stage="S1",
        operator="l2.liq_concentration_ask",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Bookshape",
        description="Ask liquidity concentration: inner/outer depth ratio. High = concentrated near mid.",
        depends_on=(Dep(name="depth_notional_ask_10bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_struct50_spot_1s", kind="col"),),
        feature_id=1087,
    ),

    # === l2.liq_concentration_bid ===
    FeatureSpec(
        name="liq_concentration_bid_fut_struct100_1s",
        stage="S1",
        operator="l2.liq_concentration_bid",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Bookshape",
        description="Bid liquidity concentration: inner/outer depth ratio. High = concentrated near mid.",
        depends_on=(Dep(name="depth_notional_bid_struct50_fut_1s", kind="col"), Dep(name="depth_notional_bid_struct100_fut_1s", kind="col"),),
        feature_id=1088,
    ),
    FeatureSpec(
        name="liq_concentration_bid_fut_struct50_1s",
        stage="S1",
        operator="l2.liq_concentration_bid",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Bookshape",
        description="Bid liquidity concentration: inner/outer depth ratio. High = concentrated near mid.",
        depends_on=(Dep(name="depth_notional_bid_10bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_struct50_fut_1s", kind="col"),),
        feature_id=1089,
    ),
    FeatureSpec(
        name="liq_concentration_bid_spot_struct100_1s",
        stage="S1",
        operator="l2.liq_concentration_bid",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Bookshape",
        description="Bid liquidity concentration: inner/outer depth ratio. High = concentrated near mid.",
        depends_on=(Dep(name="depth_notional_bid_struct50_spot_1s", kind="col"), Dep(name="depth_notional_bid_struct100_spot_1s", kind="col"),),
        feature_id=1090,
    ),
    FeatureSpec(
        name="liq_concentration_bid_spot_struct50_1s",
        stage="S1",
        operator="l2.liq_concentration_bid",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Bookshape",
        description="Bid liquidity concentration: inner/outer depth ratio. High = concentrated near mid.",
        depends_on=(Dep(name="depth_notional_bid_10bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_struct50_spot_1s", kind="col"),),
        feature_id=1091,
    ),

    # === derived.add ===
    FeatureSpec(
        name="liq_sum_fut_10bps_1s",
        stage="S1",
        operator="derived.add",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Bookshape",
        description="Sum of two columns.",
        depends_on=(Dep(name="depth_notional_ask_10bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_10bps_fut_1s", kind="col"),),
        feature_id=1092,
    ),

    # === l2.liq_sum ===
    FeatureSpec(
        name="liq_sum_fut_1s",
        stage="S1",
        operator="l2.liq_sum",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Bookshape",
        description="Total resting liquidity: depth_bid + depth_ask.",
        depends_on=(Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"),),
        feature_id=1093,
    ),

    # === derived.add ===
    # NOTE: liq_sum_fut_5bps_1s removed — identical to liq_sum_fut_1s (same deps, same formula)
    FeatureSpec(
        name="liq_sum_spot_10bps_1s",
        stage="S1",
        operator="derived.add",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Bookshape",
        description="Sum of two columns.",
        depends_on=(Dep(name="depth_notional_ask_10bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_10bps_spot_1s", kind="col"),),
        feature_id=1094,
    ),

    # === l2.liq_sum ===
    FeatureSpec(
        name="liq_sum_spot_1s",
        stage="S1",
        operator="l2.liq_sum",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Bookshape",
        description="Total resting liquidity: depth_bid + depth_ask.",
        depends_on=(Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"),),
        feature_id=1095,
    ),

    # NOTE: liq_sum_spot_5bps_1s removed — identical to liq_sum_spot_1s (same deps, same formula)

    # === derived.roll_mean ===
    FeatureSpec(
        name="max_bps_ask_fut_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_bps_ask_fut_1s", kind="col"),),
        feature_id=1096,
    ),
    FeatureSpec(
        name="max_bps_ask_fut_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_bps_ask_fut_1s", kind="col"),),
        feature_id=1097,
    ),
    FeatureSpec(
        name="max_bps_ask_fut_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_bps_ask_fut_1s", kind="col"),),
        feature_id=1098,
    ),
    FeatureSpec(
        name="max_bps_ask_spot_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_bps_ask_spot_1s", kind="col"),),
        feature_id=1099,
    ),
    FeatureSpec(
        name="max_bps_ask_spot_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_bps_ask_spot_1s", kind="col"),),
        feature_id=1100,
    ),
    FeatureSpec(
        name="max_bps_ask_spot_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_bps_ask_spot_1s", kind="col"),),
        feature_id=1101,
    ),
    FeatureSpec(
        name="max_bps_bid_fut_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_bps_bid_fut_1s", kind="col"),),
        feature_id=1102,
    ),
    FeatureSpec(
        name="max_bps_bid_fut_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_bps_bid_fut_1s", kind="col"),),
        feature_id=1103,
    ),
    FeatureSpec(
        name="max_bps_bid_fut_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_bps_bid_fut_1s", kind="col"),),
        feature_id=1104,
    ),
    FeatureSpec(
        name="max_bps_bid_spot_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_bps_bid_spot_1s", kind="col"),),
        feature_id=1105,
    ),
    FeatureSpec(
        name="max_bps_bid_spot_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_bps_bid_spot_1s", kind="col"),),
        feature_id=1106,
    ),
    FeatureSpec(
        name="max_bps_bid_spot_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_bps_bid_spot_1s", kind="col"),),
        feature_id=1107,
    ),

    # === l2.max_liq_distance ===
    # NOTE: max_liq_distance_*_5bps_* features removed (4 total).
    # These were passthroughs of depth_notional (wrong). True BPS distance
    # to max liquidity cluster requires per-price-level order book data
    # not available at S1 level. The S0 max_liq_distance_*_10bps and _struct*
    # features computed from raw data are correct and should be used instead.
]