# etl/spec/s1/s1_liquidity_events.py
# ==============================================================================
# S1 Feature Specs: Liquidity Events
#
# Binance-only pipeline | Source: S0 features (parquet)
# 68 features | Feature IDs: 1130-1197
# ==============================================================================

from typing import List
from etl.spec import FeatureSpec, Dep


S1_LIQUIDITY_EVENTS_FEATURES: List[FeatureSpec] = [

    # === l2.add_rate_ask ===
    FeatureSpec(
        name="add_rate_ask_fut_10bps_1s",
        stage="S1",
        operator="l2.add_rate_ask",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Liquidity Events",
        description="Ask add rate: max(0, depth_t - depth_{t-1}).",
        depends_on=(Dep(name="depth_notional_ask_10bps_fut_1s", kind="col"),),
        feature_id=1130,
    ),
    FeatureSpec(
        name="add_rate_ask_fut_1bps_1s",
        stage="S1",
        operator="l2.add_rate_ask",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Liquidity Events",
        description="Ask add rate: max(0, depth_t - depth_{t-1}).",
        depends_on=(Dep(name="depth_notional_ask_1bps_fut_1s", kind="col"),),
        feature_id=1131,
    ),
    FeatureSpec(
        name="add_rate_ask_fut_2bps_1s",
        stage="S1",
        operator="l2.add_rate_ask",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Liquidity Events",
        description="Ask add rate: max(0, depth_t - depth_{t-1}).",
        depends_on=(Dep(name="depth_notional_ask_2bps_fut_1s", kind="col"),),
        feature_id=1132,
    ),
    FeatureSpec(
        name="add_rate_ask_fut_5bps_1s",
        stage="S1",
        operator="l2.add_rate_ask",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Liquidity Events",
        description="Ask add rate: max(0, depth_t - depth_{t-1}).",
        depends_on=(Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"),),
        feature_id=1133,
    ),
    FeatureSpec(
        name="add_rate_ask_spot_10bps_1s",
        stage="S1",
        operator="l2.add_rate_ask",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Liquidity Events",
        description="Ask add rate: max(0, depth_t - depth_{t-1}).",
        depends_on=(Dep(name="depth_notional_ask_10bps_spot_1s", kind="col"),),
        feature_id=1134,
    ),
    FeatureSpec(
        name="add_rate_ask_spot_1bps_1s",
        stage="S1",
        operator="l2.add_rate_ask",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Liquidity Events",
        description="Ask add rate: max(0, depth_t - depth_{t-1}).",
        depends_on=(Dep(name="depth_notional_ask_1bps_spot_1s", kind="col"),),
        feature_id=1135,
    ),
    FeatureSpec(
        name="add_rate_ask_spot_2bps_1s",
        stage="S1",
        operator="l2.add_rate_ask",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Liquidity Events",
        description="Ask add rate: max(0, depth_t - depth_{t-1}).",
        depends_on=(Dep(name="depth_notional_ask_2bps_spot_1s", kind="col"),),
        feature_id=1136,
    ),
    FeatureSpec(
        name="add_rate_ask_spot_5bps_1s",
        stage="S1",
        operator="l2.add_rate_ask",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Liquidity Events",
        description="Ask add rate: max(0, depth_t - depth_{t-1}).",
        depends_on=(Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"),),
        feature_id=1137,
    ),

    # === l2.add_rate_bid ===
    FeatureSpec(
        name="add_rate_bid_fut_10bps_1s",
        stage="S1",
        operator="l2.add_rate_bid",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Liquidity Events",
        description="Bid add rate: max(0, depth_t - depth_{t-1}).",
        depends_on=(Dep(name="depth_notional_bid_10bps_fut_1s", kind="col"),),
        feature_id=1138,
    ),
    FeatureSpec(
        name="add_rate_bid_fut_1bps_1s",
        stage="S1",
        operator="l2.add_rate_bid",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Liquidity Events",
        description="Bid add rate: max(0, depth_t - depth_{t-1}).",
        depends_on=(Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"),),
        feature_id=1139,
    ),
    FeatureSpec(
        name="add_rate_bid_fut_2bps_1s",
        stage="S1",
        operator="l2.add_rate_bid",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Liquidity Events",
        description="Bid add rate: max(0, depth_t - depth_{t-1}).",
        depends_on=(Dep(name="depth_notional_bid_2bps_fut_1s", kind="col"),),
        feature_id=1140,
    ),
    FeatureSpec(
        name="add_rate_bid_fut_5bps_1s",
        stage="S1",
        operator="l2.add_rate_bid",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Liquidity Events",
        description="Bid add rate: max(0, depth_t - depth_{t-1}).",
        depends_on=(Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"),),
        feature_id=1141,
    ),
    FeatureSpec(
        name="add_rate_bid_spot_10bps_1s",
        stage="S1",
        operator="l2.add_rate_bid",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Liquidity Events",
        description="Bid add rate: max(0, depth_t - depth_{t-1}).",
        depends_on=(Dep(name="depth_notional_bid_10bps_spot_1s", kind="col"),),
        feature_id=1142,
    ),
    FeatureSpec(
        name="add_rate_bid_spot_1bps_1s",
        stage="S1",
        operator="l2.add_rate_bid",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Liquidity Events",
        description="Bid add rate: max(0, depth_t - depth_{t-1}).",
        depends_on=(Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"),),
        feature_id=1143,
    ),
    FeatureSpec(
        name="add_rate_bid_spot_2bps_1s",
        stage="S1",
        operator="l2.add_rate_bid",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Liquidity Events",
        description="Bid add rate: max(0, depth_t - depth_{t-1}).",
        depends_on=(Dep(name="depth_notional_bid_2bps_spot_1s", kind="col"),),
        feature_id=1144,
    ),
    FeatureSpec(
        name="add_rate_bid_spot_5bps_1s",
        stage="S1",
        operator="l2.add_rate_bid",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Liquidity Events",
        description="Bid add rate: max(0, depth_t - depth_{t-1}).",
        depends_on=(Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"),),
        feature_id=1145,
    ),

    # === l2.cancel_rate_ask ===
    FeatureSpec(
        name="cancel_rate_ask_fut_10bps_1s",
        stage="S1",
        operator="l2.cancel_rate_ask",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Liquidity Events",
        description="Ask cancel rate: max(0, depth_{t-1} - depth_t).",
        depends_on=(Dep(name="depth_notional_ask_10bps_fut_1s", kind="col"),),
        feature_id=1146,
    ),
    FeatureSpec(
        name="cancel_rate_ask_fut_1bps_1s",
        stage="S1",
        operator="l2.cancel_rate_ask",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Liquidity Events",
        description="Ask cancel rate: max(0, depth_{t-1} - depth_t).",
        depends_on=(Dep(name="depth_notional_ask_1bps_fut_1s", kind="col"),),
        feature_id=1147,
    ),
    FeatureSpec(
        name="cancel_rate_ask_fut_2bps_1s",
        stage="S1",
        operator="l2.cancel_rate_ask",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Liquidity Events",
        description="Ask cancel rate: max(0, depth_{t-1} - depth_t).",
        depends_on=(Dep(name="depth_notional_ask_2bps_fut_1s", kind="col"),),
        feature_id=1148,
    ),
    FeatureSpec(
        name="cancel_rate_ask_fut_5bps_1s",
        stage="S1",
        operator="l2.cancel_rate_ask",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Liquidity Events",
        description="Ask cancel rate: max(0, depth_{t-1} - depth_t).",
        depends_on=(Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"),),
        feature_id=1149,
    ),
    FeatureSpec(
        name="cancel_rate_ask_spot_10bps_1s",
        stage="S1",
        operator="l2.cancel_rate_ask",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Liquidity Events",
        description="Ask cancel rate: max(0, depth_{t-1} - depth_t).",
        depends_on=(Dep(name="depth_notional_ask_10bps_spot_1s", kind="col"),),
        feature_id=1150,
    ),
    FeatureSpec(
        name="cancel_rate_ask_spot_1bps_1s",
        stage="S1",
        operator="l2.cancel_rate_ask",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Liquidity Events",
        description="Ask cancel rate: max(0, depth_{t-1} - depth_t).",
        depends_on=(Dep(name="depth_notional_ask_1bps_spot_1s", kind="col"),),
        feature_id=1151,
    ),
    FeatureSpec(
        name="cancel_rate_ask_spot_2bps_1s",
        stage="S1",
        operator="l2.cancel_rate_ask",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Liquidity Events",
        description="Ask cancel rate: max(0, depth_{t-1} - depth_t).",
        depends_on=(Dep(name="depth_notional_ask_2bps_spot_1s", kind="col"),),
        feature_id=1152,
    ),
    FeatureSpec(
        name="cancel_rate_ask_spot_5bps_1s",
        stage="S1",
        operator="l2.cancel_rate_ask",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Liquidity Events",
        description="Ask cancel rate: max(0, depth_{t-1} - depth_t).",
        depends_on=(Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"),),
        feature_id=1153,
    ),

    # === l2.cancel_rate_bid ===
    FeatureSpec(
        name="cancel_rate_bid_fut_10bps_1s",
        stage="S1",
        operator="l2.cancel_rate_bid",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Liquidity Events",
        description="Bid cancel rate: max(0, depth_{t-1} - depth_t).",
        depends_on=(Dep(name="depth_notional_bid_10bps_fut_1s", kind="col"),),
        feature_id=1154,
    ),
    FeatureSpec(
        name="cancel_rate_bid_fut_1bps_1s",
        stage="S1",
        operator="l2.cancel_rate_bid",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Liquidity Events",
        description="Bid cancel rate: max(0, depth_{t-1} - depth_t).",
        depends_on=(Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"),),
        feature_id=1155,
    ),
    FeatureSpec(
        name="cancel_rate_bid_fut_2bps_1s",
        stage="S1",
        operator="l2.cancel_rate_bid",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Liquidity Events",
        description="Bid cancel rate: max(0, depth_{t-1} - depth_t).",
        depends_on=(Dep(name="depth_notional_bid_2bps_fut_1s", kind="col"),),
        feature_id=1156,
    ),
    FeatureSpec(
        name="cancel_rate_bid_fut_5bps_1s",
        stage="S1",
        operator="l2.cancel_rate_bid",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Liquidity Events",
        description="Bid cancel rate: max(0, depth_{t-1} - depth_t).",
        depends_on=(Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"),),
        feature_id=1157,
    ),
    FeatureSpec(
        name="cancel_rate_bid_spot_10bps_1s",
        stage="S1",
        operator="l2.cancel_rate_bid",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Liquidity Events",
        description="Bid cancel rate: max(0, depth_{t-1} - depth_t).",
        depends_on=(Dep(name="depth_notional_bid_10bps_spot_1s", kind="col"),),
        feature_id=1158,
    ),
    FeatureSpec(
        name="cancel_rate_bid_spot_1bps_1s",
        stage="S1",
        operator="l2.cancel_rate_bid",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Liquidity Events",
        description="Bid cancel rate: max(0, depth_{t-1} - depth_t).",
        depends_on=(Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"),),
        feature_id=1159,
    ),
    FeatureSpec(
        name="cancel_rate_bid_spot_2bps_1s",
        stage="S1",
        operator="l2.cancel_rate_bid",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Liquidity Events",
        description="Bid cancel rate: max(0, depth_{t-1} - depth_t).",
        depends_on=(Dep(name="depth_notional_bid_2bps_spot_1s", kind="col"),),
        feature_id=1160,
    ),
    FeatureSpec(
        name="cancel_rate_bid_spot_5bps_1s",
        stage="S1",
        operator="l2.cancel_rate_bid",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Liquidity Events",
        description="Bid cancel rate: max(0, depth_{t-1} - depth_t).",
        depends_on=(Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"),),
        feature_id=1161,
    ),

    # === l2.fill_rate_ahead ===
    FeatureSpec(
        name="fill_rate_ahead_fut_1bps_15s",
        stage="S1",
        operator="l2.fill_rate_ahead",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Fraction of depth consumed by taker flow in window.",
        depends_on=(Dep(name="depth_notional_ask_1bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"), Dep(name="taker_buy_vol_fut_1s", kind="col"), Dep(name="taker_sell_vol_fut_1s", kind="col"),),
        feature_id=1162,
    ),
    FeatureSpec(
        name="fill_rate_ahead_spot_1bps_15s",
        stage="S1",
        operator="l2.fill_rate_ahead",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Fraction of depth consumed by taker flow in window.",
        depends_on=(Dep(name="depth_notional_ask_1bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"), Dep(name="taker_buy_vol_spot_1s", kind="col"), Dep(name="taker_sell_vol_spot_1s", kind="col"),),
        feature_id=1163,
    ),

    # === l2.pull_rate ===
    FeatureSpec(
        name="pull_rate_fut_10bps_15s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_fut_10bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_10bps_1s", kind="col"), Dep(name="depth_notional_ask_10bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_10bps_fut_1s", kind="col"),),
        feature_id=1164,
    ),
    FeatureSpec(
        name="pull_rate_fut_10bps_5s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_fut_10bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_10bps_1s", kind="col"), Dep(name="depth_notional_ask_10bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_10bps_fut_1s", kind="col"),),
        feature_id=1165,
    ),
    FeatureSpec(
        name="pull_rate_fut_10bps_60s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_fut_10bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_10bps_1s", kind="col"), Dep(name="depth_notional_ask_10bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_10bps_fut_1s", kind="col"),),
        feature_id=1166,
    ),
    FeatureSpec(
        name="pull_rate_fut_1bps_5s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_fut_1bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"),),
        feature_id=1167,
    ),
    FeatureSpec(
        name="pull_rate_fut_1bps_60s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_fut_1bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"),),
        feature_id=1168,
    ),
    FeatureSpec(
        name="pull_rate_fut_2bps_5s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_fut_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_2bps_1s", kind="col"), Dep(name="depth_notional_ask_2bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_2bps_fut_1s", kind="col"),),
        feature_id=1169,
    ),
    FeatureSpec(
        name="pull_rate_fut_5bps_15s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_fut_5bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_5bps_1s", kind="col"), Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"),),
        feature_id=1170,
    ),
    FeatureSpec(
        name="pull_rate_fut_5bps_5s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_fut_5bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_5bps_1s", kind="col"), Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"),),
        feature_id=1171,
    ),
    FeatureSpec(
        name="pull_rate_fut_5bps_60s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_fut_5bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_5bps_1s", kind="col"), Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"),),
        feature_id=1172,
    ),
    FeatureSpec(
        name="pull_rate_spot_10bps_15s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_spot_10bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_10bps_1s", kind="col"), Dep(name="depth_notional_ask_10bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_10bps_spot_1s", kind="col"),),
        feature_id=1173,
    ),
    FeatureSpec(
        name="pull_rate_spot_10bps_5s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_spot_10bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_10bps_1s", kind="col"), Dep(name="depth_notional_ask_10bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_10bps_spot_1s", kind="col"),),
        feature_id=1174,
    ),
    FeatureSpec(
        name="pull_rate_spot_10bps_60s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_spot_10bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_10bps_1s", kind="col"), Dep(name="depth_notional_ask_10bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_10bps_spot_1s", kind="col"),),
        feature_id=1175,
    ),
    FeatureSpec(
        name="pull_rate_spot_1bps_5s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_spot_1bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"),),
        feature_id=1176,
    ),
    FeatureSpec(
        name="pull_rate_spot_1bps_60s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_spot_1bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"),),
        feature_id=1177,
    ),
    FeatureSpec(
        name="pull_rate_spot_2bps_5s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_spot_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_2bps_1s", kind="col"), Dep(name="depth_notional_ask_2bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_2bps_spot_1s", kind="col"),),
        feature_id=1178,
    ),
    FeatureSpec(
        name="pull_rate_spot_5bps_15s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_spot_5bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_5bps_1s", kind="col"), Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"),),
        feature_id=1179,
    ),
    FeatureSpec(
        name="pull_rate_spot_5bps_5s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_spot_5bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_5bps_1s", kind="col"), Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"),),
        feature_id=1180,
    ),
    FeatureSpec(
        name="pull_rate_spot_5bps_60s",
        stage="S1",
        operator="l2.pull_rate",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: total cancels / (total depth + eps).",
        depends_on=(Dep(name="cancel_rate_ask_spot_5bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_5bps_1s", kind="col"), Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"),),
        feature_id=1181,
    ),

    # === l2.refill_rate ===
    FeatureSpec(
        name="refill_rate_fut_10bps_15s",
        stage="S1",
        operator="l2.refill_rate",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: total adds / (total depth + eps).",
        depends_on=(Dep(name="add_rate_ask_fut_10bps_1s", kind="col"), Dep(name="add_rate_bid_fut_10bps_1s", kind="col"), Dep(name="depth_notional_ask_10bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_10bps_fut_1s", kind="col"),),
        feature_id=1182,
    ),
    FeatureSpec(
        name="refill_rate_fut_10bps_5s",
        stage="S1",
        operator="l2.refill_rate",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: total adds / (total depth + eps).",
        depends_on=(Dep(name="add_rate_ask_fut_10bps_1s", kind="col"), Dep(name="add_rate_bid_fut_10bps_1s", kind="col"), Dep(name="depth_notional_ask_10bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_10bps_fut_1s", kind="col"),),
        feature_id=1183,
    ),
    FeatureSpec(
        name="refill_rate_fut_10bps_60s",
        stage="S1",
        operator="l2.refill_rate",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: total adds / (total depth + eps).",
        depends_on=(Dep(name="add_rate_ask_fut_10bps_1s", kind="col"), Dep(name="add_rate_bid_fut_10bps_1s", kind="col"), Dep(name="depth_notional_ask_10bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_10bps_fut_1s", kind="col"),),
        feature_id=1184,
    ),
    FeatureSpec(
        name="refill_rate_fut_1bps_60s",
        stage="S1",
        operator="l2.refill_rate",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: total adds / (total depth + eps).",
        depends_on=(Dep(name="add_rate_ask_fut_1bps_1s", kind="col"), Dep(name="add_rate_bid_fut_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"),),
        feature_id=1185,
    ),
    FeatureSpec(
        name="refill_rate_fut_2bps_5s",
        stage="S1",
        operator="l2.refill_rate",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: total adds / (total depth + eps).",
        depends_on=(Dep(name="add_rate_ask_fut_2bps_1s", kind="col"), Dep(name="add_rate_bid_fut_2bps_1s", kind="col"), Dep(name="depth_notional_ask_2bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_2bps_fut_1s", kind="col"),),
        feature_id=1186,
    ),
    FeatureSpec(
        name="refill_rate_fut_5bps_15s",
        stage="S1",
        operator="l2.refill_rate",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: total adds / (total depth + eps).",
        depends_on=(Dep(name="add_rate_ask_fut_5bps_1s", kind="col"), Dep(name="add_rate_bid_fut_5bps_1s", kind="col"), Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"),),
        feature_id=1187,
    ),
    FeatureSpec(
        name="refill_rate_fut_5bps_5s",
        stage="S1",
        operator="l2.refill_rate",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: total adds / (total depth + eps).",
        depends_on=(Dep(name="add_rate_ask_fut_5bps_1s", kind="col"), Dep(name="add_rate_bid_fut_5bps_1s", kind="col"), Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"),),
        feature_id=1188,
    ),
    FeatureSpec(
        name="refill_rate_fut_5bps_60s",
        stage="S1",
        operator="l2.refill_rate",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: total adds / (total depth + eps).",
        depends_on=(Dep(name="add_rate_ask_fut_5bps_1s", kind="col"), Dep(name="add_rate_bid_fut_5bps_1s", kind="col"), Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"),),
        feature_id=1189,
    ),
    FeatureSpec(
        name="refill_rate_spot_10bps_15s",
        stage="S1",
        operator="l2.refill_rate",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: total adds / (total depth + eps).",
        depends_on=(Dep(name="add_rate_ask_spot_10bps_1s", kind="col"), Dep(name="add_rate_bid_spot_10bps_1s", kind="col"), Dep(name="depth_notional_ask_10bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_10bps_spot_1s", kind="col"),),
        feature_id=1190,
    ),
    FeatureSpec(
        name="refill_rate_spot_10bps_5s",
        stage="S1",
        operator="l2.refill_rate",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: total adds / (total depth + eps).",
        depends_on=(Dep(name="add_rate_ask_spot_10bps_1s", kind="col"), Dep(name="add_rate_bid_spot_10bps_1s", kind="col"), Dep(name="depth_notional_ask_10bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_10bps_spot_1s", kind="col"),),
        feature_id=1191,
    ),
    FeatureSpec(
        name="refill_rate_spot_10bps_60s",
        stage="S1",
        operator="l2.refill_rate",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: total adds / (total depth + eps).",
        depends_on=(Dep(name="add_rate_ask_spot_10bps_1s", kind="col"), Dep(name="add_rate_bid_spot_10bps_1s", kind="col"), Dep(name="depth_notional_ask_10bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_10bps_spot_1s", kind="col"),),
        feature_id=1192,
    ),
    FeatureSpec(
        name="refill_rate_spot_1bps_60s",
        stage="S1",
        operator="l2.refill_rate",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: total adds / (total depth + eps).",
        depends_on=(Dep(name="add_rate_ask_spot_1bps_1s", kind="col"), Dep(name="add_rate_bid_spot_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"),),
        feature_id=1193,
    ),
    FeatureSpec(
        name="refill_rate_spot_2bps_5s",
        stage="S1",
        operator="l2.refill_rate",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: total adds / (total depth + eps).",
        depends_on=(Dep(name="add_rate_ask_spot_2bps_1s", kind="col"), Dep(name="add_rate_bid_spot_2bps_1s", kind="col"), Dep(name="depth_notional_ask_2bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_2bps_spot_1s", kind="col"),),
        feature_id=1194,
    ),
    FeatureSpec(
        name="refill_rate_spot_5bps_15s",
        stage="S1",
        operator="l2.refill_rate",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: total adds / (total depth + eps).",
        depends_on=(Dep(name="add_rate_ask_spot_5bps_1s", kind="col"), Dep(name="add_rate_bid_spot_5bps_1s", kind="col"), Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"),),
        feature_id=1195,
    ),
    FeatureSpec(
        name="refill_rate_spot_5bps_5s",
        stage="S1",
        operator="l2.refill_rate",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: total adds / (total depth + eps).",
        depends_on=(Dep(name="add_rate_ask_spot_5bps_1s", kind="col"), Dep(name="add_rate_bid_spot_5bps_1s", kind="col"), Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"),),
        feature_id=1196,
    ),
    FeatureSpec(
        name="refill_rate_spot_5bps_60s",
        stage="S1",
        operator="l2.refill_rate",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: total adds / (total depth + eps).",
        depends_on=(Dep(name="add_rate_ask_spot_5bps_1s", kind="col"), Dep(name="add_rate_bid_spot_5bps_1s", kind="col"), Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"),),
        feature_id=1197,
    ),
]