# etl/spec/s1/s1_price.py
# ==============================================================================
# S1 Feature Specs: Price
#
# Binance-only pipeline | Source: S0 features (parquet)
# 35 features | Feature IDs: 1266-1300
# ==============================================================================
    # === LWP Mid Rolling (Liquidity-Weighted Price) ===
    # Source: lwp_mid_*_1s from S0 (correct depth-array computation via lobdeep).
    # Rolling mean = average "liquidity centre of gravity" over window.
    #
    # Variants:
    #   5bps:     tight fixed window — microstructure signal
    #   10bps:    wider fixed window — more stable, captures deeper liquidity
    #   struct50: adaptive 0→0.5*bps_sym — valid across vol regimes
    #   struct100: adaptive 0→1.0*bps_sym — full symmetric depth window
    # Timeframes: 60/300/900s. Spot + Futures for cross-market use at S2+.

from typing import List
from etl.spec import FeatureSpec, Dep


S1_PRICE_FEATURES: List[FeatureSpec] = [
    FeatureSpec(
        name="lwp_mid_5bps_fut_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid 5bps over 60s.",
        depends_on=(Dep(name="lwp_mid_5bps_fut_1s", kind="col"),),
        feature_id=1266,
    ),
    FeatureSpec(
        name="lwp_mid_5bps_fut_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid 5bps over 300s.",
        depends_on=(Dep(name="lwp_mid_5bps_fut_1s", kind="col"),),
        feature_id=1267,
    ),
    FeatureSpec(
        name="lwp_mid_5bps_fut_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid 5bps over 900s.",
        depends_on=(Dep(name="lwp_mid_5bps_fut_1s", kind="col"),),
        feature_id=1268,
    ),
    FeatureSpec(
        name="lwp_mid_5bps_spot_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid 5bps over 60s.",
        depends_on=(Dep(name="lwp_mid_5bps_spot_1s", kind="col"),),
        feature_id=1269,
    ),
    FeatureSpec(
        name="lwp_mid_5bps_spot_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid 5bps over 300s.",
        depends_on=(Dep(name="lwp_mid_5bps_spot_1s", kind="col"),),
        feature_id=1270,
    ),
    FeatureSpec(
        name="lwp_mid_5bps_spot_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid 5bps over 900s.",
        depends_on=(Dep(name="lwp_mid_5bps_spot_1s", kind="col"),),
        feature_id=1271,
    ),
    FeatureSpec(
        name="lwp_mid_10bps_fut_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid 10bps over 60s.",
        depends_on=(Dep(name="lwp_mid_10bps_fut_1s", kind="col"),),
        feature_id=1272,
    ),
    FeatureSpec(
        name="lwp_mid_10bps_fut_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid 10bps over 300s.",
        depends_on=(Dep(name="lwp_mid_10bps_fut_1s", kind="col"),),
        feature_id=1273,
    ),
    FeatureSpec(
        name="lwp_mid_10bps_fut_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid 10bps over 900s.",
        depends_on=(Dep(name="lwp_mid_10bps_fut_1s", kind="col"),),
        feature_id=1274,
    ),
    FeatureSpec(
        name="lwp_mid_10bps_spot_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid 10bps over 60s.",
        depends_on=(Dep(name="lwp_mid_10bps_spot_1s", kind="col"),),
        feature_id=1275,
    ),
    FeatureSpec(
        name="lwp_mid_10bps_spot_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid 10bps over 300s.",
        depends_on=(Dep(name="lwp_mid_10bps_spot_1s", kind="col"),),
        feature_id=1276,
    ),
    FeatureSpec(
        name="lwp_mid_10bps_spot_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid 10bps over 900s.",
        depends_on=(Dep(name="lwp_mid_10bps_spot_1s", kind="col"),),
        feature_id=1277,
    ),
    FeatureSpec(
        name="lwp_mid_struct50_fut_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid struct50 over 60s.",
        depends_on=(Dep(name="lwp_mid_struct50_fut_1s", kind="col"),),
        feature_id=1278,
    ),
    FeatureSpec(
        name="lwp_mid_struct50_fut_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid struct50 over 300s.",
        depends_on=(Dep(name="lwp_mid_struct50_fut_1s", kind="col"),),
        feature_id=1279,
    ),
    FeatureSpec(
        name="lwp_mid_struct50_fut_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid struct50 over 900s.",
        depends_on=(Dep(name="lwp_mid_struct50_fut_1s", kind="col"),),
        feature_id=1280,
    ),
    FeatureSpec(
        name="lwp_mid_struct50_spot_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid struct50 over 60s.",
        depends_on=(Dep(name="lwp_mid_struct50_spot_1s", kind="col"),),
        feature_id=1281,
    ),
    FeatureSpec(
        name="lwp_mid_struct50_spot_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid struct50 over 300s.",
        depends_on=(Dep(name="lwp_mid_struct50_spot_1s", kind="col"),),
        feature_id=1282,
    ),
    FeatureSpec(
        name="lwp_mid_struct50_spot_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid struct50 over 900s.",
        depends_on=(Dep(name="lwp_mid_struct50_spot_1s", kind="col"),),
        feature_id=1283,
    ),
    FeatureSpec(
        name="lwp_mid_struct100_fut_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid struct100 over 60s.",
        depends_on=(Dep(name="lwp_mid_struct100_fut_1s", kind="col"),),
        feature_id=1284,
    ),
    FeatureSpec(
        name="lwp_mid_struct100_fut_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid struct100 over 300s.",
        depends_on=(Dep(name="lwp_mid_struct100_fut_1s", kind="col"),),
        feature_id=1285,
    ),
    FeatureSpec(
        name="lwp_mid_struct100_fut_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid struct100 over 900s.",
        depends_on=(Dep(name="lwp_mid_struct100_fut_1s", kind="col"),),
        feature_id=1286,
    ),
    FeatureSpec(
        name="lwp_mid_struct100_spot_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid struct100 over 60s.",
        depends_on=(Dep(name="lwp_mid_struct100_spot_1s", kind="col"),),
        feature_id=1287,
    ),
    FeatureSpec(
        name="lwp_mid_struct100_spot_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid struct100 over 300s.",
        depends_on=(Dep(name="lwp_mid_struct100_spot_1s", kind="col"),),
        feature_id=1288,
    ),
    FeatureSpec(
        name="lwp_mid_struct100_spot_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Price",
        description="Rolling mean of LWP-mid struct100 over 900s.",
        depends_on=(Dep(name="lwp_mid_struct100_spot_1s", kind="col"),),
        feature_id=1289,
    ),
    # === derived.basis ===
    FeatureSpec(
        name="basis_1s",
        stage="S1",
        operator="derived.basis",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Price",
        description="Basis: mid_fut - mid_spot.",
        depends_on=(Dep(name="mid_fut_1s", kind="col"), Dep(name="mid_spot_1s", kind="col"),),
        feature_id=1290,
    ),
    FeatureSpec(
        name="basis_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Price",
        description="Rolling mean of basis over 300s.",
        depends_on=(Dep(name="basis_1s", kind="col"),),
        feature_id=1291,
    ),
    FeatureSpec(
        name="basis_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Price",
        description="Rolling mean of basis over 60s.",
        depends_on=(Dep(name="basis_1s", kind="col"),),
        feature_id=1292,
    ),

    # === l2.lwp ===
    # NOTE: lwp_fut_1s / lwp_spot_1s removed. With only best_ask/best_bid as deps
    # (no sizes), they computed ask/bid ratio ≈ 1.0 instead of actual LWP.
    # True LWP requires best-level quantities. Use lwp_mid_*_1s from S0 instead.

    # === l2.mid_touch ===
    # NOTE: mid_touch_fut_1s / mid_touch_spot_1s removed. l2.mid_touch = (bid+ask)/2
    # which is identical to mid_fut/spot_1s — same root cause as lwp removal.
    # True microprice requires best_ask_qty/best_bid_qty which are not in S1 output.
    # Downstream: mid_touch_dev_* (S2) and z_mid_touch_dev_* (S3) also removed.

    # === derived.roll_mean ===
    FeatureSpec(
        name="spread_fut_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Price",
        description="Rolling mean over window.",
        depends_on=(Dep(name="spread_fut_1s", kind="col"),),
        feature_id=1293,
    ),
    FeatureSpec(
        name="spread_fut_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Price",
        description="Rolling mean over window.",
        depends_on=(Dep(name="spread_fut_1s", kind="col"),),
        feature_id=1294,
    ),
    FeatureSpec(
        name="spread_fut_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Price",
        description="Rolling mean over window.",
        depends_on=(Dep(name="spread_fut_1s", kind="col"),),
        feature_id=1295,
    ),
    FeatureSpec(
        name="spread_spot_300s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Price",
        description="Rolling mean over window.",
        depends_on=(Dep(name="spread_spot_1s", kind="col"),),
        feature_id=1296,
    ),
    FeatureSpec(
        name="spread_spot_60s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Price",
        description="Rolling mean over window.",
        depends_on=(Dep(name="spread_spot_1s", kind="col"),),
        feature_id=1297,
    ),
    FeatureSpec(
        name="spread_spot_900s",
        stage="S1",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Price",
        description="Rolling mean over window.",
        depends_on=(Dep(name="spread_spot_1s", kind="col"),),
        feature_id=1298,
    ),

    # === trades.vwap ===
    FeatureSpec(
        name="vwap_fut_1s",
        stage="S1",
        operator="trades.vwap",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Price",
        description="VWAP: notional / volume.",
        depends_on=(Dep(name="notional_fut_1s", kind="col"), Dep(name="volume_fut_1s", kind="col"),),
        feature_id=1299,
    ),
    FeatureSpec(
        name="vwap_spot_1s",
        stage="S1",
        operator="trades.vwap",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Price",
        description="VWAP: notional / volume.",
        depends_on=(Dep(name="notional_spot_1s", kind="col"), Dep(name="volume_spot_1s", kind="col"),),
        feature_id=1300,
    ),
]