# etl/spec/s1/s1_pressure.py
# ==============================================================================
# S1 Feature Specs: Pressure
#
# Binance-only pipeline | Source: S0 features (parquet)
# 44 features | Feature IDs: 1222-1265
# ==============================================================================

from typing import List
from etl.spec import FeatureSpec, Dep


S1_PRESSURE_FEATURES: List[FeatureSpec] = [

    # === l2.net_pressure ===
    FeatureSpec(
        name="net_pressure_fut_1bps_15s",
        stage="S1",
        operator="l2.net_pressure",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Pressure",
        description="(add_bid - cancel_bid) - (add_ask - cancel_ask). Net order flow pressure.",
        depends_on=(Dep(name="add_rate_bid_fut_1bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_1bps_1s", kind="col"), Dep(name="add_rate_ask_fut_1bps_1s", kind="col"), Dep(name="cancel_rate_ask_fut_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"),),
        feature_id=1222,
    ),
    FeatureSpec(
        name="net_pressure_fut_1bps_5s",
        stage="S1",
        operator="l2.net_pressure",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Pressure",
        description="(add_bid - cancel_bid) - (add_ask - cancel_ask). Net order flow pressure.",
        depends_on=(Dep(name="add_rate_bid_fut_1bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_1bps_1s", kind="col"), Dep(name="add_rate_ask_fut_1bps_1s", kind="col"), Dep(name="cancel_rate_ask_fut_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"),),
        feature_id=1223,
    ),
    FeatureSpec(
        name="net_pressure_fut_1bps_60s",
        stage="S1",
        operator="l2.net_pressure",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Pressure",
        description="(add_bid - cancel_bid) - (add_ask - cancel_ask). Net order flow pressure.",
        depends_on=(Dep(name="add_rate_bid_fut_1bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_1bps_1s", kind="col"), Dep(name="add_rate_ask_fut_1bps_1s", kind="col"), Dep(name="cancel_rate_ask_fut_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"),),
        feature_id=1224,
    ),
    FeatureSpec(
        name="net_pressure_spot_1bps_15s",
        stage="S1",
        operator="l2.net_pressure",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Pressure",
        description="(add_bid - cancel_bid) - (add_ask - cancel_ask). Net order flow pressure.",
        depends_on=(Dep(name="add_rate_bid_spot_1bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_1bps_1s", kind="col"), Dep(name="add_rate_ask_spot_1bps_1s", kind="col"), Dep(name="cancel_rate_ask_spot_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"),),
        feature_id=1225,
    ),
    FeatureSpec(
        name="net_pressure_spot_1bps_5s",
        stage="S1",
        operator="l2.net_pressure",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Pressure",
        description="(add_bid - cancel_bid) - (add_ask - cancel_ask). Net order flow pressure.",
        depends_on=(Dep(name="add_rate_bid_spot_1bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_1bps_1s", kind="col"), Dep(name="add_rate_ask_spot_1bps_1s", kind="col"), Dep(name="cancel_rate_ask_spot_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"),),
        feature_id=1226,
    ),
    FeatureSpec(
        name="net_pressure_spot_1bps_60s",
        stage="S1",
        operator="l2.net_pressure",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Pressure",
        description="(add_bid - cancel_bid) - (add_ask - cancel_ask). Net order flow pressure.",
        depends_on=(Dep(name="add_rate_bid_spot_1bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_1bps_1s", kind="col"), Dep(name="add_rate_ask_spot_1bps_1s", kind="col"), Dep(name="cancel_rate_ask_spot_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"),),
        feature_id=1227,
    ),

    # === l2.queue_imbalance_1s ===
    FeatureSpec(
        name="queue_imb_fut_1bps_1s",
        stage="S1",
        operator="l2.queue_imbalance_1s",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask + eps).",
        depends_on=(Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_1bps_fut_1s", kind="col"),),
        feature_id=1228,
    ),
    FeatureSpec(
        name="queue_imb_fut_2bps_1s",
        stage="S1",
        operator="l2.queue_imbalance_1s",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask + eps).",
        depends_on=(Dep(name="depth_notional_bid_2bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_2bps_fut_1s", kind="col"),),
        feature_id=1229,
    ),
    FeatureSpec(
        name="queue_imb_fut_5bps_1s",
        stage="S1",
        operator="l2.queue_imbalance_1s",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask + eps).",
        depends_on=(Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"),),
        feature_id=1230,
    ),
    FeatureSpec(
        name="queue_imb_spot_1bps_1s",
        stage="S1",
        operator="l2.queue_imbalance_1s",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask + eps).",
        depends_on=(Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_1bps_spot_1s", kind="col"),),
        feature_id=1231,
    ),
    FeatureSpec(
        name="queue_imb_spot_2bps_1s",
        stage="S1",
        operator="l2.queue_imbalance_1s",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask + eps).",
        depends_on=(Dep(name="depth_notional_bid_2bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_2bps_spot_1s", kind="col"),),
        feature_id=1232,
    ),
    FeatureSpec(
        name="queue_imb_spot_5bps_1s",
        stage="S1",
        operator="l2.queue_imbalance_1s",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask + eps).",
        depends_on=(Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"),),
        feature_id=1233,
    ),

    # === l2.queue_pressure ===
    FeatureSpec(
        name="queue_pressure_fut_10bps_15s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_10bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_10bps_fut_1s", kind="col"),),
        feature_id=1234,
    ),
    FeatureSpec(
        name="queue_pressure_fut_10bps_5s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_10bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_10bps_fut_1s", kind="col"),),
        feature_id=1235,
    ),
    FeatureSpec(
        name="queue_pressure_fut_10bps_60s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_10bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_10bps_fut_1s", kind="col"),),
        feature_id=1236,
    ),
    FeatureSpec(
        name="queue_pressure_fut_1bps_1s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_1bps_fut_1s", kind="col"),),
        feature_id=1237,
    ),
    FeatureSpec(
        name="queue_pressure_fut_1bps_5s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_1bps_fut_1s", kind="col"),),
        feature_id=1238,
    ),
    FeatureSpec(
        name="queue_pressure_fut_2bps_15s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_2bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_2bps_fut_1s", kind="col"),),
        feature_id=1239,
    ),
    FeatureSpec(
        name="queue_pressure_fut_2bps_1s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_2bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_2bps_fut_1s", kind="col"),),
        feature_id=1240,
    ),
    FeatureSpec(
        name="queue_pressure_fut_2bps_5s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_2bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_2bps_fut_1s", kind="col"),),
        feature_id=1241,
    ),
    FeatureSpec(
        name="queue_pressure_fut_2bps_60s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_2bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_2bps_fut_1s", kind="col"),),
        feature_id=1242,
    ),
    FeatureSpec(
        name="queue_pressure_fut_5bps_15s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"),),
        feature_id=1243,
    ),
    FeatureSpec(
        name="queue_pressure_fut_5bps_1s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"),),
        feature_id=1244,
    ),
    FeatureSpec(
        name="queue_pressure_fut_5bps_5s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"),),
        feature_id=1245,
    ),
    FeatureSpec(
        name="queue_pressure_fut_5bps_60s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"),),
        feature_id=1246,
    ),

    # === l2.queue_pressure_log_1s ===
    FeatureSpec(
        name="queue_pressure_log_fut_1bps_1s",
        stage="S1",
        operator="l2.queue_pressure_log_1s",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Pressure",
        description="log((depth_bid + eps) / (depth_ask + eps)). Log pressure.",
        depends_on=(Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_1bps_fut_1s", kind="col"),),
        feature_id=1247,
    ),
    FeatureSpec(
        name="queue_pressure_log_fut_2bps_1s",
        stage="S1",
        operator="l2.queue_pressure_log_1s",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Pressure",
        description="log((depth_bid + eps) / (depth_ask + eps)). Log pressure.",
        depends_on=(Dep(name="depth_notional_bid_2bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_2bps_fut_1s", kind="col"),),
        feature_id=1248,
    ),
    FeatureSpec(
        name="queue_pressure_log_fut_5bps_1s",
        stage="S1",
        operator="l2.queue_pressure_log_1s",
        params={'market_scope': 'Futures', 'resample': '1s'},
        group="Pressure",
        description="log((depth_bid + eps) / (depth_ask + eps)). Log pressure.",
        depends_on=(Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"), Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"),),
        feature_id=1249,
    ),
    FeatureSpec(
        name="queue_pressure_log_spot_1bps_1s",
        stage="S1",
        operator="l2.queue_pressure_log_1s",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Pressure",
        description="log((depth_bid + eps) / (depth_ask + eps)). Log pressure.",
        depends_on=(Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_1bps_spot_1s", kind="col"),),
        feature_id=1250,
    ),
    FeatureSpec(
        name="queue_pressure_log_spot_2bps_1s",
        stage="S1",
        operator="l2.queue_pressure_log_1s",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Pressure",
        description="log((depth_bid + eps) / (depth_ask + eps)). Log pressure.",
        depends_on=(Dep(name="depth_notional_bid_2bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_2bps_spot_1s", kind="col"),),
        feature_id=1251,
    ),
    FeatureSpec(
        name="queue_pressure_log_spot_5bps_1s",
        stage="S1",
        operator="l2.queue_pressure_log_1s",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Pressure",
        description="log((depth_bid + eps) / (depth_ask + eps)). Log pressure.",
        depends_on=(Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"),),
        feature_id=1252,
    ),

    # === l2.queue_pressure ===
    FeatureSpec(
        name="queue_pressure_spot_10bps_15s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_10bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_10bps_spot_1s", kind="col"),),
        feature_id=1253,
    ),
    FeatureSpec(
        name="queue_pressure_spot_10bps_5s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_10bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_10bps_spot_1s", kind="col"),),
        feature_id=1254,
    ),
    FeatureSpec(
        name="queue_pressure_spot_10bps_60s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_10bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_10bps_spot_1s", kind="col"),),
        feature_id=1255,
    ),
    FeatureSpec(
        name="queue_pressure_spot_1bps_1s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_1bps_spot_1s", kind="col"),),
        feature_id=1256,
    ),
    FeatureSpec(
        name="queue_pressure_spot_1bps_5s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_1bps_spot_1s", kind="col"),),
        feature_id=1257,
    ),
    FeatureSpec(
        name="queue_pressure_spot_2bps_15s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_2bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_2bps_spot_1s", kind="col"),),
        feature_id=1258,
    ),
    FeatureSpec(
        name="queue_pressure_spot_2bps_1s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_2bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_2bps_spot_1s", kind="col"),),
        feature_id=1259,
    ),
    FeatureSpec(
        name="queue_pressure_spot_2bps_5s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_2bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_2bps_spot_1s", kind="col"),),
        feature_id=1260,
    ),
    FeatureSpec(
        name="queue_pressure_spot_2bps_60s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_2bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_2bps_spot_1s", kind="col"),),
        feature_id=1261,
    ),
    FeatureSpec(
        name="queue_pressure_spot_5bps_15s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"),),
        feature_id=1262,
    ),
    FeatureSpec(
        name="queue_pressure_spot_5bps_1s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Spot', 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"),),
        feature_id=1263,
    ),
    FeatureSpec(
        name="queue_pressure_spot_5bps_5s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"),),
        feature_id=1264,
    ),
    FeatureSpec(
        name="queue_pressure_spot_5bps_60s",
        stage="S1",
        operator="l2.queue_pressure",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Pressure",
        description="(depth_bid - depth_ask) / (depth_bid + depth_ask). Linear pressure.",
        depends_on=(Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"), Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"),),
        feature_id=1265,
    ),
]