# etl/spec/s2/s2_absorption.py
# ==============================================================================
# S2 Feature Specs: Absorption
#
# Binance-only pipeline | Source: S1 features (+ some S0 columns)
# 24 features | Feature IDs: 456–479
# ==============================================================================

from typing import List
from etl.spec import FeatureSpec, Dep


S2_ABSORPTION_FEATURES: List[FeatureSpec] = [

    # === derived.asymmetry ===
    FeatureSpec(
        name="absorption_asymmetry_fut_1bps_15s",
        stage="S2",
        operator="derived.asymmetry",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Absorption",
        description="(ask - bid) / (ask + bid) asymmetry ratio.",
        depends_on=(Dep(name="absorption_volume_ask_fut_1bps_15s", kind="col"), Dep(name="absorption_volume_bid_fut_1bps_15s", kind="col"),),
        feature_id=2000,
    ),
    FeatureSpec(
        name="absorption_asymmetry_spot_1bps_15s",
        stage="S2",
        operator="derived.asymmetry",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Absorption",
        description="(ask - bid) / (ask + bid) asymmetry ratio.",
        depends_on=(Dep(name="absorption_volume_ask_spot_1bps_15s", kind="col"), Dep(name="absorption_volume_bid_spot_1bps_15s", kind="col"),),
        feature_id=2001,
    ),

    # === derived.roll_mean ===
    FeatureSpec(
        name="aggressor_absorption_ratio_fut_2bps_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Absorption",
        description="Rolling mean over window.",
        depends_on=(Dep(name="aggr_absorp_ratio_ask_fut_2bps_1s", kind="col"), Dep(name="aggr_absorp_ratio_bid_fut_2bps_1s", kind="col"),),
        feature_id=2002,
    ),
    FeatureSpec(
        name="aggressor_absorption_ratio_fut_5bps_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Absorption",
        description="Rolling mean over window.",
        depends_on=(Dep(name="aggr_absorp_ratio_ask_fut_5bps_1s", kind="col"), Dep(name="aggr_absorp_ratio_bid_fut_5bps_1s", kind="col"),),
        feature_id=2003,
    ),
    FeatureSpec(
        name="aggressor_absorption_ratio_spot_2bps_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Absorption",
        description="Rolling mean over window.",
        depends_on=(Dep(name="aggr_absorp_ratio_ask_spot_2bps_1s", kind="col"), Dep(name="aggr_absorp_ratio_bid_spot_2bps_1s", kind="col"),),
        feature_id=2004,
    ),
    FeatureSpec(
        name="aggressor_absorption_ratio_spot_5bps_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Absorption",
        description="Rolling mean over window.",
        depends_on=(Dep(name="aggr_absorp_ratio_ask_spot_5bps_1s", kind="col"), Dep(name="aggr_absorp_ratio_bid_spot_5bps_1s", kind="col"),),
        feature_id=2005,
    ),

    # === derived.roll_sum ===
    FeatureSpec(
        name="absorption_volume_ask_fut_1bps_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Absorption",
        description="Rolling sum over window.",
        depends_on=(Dep(name="absorption_volume_ask_fut_1bps_1s", kind="col"),),
        feature_id=2006,
    ),
    FeatureSpec(
        name="absorption_volume_ask_spot_1bps_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Absorption",
        description="Rolling sum over window.",
        depends_on=(Dep(name="absorption_volume_ask_spot_1bps_1s", kind="col"),),
        feature_id=2007,
    ),
    FeatureSpec(
        name="absorption_volume_bid_fut_1bps_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Absorption",
        description="Rolling sum over window.",
        depends_on=(Dep(name="absorption_volume_bid_fut_1bps_1s", kind="col"),),
        feature_id=2008,
    ),
    FeatureSpec(
        name="absorption_volume_bid_spot_1bps_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Absorption",
        description="Rolling sum over window.",
        depends_on=(Dep(name="absorption_volume_bid_spot_1bps_1s", kind="col"),),
        feature_id=2009,
    ),

    # === l2.absorb_refill_ask ===
    FeatureSpec(
        name="absorb_refill_ask_fut_10bps_1s",
        stage="S2",
        operator="l2.absorb_refill_ask",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Absorption",
        description="Absorption + refill on ask side: add_rate weighted by taker sell vol.",
        depends_on=(Dep(name="add_rate_ask_fut_10bps_1s", kind="col"), Dep(name="taker_sell_vol_fut_1s", kind="col"),),
        feature_id=2010,
    ),
    FeatureSpec(
        name="absorb_refill_ask_fut_2bps_1s",
        stage="S2",
        operator="l2.absorb_refill_ask",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Absorption",
        description="Absorption + refill on ask side: add_rate weighted by taker sell vol.",
        depends_on=(Dep(name="add_rate_ask_fut_2bps_1s", kind="col"), Dep(name="taker_sell_vol_fut_1s", kind="col"),),
        feature_id=2011,
    ),
    FeatureSpec(
        name="absorb_refill_ask_fut_5bps_1s",
        stage="S2",
        operator="l2.absorb_refill_ask",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Absorption",
        description="Absorption + refill on ask side: add_rate weighted by taker sell vol.",
        depends_on=(Dep(name="add_rate_ask_fut_5bps_1s", kind="col"), Dep(name="taker_sell_vol_fut_1s", kind="col"),),
        feature_id=2012,
    ),
    FeatureSpec(
        name="absorb_refill_ask_spot_10bps_1s",
        stage="S2",
        operator="l2.absorb_refill_ask",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Absorption",
        description="Absorption + refill on ask side: add_rate weighted by taker sell vol.",
        depends_on=(Dep(name="add_rate_ask_spot_10bps_1s", kind="col"), Dep(name="taker_sell_vol_spot_1s", kind="col"),),
        feature_id=2013,
    ),
    FeatureSpec(
        name="absorb_refill_ask_spot_2bps_1s",
        stage="S2",
        operator="l2.absorb_refill_ask",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Absorption",
        description="Absorption + refill on ask side: add_rate weighted by taker sell vol.",
        depends_on=(Dep(name="add_rate_ask_spot_2bps_1s", kind="col"), Dep(name="taker_sell_vol_spot_1s", kind="col"),),
        feature_id=2014,
    ),
    FeatureSpec(
        name="absorb_refill_ask_spot_5bps_1s",
        stage="S2",
        operator="l2.absorb_refill_ask",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Absorption",
        description="Absorption + refill on ask side: add_rate weighted by taker sell vol.",
        depends_on=(Dep(name="add_rate_ask_spot_5bps_1s", kind="col"), Dep(name="taker_sell_vol_spot_1s", kind="col"),),
        feature_id=2015,
    ),

    # === l2.absorb_refill_bid ===
    FeatureSpec(
        name="absorb_refill_bid_fut_10bps_1s",
        stage="S2",
        operator="l2.absorb_refill_bid",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Absorption",
        description="Absorption + refill on bid side: add_rate weighted by taker buy vol.",
        depends_on=(Dep(name="add_rate_bid_fut_10bps_1s", kind="col"), Dep(name="taker_buy_vol_fut_1s", kind="col"),),
        feature_id=2016,
    ),
    FeatureSpec(
        name="absorb_refill_bid_fut_2bps_1s",
        stage="S2",
        operator="l2.absorb_refill_bid",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Absorption",
        description="Absorption + refill on bid side: add_rate weighted by taker buy vol.",
        depends_on=(Dep(name="add_rate_bid_fut_2bps_1s", kind="col"), Dep(name="taker_buy_vol_fut_1s", kind="col"),),
        feature_id=2017,
    ),
    FeatureSpec(
        name="absorb_refill_bid_fut_5bps_1s",
        stage="S2",
        operator="l2.absorb_refill_bid",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Absorption",
        description="Absorption + refill on bid side: add_rate weighted by taker buy vol.",
        depends_on=(Dep(name="add_rate_bid_fut_5bps_1s", kind="col"), Dep(name="taker_buy_vol_fut_1s", kind="col"),),
        feature_id=2018,
    ),
    FeatureSpec(
        name="absorb_refill_bid_spot_10bps_1s",
        stage="S2",
        operator="l2.absorb_refill_bid",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Absorption",
        description="Absorption + refill on bid side: add_rate weighted by taker buy vol.",
        depends_on=(Dep(name="add_rate_bid_spot_10bps_1s", kind="col"), Dep(name="taker_buy_vol_spot_1s", kind="col"),),
        feature_id=2019,
    ),
    FeatureSpec(
        name="absorb_refill_bid_spot_2bps_1s",
        stage="S2",
        operator="l2.absorb_refill_bid",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Absorption",
        description="Absorption + refill on bid side: add_rate weighted by taker buy vol.",
        depends_on=(Dep(name="add_rate_bid_spot_2bps_1s", kind="col"), Dep(name="taker_buy_vol_spot_1s", kind="col"),),
        feature_id=2020,
    ),
    FeatureSpec(
        name="absorb_refill_bid_spot_5bps_1s",
        stage="S2",
        operator="l2.absorb_refill_bid",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Absorption",
        description="Absorption + refill on bid side: add_rate weighted by taker buy vol.",
        depends_on=(Dep(name="add_rate_bid_spot_5bps_1s", kind="col"), Dep(name="taker_buy_vol_spot_1s", kind="col"),),
        feature_id=2021,
    ),

    # === trades.trade_absorption_ratio_1s ===
    FeatureSpec(
        name="trade_absorption_ratio_fut_1s",
        stage="S2",
        operator="trades.trade_absorption_ratio_1s",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Absorption",
        description="Trade absorption ratio: |ret| / volume. Price efficiency.",
        depends_on=(Dep(name="ret_mid_fut_1s", kind="col"), Dep(name="volume_fut_1s", kind="col"),),
        feature_id=2022,
    ),
    FeatureSpec(
        name="trade_absorption_ratio_spot_1s",
        stage="S2",
        operator="trades.trade_absorption_ratio_1s",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Absorption",
        description="Trade absorption ratio: |ret| / volume. Price efficiency.",
        depends_on=(Dep(name="ret_mid_spot_1s", kind="col"), Dep(name="volume_spot_1s", kind="col"),),
        feature_id=2023,
    ),
]