# etl/spec/s2/s2_bookshape.py
# ==============================================================================
# S2 Feature Specs: Bookshape
#
# Binance-only pipeline | Source: S1 features (+ some S0 columns)
# 82 features | Feature IDs: 500–601
# ==============================================================================

from typing import List
from etl.spec import FeatureSpec, Dep


S2_BOOKSHAPE_FEATURES: List[FeatureSpec] = [

    # === derived.ratio ===
    FeatureSpec(
        name="depth_gradient_fut_struct100_1s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Bookshape",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="depth_gradient_ask_fut_struct100_1s", kind="col"), Dep(name="depth_gradient_bid_fut_struct100_1s", kind="col"),),
        feature_id=2042,
    ),
    FeatureSpec(
        name="depth_gradient_fut_struct50_1s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Bookshape",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="depth_gradient_ask_fut_struct50_1s", kind="col"), Dep(name="depth_gradient_bid_fut_struct50_1s", kind="col"),),
        feature_id=2043,
    ),
    FeatureSpec(
        name="depth_gradient_spot_struct100_1s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Bookshape",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="depth_gradient_ask_spot_struct100_1s", kind="col"), Dep(name="depth_gradient_bid_spot_struct100_1s", kind="col"),),
        feature_id=2044,
    ),
    FeatureSpec(
        name="depth_gradient_spot_struct50_1s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Bookshape",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="depth_gradient_ask_spot_struct50_1s", kind="col"), Dep(name="depth_gradient_bid_spot_struct50_1s", kind="col"),),
        feature_id=2045,
    ),
    FeatureSpec(
        name="liq_concentration_fut_struct100_1s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Bookshape",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="liq_concentration_ask_fut_struct100_1s", kind="col"), Dep(name="liq_concentration_bid_fut_struct100_1s", kind="col"),),
        feature_id=2046,
    ),
    FeatureSpec(
        name="liq_concentration_fut_struct50_1s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Bookshape",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="liq_concentration_ask_fut_struct50_1s", kind="col"), Dep(name="liq_concentration_bid_fut_struct50_1s", kind="col"),),
        feature_id=2047,
    ),
    FeatureSpec(
        name="liq_concentration_spot_struct100_1s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Bookshape",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="liq_concentration_ask_spot_struct100_1s", kind="col"), Dep(name="liq_concentration_bid_spot_struct100_1s", kind="col"),),
        feature_id=2048,
    ),
    FeatureSpec(
        name="liq_concentration_spot_struct50_1s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Bookshape",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="liq_concentration_ask_spot_struct50_1s", kind="col"), Dep(name="liq_concentration_bid_spot_struct50_1s", kind="col"),),
        feature_id=2049,
    ),

    # === derived.roll_mean ===
    FeatureSpec(
        name="book_asymmetry_fut_struct100_300s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="book_asymmetry_fut_struct100_1s", kind="col"),),
        feature_id=2050,
    ),
    FeatureSpec(
        name="book_asymmetry_fut_struct100_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="book_asymmetry_fut_struct100_1s", kind="col"),),
        feature_id=2051,
    ),
    FeatureSpec(
        name="book_asymmetry_fut_struct100_900s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="book_asymmetry_fut_struct100_1s", kind="col"),),
        feature_id=2052,
    ),
    FeatureSpec(
        name="book_asymmetry_fut_struct50_300s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="book_asymmetry_fut_struct50_1s", kind="col"),),
        feature_id=2053,
    ),
    FeatureSpec(
        name="book_asymmetry_fut_struct50_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="book_asymmetry_fut_struct50_1s", kind="col"),),
        feature_id=2054,
    ),
    FeatureSpec(
        name="book_asymmetry_fut_struct50_900s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="book_asymmetry_fut_struct50_1s", kind="col"),),
        feature_id=2055,
    ),
    FeatureSpec(
        name="book_asymmetry_spot_struct100_300s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="book_asymmetry_spot_struct100_1s", kind="col"),),
        feature_id=2056,
    ),
    FeatureSpec(
        name="book_asymmetry_spot_struct100_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="book_asymmetry_spot_struct100_1s", kind="col"),),
        feature_id=2057,
    ),
    FeatureSpec(
        name="book_asymmetry_spot_struct100_900s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="book_asymmetry_spot_struct100_1s", kind="col"),),
        feature_id=2058,
    ),
    FeatureSpec(
        name="book_asymmetry_spot_struct50_300s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="book_asymmetry_spot_struct50_1s", kind="col"),),
        feature_id=2059,
    ),
    FeatureSpec(
        name="book_asymmetry_spot_struct50_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="book_asymmetry_spot_struct50_1s", kind="col"),),
        feature_id=2060,
    ),
    FeatureSpec(
        name="book_asymmetry_spot_struct50_900s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="book_asymmetry_spot_struct50_1s", kind="col"),),
        feature_id=2061,
    ),
    FeatureSpec(
        name="liq_sum_fut_300s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="liq_sum_fut_1s", kind="col"),),
        feature_id=2062,
    ),
    FeatureSpec(
        name="liq_sum_fut_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="liq_sum_fut_1s", kind="col"),),
        feature_id=2063,
    ),
    FeatureSpec(
        name="liq_sum_fut_900s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="liq_sum_fut_1s", kind="col"),),
        feature_id=2064,
    ),
    FeatureSpec(
        name="liq_sum_spot_300s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="liq_sum_spot_1s", kind="col"),),
        feature_id=2065,
    ),
    FeatureSpec(
        name="liq_sum_spot_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="liq_sum_spot_1s", kind="col"),),
        feature_id=2066,
    ),
    FeatureSpec(
        name="liq_sum_spot_900s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="liq_sum_spot_1s", kind="col"),),
        feature_id=2067,
    ),
    FeatureSpec(
        name="max_liq_distance_ask_fut_5bps_300s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_liq_distance_ask_5bps_fut_1s", kind="col"),),
        feature_id=2068,
    ),
    FeatureSpec(
        name="max_liq_distance_ask_fut_5bps_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_liq_distance_ask_5bps_fut_1s", kind="col"),),
        feature_id=2069,
    ),
    FeatureSpec(
        name="max_liq_distance_ask_spot_5bps_300s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_liq_distance_ask_5bps_spot_1s", kind="col"),),
        feature_id=2070,
    ),
    FeatureSpec(
        name="max_liq_distance_ask_spot_5bps_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_liq_distance_ask_5bps_spot_1s", kind="col"),),
        feature_id=2071,
    ),
    FeatureSpec(
        name="max_liq_distance_bid_fut_5bps_300s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_liq_distance_bid_5bps_fut_1s", kind="col"),),
        feature_id=2072,
    ),
    FeatureSpec(
        name="max_liq_distance_bid_fut_5bps_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_liq_distance_bid_5bps_fut_1s", kind="col"),),
        feature_id=2073,
    ),
    FeatureSpec(
        name="max_liq_distance_bid_spot_5bps_300s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_liq_distance_bid_5bps_spot_1s", kind="col"),),
        feature_id=2074,
    ),
    FeatureSpec(
        name="max_liq_distance_bid_spot_5bps_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling mean over window.",
        depends_on=(Dep(name="max_liq_distance_bid_5bps_spot_1s", kind="col"),),
        feature_id=2075,
    ),

    # === derived.roll_sum ===
    FeatureSpec(
        name="depth_gradient_ask_fut_struct100_300s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_ask_fut_struct100_1s", kind="col"),),
        feature_id=2076,
    ),
    FeatureSpec(
        name="depth_gradient_ask_fut_struct100_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_ask_fut_struct100_1s", kind="col"),),
        feature_id=2077,
    ),
    FeatureSpec(
        name="depth_gradient_ask_fut_struct100_900s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_ask_fut_struct100_1s", kind="col"),),
        feature_id=2078,
    ),
    FeatureSpec(
        name="depth_gradient_ask_fut_struct50_300s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_ask_fut_struct50_1s", kind="col"),),
        feature_id=2079,
    ),
    FeatureSpec(
        name="depth_gradient_ask_fut_struct50_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_ask_fut_struct50_1s", kind="col"),),
        feature_id=2080,
    ),
    FeatureSpec(
        name="depth_gradient_ask_fut_struct50_900s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_ask_fut_struct50_1s", kind="col"),),
        feature_id=2081,
    ),
    FeatureSpec(
        name="depth_gradient_ask_spot_struct100_300s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_ask_spot_struct100_1s", kind="col"),),
        feature_id=2082,
    ),
    FeatureSpec(
        name="depth_gradient_ask_spot_struct100_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_ask_spot_struct100_1s", kind="col"),),
        feature_id=2083,
    ),
    FeatureSpec(
        name="depth_gradient_ask_spot_struct100_900s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_ask_spot_struct100_1s", kind="col"),),
        feature_id=2084,
    ),
    FeatureSpec(
        name="depth_gradient_ask_spot_struct50_300s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_ask_spot_struct50_1s", kind="col"),),
        feature_id=2085,
    ),
    FeatureSpec(
        name="depth_gradient_ask_spot_struct50_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_ask_spot_struct50_1s", kind="col"),),
        feature_id=2086,
    ),
    FeatureSpec(
        name="depth_gradient_ask_spot_struct50_900s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_ask_spot_struct50_1s", kind="col"),),
        feature_id=2087,
    ),
    FeatureSpec(
        name="depth_gradient_bid_fut_struct100_300s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_bid_fut_struct100_1s", kind="col"),),
        feature_id=2088,
    ),
    FeatureSpec(
        name="depth_gradient_bid_fut_struct100_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_bid_fut_struct100_1s", kind="col"),),
        feature_id=2089,
    ),
    FeatureSpec(
        name="depth_gradient_bid_fut_struct100_900s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_bid_fut_struct100_1s", kind="col"),),
        feature_id=2090,
    ),
    FeatureSpec(
        name="depth_gradient_bid_fut_struct50_300s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_bid_fut_struct50_1s", kind="col"),),
        feature_id=2091,
    ),
    FeatureSpec(
        name="depth_gradient_bid_fut_struct50_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_bid_fut_struct50_1s", kind="col"),),
        feature_id=2092,
    ),
    FeatureSpec(
        name="depth_gradient_bid_fut_struct50_900s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_bid_fut_struct50_1s", kind="col"),),
        feature_id=2093,
    ),
    FeatureSpec(
        name="depth_gradient_bid_spot_struct100_300s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_bid_spot_struct100_1s", kind="col"),),
        feature_id=2094,
    ),
    FeatureSpec(
        name="depth_gradient_bid_spot_struct100_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_bid_spot_struct100_1s", kind="col"),),
        feature_id=2095,
    ),
    FeatureSpec(
        name="depth_gradient_bid_spot_struct100_900s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_bid_spot_struct100_1s", kind="col"),),
        feature_id=2096,
    ),
    FeatureSpec(
        name="depth_gradient_bid_spot_struct50_300s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_bid_spot_struct50_1s", kind="col"),),
        feature_id=2097,
    ),
    FeatureSpec(
        name="depth_gradient_bid_spot_struct50_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_bid_spot_struct50_1s", kind="col"),),
        feature_id=2098,
    ),
    FeatureSpec(
        name="depth_gradient_bid_spot_struct50_900s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="depth_gradient_bid_spot_struct50_1s", kind="col"),),
        feature_id=2099,
    ),
    FeatureSpec(
        name="liq_concentration_ask_fut_struct100_300s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_ask_fut_struct100_1s", kind="col"),),
        feature_id=2100,
    ),
    FeatureSpec(
        name="liq_concentration_ask_fut_struct100_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_ask_fut_struct100_1s", kind="col"),),
        feature_id=2101,
    ),
    FeatureSpec(
        name="liq_concentration_ask_fut_struct100_900s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_ask_fut_struct100_1s", kind="col"),),
        feature_id=2102,
    ),
    FeatureSpec(
        name="liq_concentration_ask_fut_struct50_300s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_ask_fut_struct50_1s", kind="col"),),
        feature_id=2103,
    ),
    FeatureSpec(
        name="liq_concentration_ask_fut_struct50_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_ask_fut_struct50_1s", kind="col"),),
        feature_id=2104,
    ),
    FeatureSpec(
        name="liq_concentration_ask_fut_struct50_900s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_ask_fut_struct50_1s", kind="col"),),
        feature_id=2105,
    ),
    FeatureSpec(
        name="liq_concentration_ask_spot_struct100_300s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_ask_spot_struct100_1s", kind="col"),),
        feature_id=2106,
    ),
    FeatureSpec(
        name="liq_concentration_ask_spot_struct100_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_ask_spot_struct100_1s", kind="col"),),
        feature_id=2107,
    ),
    FeatureSpec(
        name="liq_concentration_ask_spot_struct100_900s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_ask_spot_struct100_1s", kind="col"),),
        feature_id=2108,
    ),
    FeatureSpec(
        name="liq_concentration_ask_spot_struct50_300s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_ask_spot_struct50_1s", kind="col"),),
        feature_id=2109,
    ),
    FeatureSpec(
        name="liq_concentration_ask_spot_struct50_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_ask_spot_struct50_1s", kind="col"),),
        feature_id=2110,
    ),
    FeatureSpec(
        name="liq_concentration_ask_spot_struct50_900s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_ask_spot_struct50_1s", kind="col"),),
        feature_id=2111,
    ),
    FeatureSpec(
        name="liq_concentration_bid_fut_struct100_300s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_bid_fut_struct100_1s", kind="col"),),
        feature_id=2112,
    ),
    FeatureSpec(
        name="liq_concentration_bid_fut_struct100_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_bid_fut_struct100_1s", kind="col"),),
        feature_id=2113,
    ),
    FeatureSpec(
        name="liq_concentration_bid_fut_struct100_900s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_bid_fut_struct100_1s", kind="col"),),
        feature_id=2114,
    ),
    FeatureSpec(
        name="liq_concentration_bid_fut_struct50_300s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_bid_fut_struct50_1s", kind="col"),),
        feature_id=2115,
    ),
    FeatureSpec(
        name="liq_concentration_bid_fut_struct50_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_bid_fut_struct50_1s", kind="col"),),
        feature_id=2116,
    ),
    FeatureSpec(
        name="liq_concentration_bid_fut_struct50_900s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_bid_fut_struct50_1s", kind="col"),),
        feature_id=2117,
    ),
    FeatureSpec(
        name="liq_concentration_bid_spot_struct100_300s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_bid_spot_struct100_1s", kind="col"),),
        feature_id=2118,
    ),
    FeatureSpec(
        name="liq_concentration_bid_spot_struct100_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_bid_spot_struct100_1s", kind="col"),),
        feature_id=2119,
    ),
    FeatureSpec(
        name="liq_concentration_bid_spot_struct100_900s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_bid_spot_struct100_1s", kind="col"),),
        feature_id=2120,
    ),
    FeatureSpec(
        name="liq_concentration_bid_spot_struct50_300s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_bid_spot_struct50_1s", kind="col"),),
        feature_id=2121,
    ),
    FeatureSpec(
        name="liq_concentration_bid_spot_struct50_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_bid_spot_struct50_1s", kind="col"),),
        feature_id=2122,
    ),
    FeatureSpec(
        name="liq_concentration_bid_spot_struct50_900s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Bookshape",
        description="Rolling sum over window.",
        depends_on=(Dep(name="liq_concentration_bid_spot_struct50_1s", kind="col"),),
        feature_id=2123,
    ),
]