# etl/spec/s2/s2_cross_market.py
# ==============================================================================
# S2 Feature Specs: Cross-Market
#
# Binance-only pipeline | Source: S1 features (+ some S0 columns)
# ==============================================================================

from typing import List
from etl.spec import FeatureSpec, Dep


S2_CROSS_MARKET_FEATURES: List[FeatureSpec] = [

    # === derived.basis_vwap ===
    FeatureSpec(
        name="basis_vwap_sf_1s",
        stage="S2",
        operator="derived.basis_vwap",
        params={'market_scope': 'Cross', 'window_s': 1, 'resample': '1s'},
        group="Cross-Market",
        description="Basis via VWAP: vwap_fut - vwap_spot.",
        depends_on=(Dep(name="vwap_fut_1s", kind="col"), Dep(name="vwap_spot_1s", kind="col"),),
        feature_id=2125,
    ),

    # === derived.ratio ===
    FeatureSpec(
        name="liq_imb_sf_struct100_300s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Cross', 'window_s': 300, 'resample': '1s'},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="liq_imb_fut_struct100_300s", kind="col"), Dep(name="liq_imb_spot_struct100_300s", kind="col"),),
        feature_id=2126,
    ),
    FeatureSpec(
        name="liq_imb_sf_struct100_900s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Cross', 'window_s': 900, 'resample': '1s'},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="liq_imb_fut_struct100_900s", kind="col"), Dep(name="liq_imb_spot_struct100_900s", kind="col"),),
        feature_id=2127,
    ),
    FeatureSpec(
        name="liq_imb_sf_struct50_300s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Cross', 'window_s': 300, 'resample': '1s'},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="liq_imb_fut_struct50_300s", kind="col"), Dep(name="liq_imb_spot_struct50_300s", kind="col"),),
        feature_id=2128,
    ),
    FeatureSpec(
        name="liq_imb_sf_struct50_900s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Cross', 'window_s': 900, 'resample': '1s'},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="liq_imb_fut_struct50_300s", kind="col"), Dep(name="liq_imb_spot_struct50_300s", kind="col"),),
        feature_id=2129,
    ),
    FeatureSpec(
        name="trade_count_fut_div_300s",
        stage="S2",
        operator="derived.roll_mean",
        # are NaN ~5% of seconds (denominator market inactive). With strict
        # min_periods=window_s the rolling mean was 100% NaN downstream.
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s', 'min_periods': 60},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="trade_count_fut_div_1s", kind="col"),),
        feature_id=2130,
    ),
    FeatureSpec(
        name="trade_count_fut_div_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s', 'min_periods': 10},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="trade_count_fut_div_1s", kind="col"),),
        feature_id=2131,
    ),
    FeatureSpec(
        name="trade_count_fut_div_900s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s', 'min_periods': 60},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="trade_count_fut_div_1s", kind="col"),),
        feature_id=2132,
    ),
    FeatureSpec(
        name="trade_count_fut_share_300s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="trade_count_fut_share_1s", kind="col"),),
        feature_id=2133,
    ),
    FeatureSpec(
        name="trade_count_fut_share_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="trade_count_fut_share_1s", kind="col"),),
        feature_id=2134,
    ),
    FeatureSpec(
        name="trade_count_fut_share_900s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="trade_count_fut_share_1s", kind="col"),),
        feature_id=2135,
    ),
    FeatureSpec(
        name="trade_count_spot_div_300s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s', 'min_periods': 60},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="trade_count_spot_div_1s", kind="col"),),
        feature_id=2136,
    ),
    FeatureSpec(
        name="trade_count_spot_div_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s', 'min_periods': 10},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="trade_count_spot_div_1s", kind="col"),),
        feature_id=2137,
    ),
    FeatureSpec(
        name="trade_count_spot_div_900s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s', 'min_periods': 60},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="trade_count_spot_div_1s", kind="col"),),
        feature_id=2138,
    ),
    FeatureSpec(
        name="trade_count_spot_share_300s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="trade_count_spot_share_1s", kind="col"),),
        feature_id=2139,
    ),
    FeatureSpec(
        name="trade_count_spot_share_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="trade_count_spot_share_1s", kind="col"),),
        feature_id=2140,
    ),
    FeatureSpec(
        name="trade_count_spot_share_900s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="trade_count_spot_share_1s", kind="col"),),
        feature_id=2141,
    ),
    FeatureSpec(
        name="volume_fut_div_delta_300s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s', 'min_periods': 60},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="volume_fut_div_delta_1s", kind="col"),),
        feature_id=2142,
    ),
    FeatureSpec(
        name="volume_fut_div_delta_900s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s', 'min_periods': 60},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="volume_fut_div_delta_1s", kind="col"),),
        feature_id=2143,
    ),
    FeatureSpec(
        name="volume_spot_div_delta_300s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s', 'min_periods': 60},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="volume_spot_div_delta_1s", kind="col"),),
        feature_id=2144,
    ),
    FeatureSpec(
        name="volume_spot_div_delta_900s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s', 'min_periods': 60},
        group="Cross-Market",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="volume_spot_div_delta_1s", kind="col"),),
        feature_id=2145,
    ),

    # === derived.z_volume_asym ===
    # incorrectly averaging vol_fut and vol_spot then z-scoring the average)
    # to derived.z_volume_asym (which correctly z-scores vol_fut - vol_spot).
    FeatureSpec(
        name="z_volume_asym_fut_minus_spot_300s",
        stage="S2",
        operator="derived.z_volume_asym",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Cross-Market",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="volume_fut_300s", kind="col"), Dep(name="volume_spot_300s", kind="col"),),
        feature_id=2146,
    ),
    FeatureSpec(
        name="z_volume_asym_fut_minus_spot_60s",
        stage="S2",
        operator="derived.z_volume_asym",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Cross-Market",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="volume_fut_60s", kind="col"), Dep(name="volume_spot_60s", kind="col"),),
        feature_id=2147,
    ),
    FeatureSpec(
        name="z_volume_asym_fut_minus_spot_900s",
        stage="S2",
        operator="derived.z_volume_asym",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Cross-Market",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="volume_fut_900s", kind="col"), Dep(name="volume_spot_900s", kind="col"),),
        feature_id=2148,
    ),

    # === derived.roll_mean ===
    FeatureSpec(
        name="spot_fut_taker_activity_share_300s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Cross-Market",
        description="Rolling mean over window.",
        depends_on=(Dep(name="taker_activity_share_sf_1s", kind="col"),),
        feature_id=2149,
    ),
    FeatureSpec(
        name="spot_fut_taker_activity_share_900s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Cross-Market",
        description="Rolling mean over window.",
        depends_on=(Dep(name="taker_activity_share_sf_1s", kind="col"),),
        feature_id=2150,
    ),

    # === derived.sub ===
    FeatureSpec(
        name="book_asymmetry_div_fut_minus_spot_struct100_1s",
        stage="S2",
        operator="derived.sub",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Cross-Market",
        description="Difference: col_a - col_b.",
        depends_on=(Dep(name="book_asymmetry_fut_struct100_1s", kind="col"), Dep(name="book_asymmetry_spot_struct100_1s", kind="col"),),
        feature_id=2151,
    ),
    FeatureSpec(
        name="book_asymmetry_div_fut_minus_spot_struct50_1s",
        stage="S2",
        operator="derived.sub",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Cross-Market",
        description="Difference: col_a - col_b.",
        depends_on=(Dep(name="book_asymmetry_fut_struct50_1s", kind="col"), Dep(name="book_asymmetry_spot_struct50_1s", kind="col"),),
        feature_id=2152,
    ),
    FeatureSpec(
        name="liq_imb_div_fut_minus_spot_struct100_300s",
        stage="S2",
        operator="derived.sub",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Cross-Market",
        description="Difference: col_a - col_b.",
        depends_on=(Dep(name="liq_imb_fut_struct100_300s", kind="col"), Dep(name="liq_imb_spot_struct100_300s", kind="col"),),
        feature_id=2153,
    ),
    FeatureSpec(
        name="liq_imb_div_fut_minus_spot_struct100_60s",
        stage="S2",
        operator="derived.sub",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Cross-Market",
        description="Difference: col_a - col_b.",
        depends_on=(Dep(name="liq_imb_fut_struct100_60s", kind="col"), Dep(name="liq_imb_spot_struct100_60s", kind="col"),),
        feature_id=2154,
    ),
    FeatureSpec(
        name="liq_imb_div_fut_minus_spot_struct100_900s",
        stage="S2",
        operator="derived.sub",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Cross-Market",
        description="Difference: col_a - col_b.",
        depends_on=(Dep(name="liq_imb_fut_struct100_900s", kind="col"), Dep(name="liq_imb_spot_struct100_900s", kind="col"),),
        feature_id=2155,
    ),
    FeatureSpec(
        name="liq_imb_div_fut_minus_spot_struct50_300s",
        stage="S2",
        operator="derived.sub",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Cross-Market",
        description="Difference: col_a - col_b.",
        depends_on=(Dep(name="liq_imb_fut_struct50_300s", kind="col"), Dep(name="liq_imb_spot_struct50_300s", kind="col"),),
        feature_id=2156,
    ),
    FeatureSpec(
        name="liq_imb_div_fut_minus_spot_struct50_60s",
        stage="S2",
        operator="derived.sub",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Cross-Market",
        description="Difference: col_a - col_b.",
        depends_on=(Dep(name="liq_imb_fut_struct50_60s", kind="col"), Dep(name="liq_imb_spot_struct50_60s", kind="col"),),
        feature_id=2157,
    ),
    FeatureSpec(
        name="liq_imb_div_fut_minus_spot_struct50_900s",
        stage="S2",
        operator="derived.sub",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Cross-Market",
        description="Difference: col_a - col_b.",
        depends_on=(Dep(name="liq_imb_fut_struct50_900s", kind="col"), Dep(name="liq_imb_spot_struct50_900s", kind="col"),),
        feature_id=2158,
    ),

    # =========================================================================
    # GAP-FILL: Spread Cross-Market Ratio
    # spread_sf_div = spread_fut / spread_spot — direct liquidity cost divergence.
    # 1s raw ratio + 60s/300s smoothed. Detects sustained spread regime splits.
    # =========================================================================
    FeatureSpec(
        name="spread_sf_div_1s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Cross', 'eps': '1e-12'},
        group="Cross-Market",
        description="Spread ratio fut/spot: spread_fut_1s / (spread_spot_1s + eps). >1 = wider fut spread.",
        depends_on=(Dep(name="spread_fut_1s", kind="col"), Dep(name="spread_spot_1s", kind="col"),),
        feature_id=2159,
    ),
    FeatureSpec(
        name="spread_sf_div_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Cross', 'window_s': 60, 'resample': '1s'},
        group="Cross-Market",
        description="60s rolling mean of spread_sf_div_1s.",
        depends_on=(Dep(name="spread_sf_div_1s", kind="col"),),
        feature_id=2160,
    ),
    FeatureSpec(
        name="spread_sf_div_300s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Cross', 'window_s': 300, 'resample': '1s'},
        group="Cross-Market",
        description="300s rolling mean of spread_sf_div_1s.",
        depends_on=(Dep(name="spread_sf_div_1s", kind="col"),),
        feature_id=2161,
    ),

    # =========================================================================
    # GAP-FILL: Trade Size Cross-Market Ratio
    # trade_size_sf_ratio = avg_trade_size_fut / avg_trade_size_spot.
    # Detects whether institutional clip sizes are systematically larger in one market.
    # =========================================================================
    FeatureSpec(
        name="trade_size_sf_ratio_60s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Cross', 'eps': '1e-12'},
        group="Cross-Market",
        description="Trade size ratio fut/spot: avg_trade_size_fut_60s / (avg_trade_size_spot_60s + eps).",
        depends_on=(Dep(name="avg_trade_size_fut_60s", kind="col"), Dep(name="avg_trade_size_spot_60s", kind="col"),),
        feature_id=2162,
    ),
    FeatureSpec(
        name="trade_size_sf_ratio_300s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Cross', 'eps': '1e-12'},
        group="Cross-Market",
        description="Trade size ratio fut/spot: avg_trade_size_fut_300s / (avg_trade_size_spot_300s + eps).",
        depends_on=(Dep(name="avg_trade_size_fut_300s", kind="col"), Dep(name="avg_trade_size_spot_300s", kind="col"),),
        feature_id=2163,
    ),
]