# etl/spec/s2/s2_impact.py
# ==============================================================================
# S2 Feature Specs: Impact
#
# Binance-only pipeline | Source: S1 features (+ some S0 columns)
# 26 features | Feature IDs: 917–942
# ==============================================================================

from typing import List
from etl.spec import FeatureSpec, Dep

S2_IMPACT_FEATURES: List[FeatureSpec] = [

    # === derived.impact_per_liquidity ===
    FeatureSpec(
        name="impact_per_liquidity_fut_2bps_300s",
        stage="S2",
        operator="derived.impact_per_liquidity",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Impact",
        description="|ret| * volume / depth. Market impact per unit liquidity.",
        depends_on=(Dep(name="depth_notional_ask_2bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_2bps_fut_1s", kind="col"), Dep(name="ret_mid_fut_1s", kind="col"), Dep(name="volume_fut_1s", kind="col"),),
        feature_id=2441,
    ),
    FeatureSpec(
        name="impact_per_liquidity_fut_2bps_60s",
        stage="S2",
        operator="derived.impact_per_liquidity",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Impact",
        description="|ret| * volume / depth. Market impact per unit liquidity.",
        depends_on=(Dep(name="depth_notional_ask_2bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_2bps_fut_1s", kind="col"), Dep(name="ret_mid_fut_1s", kind="col"), Dep(name="volume_fut_1s", kind="col"),),
        feature_id=2442,
    ),
    FeatureSpec(
        name="impact_per_liquidity_fut_2bps_900s",
        stage="S2",
        operator="derived.impact_per_liquidity",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Impact",
        description="|ret| * volume / depth. Market impact per unit liquidity.",
        depends_on=(Dep(name="depth_notional_ask_2bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_2bps_fut_1s", kind="col"), Dep(name="ret_mid_fut_1s", kind="col"), Dep(name="volume_fut_1s", kind="col"),),
        feature_id=2443,
    ),
    FeatureSpec(
        name="impact_per_liquidity_fut_5bps_300s",
        stage="S2",
        operator="derived.impact_per_liquidity",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Impact",
        description="|ret| * volume / depth. Market impact per unit liquidity.",
        depends_on=(Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"), Dep(name="ret_mid_fut_1s", kind="col"), Dep(name="volume_fut_1s", kind="col"),),
        feature_id=2444,
    ),
    FeatureSpec(
        name="impact_per_liquidity_fut_5bps_60s",
        stage="S2",
        operator="derived.impact_per_liquidity",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Impact",
        description="|ret| * volume / depth. Market impact per unit liquidity.",
        depends_on=(Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"), Dep(name="ret_mid_fut_1s", kind="col"), Dep(name="volume_fut_1s", kind="col"),),
        feature_id=2445,
    ),
    FeatureSpec(
        name="impact_per_liquidity_fut_5bps_900s",
        stage="S2",
        operator="derived.impact_per_liquidity",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Impact",
        description="|ret| * volume / depth. Market impact per unit liquidity.",
        depends_on=(Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"), Dep(name="ret_mid_fut_1s", kind="col"), Dep(name="volume_fut_1s", kind="col"),),
        feature_id=2446,
    ),
    FeatureSpec(
        name="impact_per_liquidity_spot_2bps_300s",
        stage="S2",
        operator="derived.impact_per_liquidity",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Impact",
        description="|ret| * volume / depth. Market impact per unit liquidity.",
        depends_on=(Dep(name="depth_notional_ask_2bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_2bps_spot_1s", kind="col"), Dep(name="ret_mid_spot_1s", kind="col"), Dep(name="volume_spot_1s", kind="col"),),
        feature_id=2447,
    ),
    FeatureSpec(
        name="impact_per_liquidity_spot_2bps_60s",
        stage="S2",
        operator="derived.impact_per_liquidity",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Impact",
        description="|ret| * volume / depth. Market impact per unit liquidity.",
        depends_on=(Dep(name="depth_notional_ask_2bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_2bps_spot_1s", kind="col"), Dep(name="ret_mid_spot_1s", kind="col"), Dep(name="volume_spot_1s", kind="col"),),
        feature_id=2448,
    ),
    FeatureSpec(
        name="impact_per_liquidity_spot_2bps_900s",
        stage="S2",
        operator="derived.impact_per_liquidity",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Impact",
        description="|ret| * volume / depth. Market impact per unit liquidity.",
        depends_on=(Dep(name="depth_notional_ask_2bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_2bps_spot_1s", kind="col"), Dep(name="ret_mid_spot_1s", kind="col"), Dep(name="volume_spot_1s", kind="col"),),
        feature_id=2449,
    ),
    FeatureSpec(
        name="impact_per_liquidity_spot_5bps_300s",
        stage="S2",
        operator="derived.impact_per_liquidity",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Impact",
        description="|ret| * volume / depth. Market impact per unit liquidity.",
        depends_on=(Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"), Dep(name="ret_mid_spot_1s", kind="col"), Dep(name="volume_spot_1s", kind="col"),),
        feature_id=2450,
    ),
    FeatureSpec(
        name="impact_per_liquidity_spot_5bps_60s",
        stage="S2",
        operator="derived.impact_per_liquidity",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Impact",
        description="|ret| * volume / depth. Market impact per unit liquidity.",
        depends_on=(Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"), Dep(name="ret_mid_spot_1s", kind="col"), Dep(name="volume_spot_1s", kind="col"),),
        feature_id=2451,
    ),
    FeatureSpec(
        name="impact_per_liquidity_spot_5bps_900s",
        stage="S2",
        operator="derived.impact_per_liquidity",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Impact",
        description="|ret| * volume / depth. Market impact per unit liquidity.",
        depends_on=(Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"), Dep(name="ret_mid_spot_1s", kind="col"), Dep(name="volume_spot_1s", kind="col"),),
        feature_id=2452,
    ),

    # === derived.impact_per_signed ===
   FeatureSpec(
        name="impact_per_signed_fut_15s",
        stage="S2",
        operator="derived.impact_per_signed",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Impact",
        description="ret / signed_volume. Signed market impact coefficient.",
        depends_on=(
            Dep(name="ret_mid_fut_1s", kind="col"),
            Dep(name="signed_vol_fut_1s", kind="col"),
        ),
        feature_id=2453,
    ),
    FeatureSpec(
        name="impact_per_signed_fut_5s",
        stage="S2",
        operator="derived.impact_per_signed",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Impact",
        description="ret / signed_volume. Signed market impact coefficient.",
        depends_on=(Dep(name="ret_mid_fut_1s", kind="col"), Dep(name="signed_vol_fut_1s", kind="col"),),
        feature_id=2454,
    ),
    FeatureSpec(
        name="impact_per_signed_fut_60s",
        stage="S2",
        operator="derived.impact_per_signed",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Impact",
        description="ret / signed_volume. Signed market impact coefficient.",
        depends_on=(Dep(name="ret_mid_fut_1s", kind="col"), Dep(name="signed_vol_fut_1s", kind="col"),),
        feature_id=2455,
    ),
    FeatureSpec(
        name="impact_per_signed_fut_900s",
        stage="S2",
        operator="derived.impact_per_signed",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Impact",
        description="ret / signed_volume. Signed market impact coefficient.",
        depends_on=(Dep(name="ret_mid_fut_1s", kind="col"), Dep(name="signed_vol_fut_1s", kind="col"),),
        feature_id=2456,
    ),
    FeatureSpec(
        name="impact_per_signed_spot_15s",
        stage="S2",
        operator="derived.impact_per_signed",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Impact",
        description="ret / signed_volume. Signed market impact coefficient.",
        depends_on=(
            Dep(name="ret_mid_spot_1s", kind="col"),
            Dep(name="signed_vol_spot_1s", kind="col"),
        ),
        feature_id=2457,
    ),
    FeatureSpec(
        name="impact_per_signed_spot_5s",
        stage="S2",
        operator="derived.impact_per_signed",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Impact",
        description="ret / signed_volume. Signed market impact coefficient.",
        depends_on=(Dep(name="ret_mid_spot_1s", kind="col"), Dep(name="signed_vol_spot_1s", kind="col"),),
        feature_id=2458,
    ),
    FeatureSpec(
        name="impact_per_signed_spot_60s",
        stage="S2",
        operator="derived.impact_per_signed",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Impact",
        description="ret / signed_volume. Signed market impact coefficient.",
        depends_on=(Dep(name="ret_mid_spot_1s", kind="col"), Dep(name="signed_vol_spot_1s", kind="col"),),
        feature_id=2459,
    ),
    FeatureSpec(
        name="impact_per_signed_spot_900s",
        stage="S2",
        operator="derived.impact_per_signed",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Impact",
        description="ret / signed_volume. Signed market impact coefficient.",
        depends_on=(Dep(name="ret_mid_spot_1s", kind="col"), Dep(name="signed_vol_spot_1s", kind="col"),),
        feature_id=2460,
    ),
]