# etl/spec/s2/s2_liquidity_events.py
# ==============================================================================
# S2 Feature Specs: Liquidity Events
#
# Binance-only pipeline | Source: S1 features (+ some S0 columns)
# 40 features | Feature IDs: 943–982
#
# ==============================================================================

from typing import List
from etl.spec import FeatureSpec, Dep


S2_LIQUIDITY_EVENTS_FEATURES: List[FeatureSpec] = [

    # === derived.ratio ===
    FeatureSpec(
        name="refill_vs_pull_fut_1bps_15s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="add_rate_ask_fut_1bps_1s", kind="col"), Dep(name="add_rate_bid_fut_1bps_1s", kind="col"), Dep(name="cancel_rate_ask_fut_1bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_1bps_1s", kind="col"),),
        feature_id=2461,
    ),
    FeatureSpec(
        name="refill_vs_pull_fut_1bps_5s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="add_rate_ask_fut_1bps_1s", kind="col"), Dep(name="add_rate_bid_fut_1bps_1s", kind="col"), Dep(name="cancel_rate_ask_fut_1bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_1bps_1s", kind="col"),),
        feature_id=2462,
    ),
    FeatureSpec(
        name="refill_vs_pull_fut_2bps_5s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="add_rate_ask_fut_2bps_1s", kind="col"), Dep(name="add_rate_bid_fut_2bps_1s", kind="col"), Dep(name="cancel_rate_ask_fut_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_2bps_1s", kind="col"),),
        feature_id=2463,
    ),
    FeatureSpec(
        name="refill_vs_pull_fut_2bps_60s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="add_rate_ask_fut_2bps_1s", kind="col"), Dep(name="add_rate_bid_fut_2bps_1s", kind="col"), Dep(name="cancel_rate_ask_fut_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_2bps_1s", kind="col"),),
        feature_id=2464,
    ),
    FeatureSpec(
        name="refill_vs_pull_spot_1bps_15s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="add_rate_ask_spot_1bps_1s", kind="col"), Dep(name="add_rate_bid_spot_1bps_1s", kind="col"), Dep(name="cancel_rate_ask_spot_1bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_1bps_1s", kind="col"),),
        feature_id=2465,
    ),
    FeatureSpec(
        name="refill_vs_pull_spot_1bps_5s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="add_rate_ask_spot_1bps_1s", kind="col"), Dep(name="add_rate_bid_spot_1bps_1s", kind="col"), Dep(name="cancel_rate_ask_spot_1bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_1bps_1s", kind="col"),),
        feature_id=2466,
    ),
    FeatureSpec(
        name="refill_vs_pull_spot_2bps_5s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="add_rate_ask_spot_2bps_1s", kind="col"), Dep(name="add_rate_bid_spot_2bps_1s", kind="col"), Dep(name="cancel_rate_ask_spot_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_2bps_1s", kind="col"),),
        feature_id=2467,
    ),
    FeatureSpec(
        name="refill_vs_pull_spot_2bps_60s",
        stage="S2",
        operator="derived.ratio",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="add_rate_ask_spot_2bps_1s", kind="col"), Dep(name="add_rate_bid_spot_2bps_1s", kind="col"), Dep(name="cancel_rate_ask_spot_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_2bps_1s", kind="col"),),
        feature_id=2468,
    ),

    # === derived.roll_mean ===
    FeatureSpec(
        name="ask_churn_fut_2bps_15s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Rolling mean over window.",
        depends_on=(Dep(name="add_rate_ask_fut_2bps_1s", kind="col"), Dep(name="cancel_rate_ask_fut_2bps_1s", kind="col"),),
        feature_id=2469,
    ),
    FeatureSpec(
        name="ask_churn_fut_2bps_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Rolling mean over window.",
        depends_on=(Dep(name="add_rate_ask_fut_2bps_1s", kind="col"), Dep(name="cancel_rate_ask_fut_2bps_1s", kind="col"),),
        feature_id=2470,
    ),
    FeatureSpec(
        name="ask_churn_spot_2bps_15s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Rolling mean over window.",
        depends_on=(Dep(name="add_rate_ask_spot_2bps_1s", kind="col"), Dep(name="cancel_rate_ask_spot_2bps_1s", kind="col"),),
        feature_id=2471,
    ),
    FeatureSpec(
        name="ask_churn_spot_2bps_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Rolling mean over window.",
        depends_on=(Dep(name="add_rate_ask_spot_2bps_1s", kind="col"), Dep(name="cancel_rate_ask_spot_2bps_1s", kind="col"),),
        feature_id=2472,
    ),
    FeatureSpec(
        name="bid_churn_fut_2bps_15s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Rolling mean over window.",
        depends_on=(Dep(name="add_rate_bid_fut_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_2bps_1s", kind="col"),),
        feature_id=2473,
    ),
    FeatureSpec(
        name="bid_churn_fut_2bps_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Rolling mean over window.",
        depends_on=(Dep(name="add_rate_bid_fut_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_2bps_1s", kind="col"),),
        feature_id=2474,
    ),
    FeatureSpec(
        name="bid_churn_spot_2bps_15s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Rolling mean over window.",
        depends_on=(Dep(name="add_rate_bid_spot_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_2bps_1s", kind="col"),),
        feature_id=2475,
    ),
    FeatureSpec(
        name="bid_churn_spot_2bps_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Rolling mean over window.",
        depends_on=(Dep(name="add_rate_bid_spot_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_2bps_1s", kind="col"),),
        feature_id=2476,
    ),

    # === l2.cancel_rate_ahead ===
    FeatureSpec(
        name="cancel_rate_ahead_fut_1bps_15s",
        stage="S2",
        operator="l2.cancel_rate_ahead",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Cancel rate on the side ahead of the trade direction.",
        depends_on=(Dep(name="cancel_rate_ask_fut_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_fut_1s", kind="col"),),
        feature_id=2477,
    ),
    FeatureSpec(
        name="cancel_rate_ahead_spot_1bps_15s",
        stage="S2",
        operator="l2.cancel_rate_ahead",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Cancel rate on the side ahead of the trade direction.",
        depends_on=(Dep(name="cancel_rate_ask_spot_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_spot_1s", kind="col"),),
        feature_id=2478,
    ),

    # === l2.cancel_rate_behind ===
    FeatureSpec(
        name="cancel_rate_behind_fut_1bps_15s",
        stage="S2",
        operator="l2.cancel_rate_behind",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Cancel rate on the side behind the trade direction.",
        depends_on=(Dep(name="cancel_rate_bid_fut_1bps_1s", kind="col"), Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"),),
        feature_id=2479,
    ),
    FeatureSpec(
        name="cancel_rate_behind_spot_1bps_15s",
        stage="S2",
        operator="l2.cancel_rate_behind",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Cancel rate on the side behind the trade direction.",
        depends_on=(Dep(name="cancel_rate_bid_spot_1bps_1s", kind="col"), Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"),),
        feature_id=2480,
    ),

    # === l2.churn_ask ===
    FeatureSpec(
        name="ask_churn_fut_5bps_1s",
        stage="S2",
        operator="l2.churn_ask",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Liquidity Events",
        description="Ask-side churn: (add_rate + cancel_rate) / depth. Turnover intensity.",
        depends_on=(Dep(name="add_rate_ask_fut_5bps_1s", kind="col"), Dep(name="cancel_rate_ask_fut_5bps_1s", kind="col"), Dep(name="depth_notional_ask_5bps_fut_1s", kind="col"),),
        feature_id=2481,
    ),
    FeatureSpec(
        name="ask_churn_spot_5bps_1s",
        stage="S2",
        operator="l2.churn_ask",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Liquidity Events",
        description="Ask-side churn: (add_rate + cancel_rate) / depth. Turnover intensity.",
        depends_on=(Dep(name="add_rate_ask_spot_5bps_1s", kind="col"), Dep(name="cancel_rate_ask_spot_5bps_1s", kind="col"), Dep(name="depth_notional_ask_5bps_spot_1s", kind="col"),),
        feature_id=2482,
    ),

    # === l2.churn_bid ===
    FeatureSpec(
        name="bid_churn_fut_5bps_1s",
        stage="S2",
        operator="l2.churn_bid",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Liquidity Events",
        description="Bid-side churn: (add_rate + cancel_rate) / depth. Turnover intensity.",
        depends_on=(Dep(name="add_rate_bid_fut_5bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_5bps_1s", kind="col"), Dep(name="depth_notional_bid_5bps_fut_1s", kind="col"),),
        feature_id=2483,
    ),
    FeatureSpec(
        name="bid_churn_spot_5bps_1s",
        stage="S2",
        operator="l2.churn_bid",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Liquidity Events",
        description="Bid-side churn: (add_rate + cancel_rate) / depth. Turnover intensity.",
        depends_on=(Dep(name="add_rate_bid_spot_5bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_5bps_1s", kind="col"), Dep(name="depth_notional_bid_5bps_spot_1s", kind="col"),),
        feature_id=2484,
    ),

    # === l2.pull_rate ===
    # Before: only [cancel_ask, cancel_bid] → engine computed cancel_ask/cancel_bid.
    # After:  [cancel_ask, cancel_bid, depth_ask, depth_bid] → (cancel_ask+cancel_bid)/(depth_ask+depth_bid).
    FeatureSpec(
        name="pull_rate_fut_1bps_15s",
        stage="S2",
        operator="l2.pull_rate",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: (cancel_ask + cancel_bid) / (depth_ask + depth_bid).",
        depends_on=(Dep(name="cancel_rate_ask_fut_1bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"),),
        feature_id=2485,
    ),
    FeatureSpec(
        name="pull_rate_fut_2bps_15s",
        stage="S2",
        operator="l2.pull_rate",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: (cancel_ask + cancel_bid) / (depth_ask + depth_bid).",
        depends_on=(Dep(name="cancel_rate_ask_fut_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_2bps_1s", kind="col"), Dep(name="depth_notional_ask_2bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_2bps_fut_1s", kind="col"),),
        feature_id=2486,
    ),
    FeatureSpec(
        name="pull_rate_fut_2bps_60s",
        stage="S2",
        operator="l2.pull_rate",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: (cancel_ask + cancel_bid) / (depth_ask + depth_bid).",
        depends_on=(Dep(name="cancel_rate_ask_fut_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_2bps_1s", kind="col"), Dep(name="depth_notional_ask_2bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_2bps_fut_1s", kind="col"),),
        feature_id=2487,
    ),
    FeatureSpec(
        name="pull_rate_spot_1bps_15s",
        stage="S2",
        operator="l2.pull_rate",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: (cancel_ask + cancel_bid) / (depth_ask + depth_bid).",
        depends_on=(Dep(name="cancel_rate_ask_spot_1bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"),),
        feature_id=2488,
    ),
    FeatureSpec(
        name="pull_rate_spot_2bps_15s",
        stage="S2",
        operator="l2.pull_rate",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: (cancel_ask + cancel_bid) / (depth_ask + depth_bid).",
        depends_on=(Dep(name="cancel_rate_ask_spot_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_2bps_1s", kind="col"), Dep(name="depth_notional_ask_2bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_2bps_spot_1s", kind="col"),),
        feature_id=2489,
    ),
    FeatureSpec(
        name="pull_rate_spot_2bps_60s",
        stage="S2",
        operator="l2.pull_rate",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized cancel rate: (cancel_ask + cancel_bid) / (depth_ask + depth_bid).",
        depends_on=(Dep(name="cancel_rate_ask_spot_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_2bps_1s", kind="col"), Dep(name="depth_notional_ask_2bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_2bps_spot_1s", kind="col"),),
        feature_id=2490,
    ),

    # === l2.refill_rate ===
    # Before: only [add_ask, add_bid] → engine computed add_ask/add_bid.
    # After:  [add_ask, add_bid, depth_ask, depth_bid] → (add_ask+add_bid)/(depth_ask+depth_bid).
    FeatureSpec(
        name="refill_rate_fut_1bps_15s",
        stage="S2",
        operator="l2.refill_rate",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: (add_ask + add_bid) / (depth_ask + depth_bid).",
        depends_on=(Dep(name="add_rate_ask_fut_1bps_1s", kind="col"), Dep(name="add_rate_bid_fut_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"),),
        feature_id=2491,
    ),
    FeatureSpec(
        name="refill_rate_fut_1bps_5s",
        stage="S2",
        operator="l2.refill_rate",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: (add_ask + add_bid) / (depth_ask + depth_bid).",
        depends_on=(Dep(name="add_rate_ask_fut_1bps_1s", kind="col"), Dep(name="add_rate_bid_fut_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"),),
        feature_id=2492,
    ),
    FeatureSpec(
        name="refill_rate_fut_2bps_15s",
        stage="S2",
        operator="l2.refill_rate",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: (add_ask + add_bid) / (depth_ask + depth_bid).",
        depends_on=(Dep(name="add_rate_ask_fut_2bps_1s", kind="col"), Dep(name="add_rate_bid_fut_2bps_1s", kind="col"), Dep(name="depth_notional_ask_2bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_2bps_fut_1s", kind="col"),),
        feature_id=2493,
    ),
    FeatureSpec(
        name="refill_rate_fut_2bps_60s",
        stage="S2",
        operator="l2.refill_rate",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: (add_ask + add_bid) / (depth_ask + depth_bid).",
        depends_on=(Dep(name="add_rate_ask_fut_2bps_1s", kind="col"), Dep(name="add_rate_bid_fut_2bps_1s", kind="col"), Dep(name="depth_notional_ask_2bps_fut_1s", kind="col"), Dep(name="depth_notional_bid_2bps_fut_1s", kind="col"),),
        feature_id=2494,
    ),
    FeatureSpec(
        name="refill_rate_spot_1bps_15s",
        stage="S2",
        operator="l2.refill_rate",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: (add_ask + add_bid) / (depth_ask + depth_bid).",
        depends_on=(Dep(name="add_rate_ask_spot_1bps_1s", kind="col"), Dep(name="add_rate_bid_spot_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"),),
        feature_id=2495,
    ),
    FeatureSpec(
        name="refill_rate_spot_1bps_5s",
        stage="S2",
        operator="l2.refill_rate",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: (add_ask + add_bid) / (depth_ask + depth_bid).",
        depends_on=(Dep(name="add_rate_ask_spot_1bps_1s", kind="col"), Dep(name="add_rate_bid_spot_1bps_1s", kind="col"), Dep(name="depth_notional_ask_1bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"),),
        feature_id=2496,
    ),
    FeatureSpec(
        name="refill_rate_spot_2bps_15s",
        stage="S2",
        operator="l2.refill_rate",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: (add_ask + add_bid) / (depth_ask + depth_bid).",
        depends_on=(Dep(name="add_rate_ask_spot_2bps_1s", kind="col"), Dep(name="add_rate_bid_spot_2bps_1s", kind="col"), Dep(name="depth_notional_ask_2bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_2bps_spot_1s", kind="col"),),
        feature_id=2497,
    ),
    FeatureSpec(
        name="refill_rate_spot_2bps_60s",
        stage="S2",
        operator="l2.refill_rate",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Liquidity Events",
        description="Normalized add rate: (add_ask + add_bid) / (depth_ask + depth_bid).",
        depends_on=(Dep(name="add_rate_ask_spot_2bps_1s", kind="col"), Dep(name="add_rate_bid_spot_2bps_1s", kind="col"), Dep(name="depth_notional_ask_2bps_spot_1s", kind="col"), Dep(name="depth_notional_bid_2bps_spot_1s", kind="col"),),
        feature_id=2498,
    ),

    # === l2.refill_rate_behind ===
    FeatureSpec(
        name="refill_rate_behind_fut_1bps_15s",
        stage="S2",
        operator="l2.refill_rate_behind",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Refill rate on the side behind the trade direction.",
        depends_on=(Dep(name="add_rate_bid_fut_1bps_1s", kind="col"), Dep(name="depth_notional_bid_1bps_fut_1s", kind="col"),),
        feature_id=2499,
    ),
    FeatureSpec(
        name="refill_rate_behind_spot_1bps_15s",
        stage="S2",
        operator="l2.refill_rate_behind",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Liquidity Events",
        description="Refill rate on the side behind the trade direction.",
        depends_on=(Dep(name="add_rate_bid_spot_1bps_1s", kind="col"), Dep(name="depth_notional_bid_1bps_spot_1s", kind="col"),),
        feature_id=2500,
    ),
]