# etl/spec/s2/s2_normalization.py
# ==============================================================================
# S2 Feature Specs: Normalization
#
# Binance-only pipeline | Source: S1 features (+ some S0 columns)
# 72 features | Feature IDs: 999–1075
#
# ==============================================================================

from typing import List
from etl.spec import FeatureSpec, Dep


S2_NORMALIZATION_FEATURES: List[FeatureSpec] = [

    # === derived.robust_zscore ===
    FeatureSpec(
        name="z_basis_300s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'window_s': 300, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="basis_300s", kind="col"),),
        feature_id=2517,
    ),
    FeatureSpec(
        name="z_basis_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="basis_60s", kind="col"),),
        feature_id=2518,
    ),
    FeatureSpec(
        name="z_book_asymmetry_fut_struct100_1s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="book_asymmetry_fut_struct100_1s", kind="col"),),
        feature_id=2519,
    ),
    FeatureSpec(
        name="z_book_asymmetry_fut_struct50_1s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="book_asymmetry_fut_struct50_1s", kind="col"),),
        feature_id=2520,
    ),
    FeatureSpec(
        name="z_book_asymmetry_spot_struct100_1s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="book_asymmetry_spot_struct100_1s", kind="col"),),
        feature_id=2521,
    ),
    FeatureSpec(
        name="z_book_asymmetry_spot_struct50_1s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="book_asymmetry_spot_struct50_1s", kind="col"),),
        feature_id=2522,
    ),
    FeatureSpec(
        name="z_liq_imb_fut_struct100_300s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="liq_imb_fut_struct100_300s", kind="col"),),
        feature_id=2523,
    ),
    FeatureSpec(
        name="z_liq_imb_fut_struct100_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="liq_imb_fut_struct100_60s", kind="col"),),
        feature_id=2524,
    ),
    FeatureSpec(
        name="z_liq_imb_fut_struct100_900s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="liq_imb_fut_struct100_900s", kind="col"),),
        feature_id=2525,
    ),
    FeatureSpec(
        name="z_liq_imb_fut_struct50_300s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="liq_imb_fut_struct50_300s", kind="col"),),
        feature_id=2526,
    ),
    FeatureSpec(
        name="z_liq_imb_fut_struct50_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="liq_imb_fut_struct50_60s", kind="col"),),
        feature_id=2527,
    ),
    FeatureSpec(
        name="z_liq_imb_fut_struct50_900s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 900, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="liq_imb_fut_struct50_900s", kind="col"),),
        feature_id=2528,
    ),
    FeatureSpec(
        name="z_liq_imb_spot_struct100_300s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="liq_imb_spot_struct100_300s", kind="col"),),
        feature_id=2529,
    ),
    FeatureSpec(
        name="z_liq_imb_spot_struct100_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="liq_imb_spot_struct100_60s", kind="col"),),
        feature_id=2530,
    ),
    FeatureSpec(
        name="z_liq_imb_spot_struct100_900s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="liq_imb_spot_struct100_900s", kind="col"),),
        feature_id=2531,
    ),
    FeatureSpec(
        name="z_liq_imb_spot_struct50_300s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="liq_imb_spot_struct50_300s", kind="col"),),
        feature_id=2532,
    ),
    FeatureSpec(
        name="z_liq_imb_spot_struct50_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="liq_imb_spot_struct50_60s", kind="col"),),
        feature_id=2533,
    ),
    FeatureSpec(
        name="z_liq_imb_spot_struct50_900s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="liq_imb_spot_struct50_900s", kind="col"),),
        feature_id=2534,
    ),
    FeatureSpec(
        name="z_participation_rate_300s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Cross', 'window_s': 300, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="participation_rate_fut_1s", kind="col"), Dep(name="participation_rate_spot_1s", kind="col"),),
        feature_id=2535,
    ),
    FeatureSpec(
        name="z_participation_rate_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Cross', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="participation_rate_fut_1s", kind="col"), Dep(name="participation_rate_spot_1s", kind="col"),),
        feature_id=2536,
    ),
    FeatureSpec(
        name="z_participation_rate_900s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Cross', 'window_s': 900, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="participation_rate_fut_1s", kind="col"), Dep(name="participation_rate_spot_1s", kind="col"),),
        feature_id=2537,
    ),
    FeatureSpec(
        name="z_pull_rate_fut_10bps_15s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_fut_10bps_15s", kind="col"),),
        feature_id=2538,
    ),
    FeatureSpec(
        name="z_pull_rate_fut_10bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_fut_10bps_5s", kind="col"),),
        feature_id=2539,
    ),
    FeatureSpec(
        name="z_pull_rate_fut_10bps_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_fut_10bps_60s", kind="col"),),
        feature_id=2540,
    ),
    FeatureSpec(
        name="z_pull_rate_fut_1bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_fut_1bps_5s", kind="col"),),
        feature_id=2541,
    ),
    FeatureSpec(
        name="z_pull_rate_fut_1bps_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_fut_1bps_60s", kind="col"),),
        feature_id=2542,
    ),
    FeatureSpec(
        name="z_pull_rate_fut_2bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_fut_2bps_5s", kind="col"),),
        feature_id=2543,
    ),
    FeatureSpec(
        name="z_pull_rate_fut_5bps_15s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_fut_5bps_15s", kind="col"),),
        feature_id=2544,
    ),
    FeatureSpec(
        name="z_pull_rate_fut_5bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_fut_5bps_5s", kind="col"),),
        feature_id=2545,
    ),
    FeatureSpec(
        name="z_pull_rate_fut_5bps_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_fut_5bps_60s", kind="col"),),
        feature_id=2546,
    ),
    FeatureSpec(
        name="z_pull_rate_spot_10bps_15s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_spot_10bps_15s", kind="col"),),
        feature_id=2547,
    ),
    FeatureSpec(
        name="z_pull_rate_spot_10bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_spot_10bps_5s", kind="col"),),
        feature_id=2548,
    ),
    FeatureSpec(
        name="z_pull_rate_spot_10bps_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_spot_10bps_60s", kind="col"),),
        feature_id=2549,
    ),
    FeatureSpec(
        name="z_pull_rate_spot_1bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_spot_1bps_5s", kind="col"),),
        feature_id=2550,
    ),
    FeatureSpec(
        name="z_pull_rate_spot_1bps_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_spot_1bps_60s", kind="col"),),
        feature_id=2551,
    ),
    FeatureSpec(
        name="z_pull_rate_spot_2bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_spot_2bps_5s", kind="col"),),
        feature_id=2552,
    ),
    FeatureSpec(
        name="z_pull_rate_spot_5bps_15s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_spot_5bps_15s", kind="col"),),
        feature_id=2553,
    ),
    FeatureSpec(
        name="z_pull_rate_spot_5bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_spot_5bps_5s", kind="col"),),
        feature_id=2554,
    ),
    FeatureSpec(
        name="z_pull_rate_spot_5bps_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="pull_rate_spot_5bps_60s", kind="col"),),
        feature_id=2555,
    ),
    FeatureSpec(
        name="z_queue_pressure_fut_1bps_1s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="queue_pressure_fut_1bps_1s", kind="col"),),
        feature_id=2556,
    ),
    FeatureSpec(
        name="z_queue_pressure_fut_1bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="queue_pressure_fut_1bps_5s", kind="col"),),
        feature_id=2557,
    ),
    FeatureSpec(
        name="z_queue_pressure_fut_2bps_1s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="queue_pressure_fut_2bps_1s", kind="col"),),
        feature_id=2558,
    ),
    FeatureSpec(
        name="z_queue_pressure_fut_2bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="queue_pressure_fut_2bps_5s", kind="col"),),
        feature_id=2559,
    ),
    FeatureSpec(
        name="z_queue_pressure_fut_5bps_1s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="queue_pressure_fut_5bps_1s", kind="col"),),
        feature_id=2560,
    ),
    FeatureSpec(
        name="z_queue_pressure_fut_5bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="queue_pressure_fut_5bps_5s", kind="col"),),
        feature_id=2561,
    ),
    FeatureSpec(
        name="z_queue_pressure_spot_1bps_1s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="queue_pressure_spot_1bps_1s", kind="col"),),
        feature_id=2562,
    ),
    FeatureSpec(
        name="z_queue_pressure_spot_1bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="queue_pressure_spot_1bps_5s", kind="col"),),
        feature_id=2563,
    ),
    FeatureSpec(
        name="z_queue_pressure_spot_2bps_1s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="queue_pressure_spot_2bps_1s", kind="col"),),
        feature_id=2564,
    ),
    FeatureSpec(
        name="z_queue_pressure_spot_2bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="queue_pressure_spot_2bps_5s", kind="col"),),
        feature_id=2565,
    ),
    FeatureSpec(
        name="z_queue_pressure_spot_5bps_1s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="queue_pressure_spot_5bps_1s", kind="col"),),
        feature_id=2566,
    ),
    FeatureSpec(
        name="z_queue_pressure_spot_5bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="queue_pressure_spot_5bps_5s", kind="col"),),
        feature_id=2567,
    ),
    FeatureSpec(
        name="z_refill_rate_fut_10bps_15s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="refill_rate_fut_10bps_15s", kind="col"),),
        feature_id=2568,
    ),
    FeatureSpec(
        name="z_refill_rate_fut_10bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="refill_rate_fut_10bps_5s", kind="col"),),
        feature_id=2569,
    ),
    FeatureSpec(
        name="z_refill_rate_fut_10bps_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="refill_rate_fut_10bps_60s", kind="col"),),
        feature_id=2570,
    ),
    FeatureSpec(
        name="z_refill_rate_fut_1bps_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="refill_rate_fut_1bps_60s", kind="col"),),
        feature_id=2571,
    ),
    FeatureSpec(
        name="z_refill_rate_fut_2bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="refill_rate_fut_2bps_5s", kind="col"),),
        feature_id=2572,
    ),
    FeatureSpec(
        name="z_refill_rate_fut_5bps_15s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="refill_rate_fut_5bps_15s", kind="col"),),
        feature_id=2573,
    ),
    FeatureSpec(
        name="z_refill_rate_fut_5bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="refill_rate_fut_5bps_5s", kind="col"),),
        feature_id=2574,
    ),
    FeatureSpec(
        name="z_refill_rate_fut_5bps_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="refill_rate_fut_5bps_60s", kind="col"),),
        feature_id=2575,
    ),
    FeatureSpec(
        name="z_refill_rate_spot_10bps_15s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="refill_rate_spot_10bps_15s", kind="col"),),
        feature_id=2576,
    ),
    FeatureSpec(
        name="z_refill_rate_spot_10bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="refill_rate_spot_10bps_5s", kind="col"),),
        feature_id=2577,
    ),
    FeatureSpec(
        name="z_refill_rate_spot_10bps_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="refill_rate_spot_10bps_60s", kind="col"),),
        feature_id=2578,
    ),
    FeatureSpec(
        name="z_refill_rate_spot_1bps_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="refill_rate_spot_1bps_60s", kind="col"),),
        feature_id=2579,
    ),
    FeatureSpec(
        name="z_refill_rate_spot_2bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="refill_rate_spot_2bps_5s", kind="col"),),
        feature_id=2580,
    ),
    FeatureSpec(
        name="z_refill_rate_spot_5bps_15s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="refill_rate_spot_5bps_15s", kind="col"),),
        feature_id=2581,
    ),
    FeatureSpec(
        name="z_refill_rate_spot_5bps_5s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="refill_rate_spot_5bps_5s", kind="col"),),
        feature_id=2582,
    ),
    FeatureSpec(
        name="z_refill_rate_spot_5bps_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="refill_rate_spot_5bps_60s", kind="col"),),
        feature_id=2583,
    ),
    FeatureSpec(
        name="z_rv_300s",
        stage="S2",
        operator="derived.z_rv",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="ret_mid_spot_1s", kind="col"),),
        feature_id=2584,
    ),
    FeatureSpec(
        name="z_rv_60s",
        stage="S2",
        operator="derived.z_rv",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="ret_mid_spot_1s", kind="col"),),
        feature_id=2585,
    ),
    FeatureSpec(
        name="z_rv_900s",
        stage="S2",
        operator="derived.z_rv",
        params={'market_scope': 'Spot', 'window_s': 900, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="ret_mid_spot_1s", kind="col"),),
        feature_id=2586,
    ),
    FeatureSpec(
        name="z_taker_imbalance_fut_1s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="taker_imbalance_fut_1s", kind="col"),),
        feature_id=2587,
    ),
    FeatureSpec(
        name="z_taker_imbalance_spot_1s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score: (x - rolling_median) / rolling_mad.",
        depends_on=(Dep(name="taker_imbalance_spot_1s", kind="col"),),
        feature_id=2588,
    ),

    # =========================================================================
    # GAP-FILL: Spread Normalization
    # Spread is computed at S0 and rolled at S1 but never normalized.
    # z_spread captures whether current spread is anomalously wide/tight vs regime.
    # Note: _1s suffix = input signal timeframe, not zscore window (see FIX note above).
    # =========================================================================
    FeatureSpec(
        name="z_spread_fut_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score of spread_fut_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="spread_fut_60s", kind="col"),),
        feature_id=2589,
    ),
    FeatureSpec(
        name="z_spread_fut_300s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score of spread_fut_300s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="spread_fut_300s", kind="col"),),
        feature_id=2590,
    ),
    FeatureSpec(
        name="z_spread_spot_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score of spread_spot_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="spread_spot_60s", kind="col"),),
        feature_id=2591,
    ),
    FeatureSpec(
        name="z_spread_spot_300s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s'},
        group="Normalization",
        description="Robust z-score of spread_spot_300s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="spread_spot_300s", kind="col"),),
        feature_id=2592,
    ),

    # =========================================================================
    # GAP-FILL: Trade Size Normalization
    # avg_trade_size exists at S2 (rolled) but is never normalized.
    # z_avg_trade_size detects anomalously large/small clips vs rolling regime.
    #
    # min_periods=3 because the underlying avg_trade_size_*_1s is NaN in
    # ~5-6% of seconds (no trades in that second). With strict min_periods=
    # window_s the rolling zscore is 100% NaN downstream. min_periods=3
    # produces useful values from the available non-NaN samples.
    # =========================================================================
    FeatureSpec(
        name="z_avg_trade_size_fut_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s', 'min_periods': 3},
        group="Normalization",
        description="Robust z-score of avg_trade_size_fut_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="avg_trade_size_fut_60s", kind="col"),),
        feature_id=2593,
    ),
    FeatureSpec(
        name="z_avg_trade_size_fut_300s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Futures', 'window_s': 300, 'resample': '1s', 'min_periods': 3},
        group="Normalization",
        description="Robust z-score of avg_trade_size_fut_300s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="avg_trade_size_fut_300s", kind="col"),),
        feature_id=2594,
    ),
    FeatureSpec(
        name="z_avg_trade_size_spot_60s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s', 'min_periods': 3},
        group="Normalization",
        description="Robust z-score of avg_trade_size_spot_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="avg_trade_size_spot_60s", kind="col"),),
        feature_id=2595,
    ),
    FeatureSpec(
        name="z_avg_trade_size_spot_300s",
        stage="S2",
        operator="derived.robust_zscore",
        params={'market_scope': 'Spot', 'window_s': 300, 'resample': '1s', 'min_periods': 3},
        group="Normalization",
        description="Robust z-score of avg_trade_size_spot_300s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="avg_trade_size_spot_300s", kind="col"),),
        feature_id=2596,
    ),
]