# etl/spec/s2/s2_pressure.py
# ==============================================================================
# S2 Feature Specs: Pressure
#
# Binance-only pipeline | Source: S1 features (+ some S0 columns)
# 29 features | Feature IDs: 1076–1104
# ==============================================================================

from typing import List
from etl.spec import FeatureSpec, Dep


S2_PRESSURE_FEATURES: List[FeatureSpec] = [

    # === deriv.queue_pressure_log_div ===
    FeatureSpec(
        name="queue_pressure_log_div_1bps_1s",
        stage="S2",
        operator="deriv.queue_pressure_log_div",
        params={'market_scope': 'Cross', 'window_s': 1, 'resample': '1s'},
        group="Pressure",
        description="Log queue pressure divergence: log_qp_fut - log_qp_spot.",
        depends_on=(Dep(name="queue_pressure_log_fut_1bps_1s", kind="col"), Dep(name="queue_pressure_log_spot_1bps_1s", kind="col"),),
        feature_id=2597,
    ),
    FeatureSpec(
        name="queue_pressure_log_div_2bps_1s",
        stage="S2",
        operator="deriv.queue_pressure_log_div",
        params={'market_scope': 'Cross', 'window_s': 1, 'resample': '1s'},
        group="Pressure",
        description="Log queue pressure divergence: log_qp_fut - log_qp_spot.",
        depends_on=(Dep(name="queue_pressure_log_fut_2bps_1s", kind="col"), Dep(name="queue_pressure_log_spot_2bps_1s", kind="col"),),
        feature_id=2598,
    ),
    FeatureSpec(
        name="queue_pressure_log_div_5bps_1s",
        stage="S2",
        operator="deriv.queue_pressure_log_div",
        params={'market_scope': 'Cross', 'window_s': 1, 'resample': '1s'},
        group="Pressure",
        description="Log queue pressure divergence: log_qp_fut - log_qp_spot.",
        depends_on=(Dep(name="queue_pressure_log_fut_5bps_1s", kind="col"), Dep(name="queue_pressure_log_spot_5bps_1s", kind="col"),),
        feature_id=2599,
    ),

    # === derived.ratio ===
    FeatureSpec(
        name="queue_pressure_ratio_fut_1bps_15s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Pressure",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="queue_pressure_log_fut_1bps_1s", kind="col"),),
        feature_id=2600,
    ),
    FeatureSpec(
        name="queue_pressure_ratio_fut_1bps_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Pressure",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="queue_pressure_log_fut_1bps_1s", kind="col"),),
        feature_id=2601,
    ),
    FeatureSpec(
        name="queue_pressure_ratio_spot_1bps_15s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Pressure",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="queue_pressure_log_spot_1bps_1s", kind="col"),),
        feature_id=2602,
    ),
    FeatureSpec(
        name="queue_pressure_ratio_spot_1bps_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Pressure",
        description="Ratio: col_a / col_b (or col_a / (col_a + col_b) for share).",
        depends_on=(Dep(name="queue_pressure_log_spot_1bps_1s", kind="col"),),
        feature_id=2603,
    ),

    # === derived.roll_mean ===
    FeatureSpec(
        name="queue_imb_fut_1bps_15s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Pressure",
        description="Rolling mean over window.",
        depends_on=(Dep(name="queue_imb_fut_1bps_1s", kind="col"),),
        feature_id=2604,
    ),
    FeatureSpec(
        name="queue_imb_fut_1bps_5s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 5, 'resample': '1s'},
        group="Pressure",
        description="Rolling mean over window.",
        depends_on=(Dep(name="queue_imb_fut_1bps_1s", kind="col"),),
        feature_id=2605,
    ),
    FeatureSpec(
        name="queue_imb_fut_1bps_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Pressure",
        description="Rolling mean over window.",
        depends_on=(Dep(name="queue_imb_fut_1bps_1s", kind="col"),),
        feature_id=2606,
    ),
    FeatureSpec(
        name="queue_imb_spot_1bps_15s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Pressure",
        description="Rolling mean over window.",
        depends_on=(Dep(name="queue_imb_spot_1bps_1s", kind="col"),),
        feature_id=2607,
    ),
    FeatureSpec(
        name="queue_imb_spot_1bps_5s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 5, 'resample': '1s'},
        group="Pressure",
        description="Rolling mean over window.",
        depends_on=(Dep(name="queue_imb_spot_1bps_1s", kind="col"),),
        feature_id=2608,
    ),
    FeatureSpec(
        name="queue_imb_spot_1bps_60s",
        stage="S2",
        operator="derived.roll_mean",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Pressure",
        description="Rolling mean over window.",
        depends_on=(Dep(name="queue_imb_spot_1bps_1s", kind="col"),),
        feature_id=2609,
    ),

    # === derived.roll_sum ===
    FeatureSpec(
        name="queue_pressure_fut_1bps_15s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 15, 'resample': '1s'},
        group="Pressure",
        description="Rolling sum over window.",
        depends_on=(Dep(name="queue_pressure_log_fut_1bps_1s", kind="col"),),
        feature_id=2610,
    ),
    FeatureSpec(
        name="queue_pressure_fut_1bps_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Futures', 'window_s': 60, 'resample': '1s'},
        group="Pressure",
        description="Rolling sum over window.",
        depends_on=(Dep(name="queue_pressure_log_fut_1bps_1s", kind="col"),),
        feature_id=2611,
    ),
    FeatureSpec(
        name="queue_pressure_spot_1bps_15s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 15, 'resample': '1s'},
        group="Pressure",
        description="Rolling sum over window.",
        depends_on=(Dep(name="queue_pressure_log_spot_1bps_1s", kind="col"),),
        feature_id=2612,
    ),
    FeatureSpec(
        name="queue_pressure_spot_1bps_60s",
        stage="S2",
        operator="derived.roll_sum",
        params={'market_scope': 'Spot', 'window_s': 60, 'resample': '1s'},
        group="Pressure",
        description="Rolling sum over window.",
        depends_on=(Dep(name="queue_pressure_log_spot_1bps_1s", kind="col"),),
        feature_id=2613,
    ),

    # === l2.net_add_pressure ===
    FeatureSpec(
        name="net_add_pressure_fut_10bps_1s",
        stage="S2",
        operator="l2.net_add_pressure",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Pressure",
        description="(add_bid - cancel_bid) - (add_ask - cancel_ask). Net add-side pressure.",
        depends_on=(Dep(name="add_rate_ask_fut_10bps_1s", kind="col"), Dep(name="add_rate_bid_fut_10bps_1s", kind="col"), Dep(name="cancel_rate_ask_fut_10bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_10bps_1s", kind="col"),),
        feature_id=2614,
    ),
    FeatureSpec(
        name="net_add_pressure_fut_2bps_1s",
        stage="S2",
        operator="l2.net_add_pressure",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Pressure",
        description="(add_bid - cancel_bid) - (add_ask - cancel_ask). Net add-side pressure.",
        depends_on=(Dep(name="add_rate_ask_fut_2bps_1s", kind="col"), Dep(name="add_rate_bid_fut_2bps_1s", kind="col"), Dep(name="cancel_rate_ask_fut_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_2bps_1s", kind="col"),),
        feature_id=2615,
    ),
    FeatureSpec(
        name="net_add_pressure_fut_5bps_1s",
        stage="S2",
        operator="l2.net_add_pressure",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Pressure",
        description="(add_bid - cancel_bid) - (add_ask - cancel_ask). Net add-side pressure.",
        depends_on=(Dep(name="add_rate_ask_fut_5bps_1s", kind="col"), Dep(name="add_rate_bid_fut_5bps_1s", kind="col"), Dep(name="cancel_rate_ask_fut_5bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_5bps_1s", kind="col"),),
        feature_id=2616,
    ),
    FeatureSpec(
        name="net_add_pressure_spot_10bps_1s",
        stage="S2",
        operator="l2.net_add_pressure",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Pressure",
        description="(add_bid - cancel_bid) - (add_ask - cancel_ask). Net add-side pressure.",
        depends_on=(Dep(name="add_rate_ask_spot_10bps_1s", kind="col"), Dep(name="add_rate_bid_spot_10bps_1s", kind="col"), Dep(name="cancel_rate_ask_spot_10bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_10bps_1s", kind="col"),),
        feature_id=2617,
    ),
    FeatureSpec(
        name="net_add_pressure_spot_2bps_1s",
        stage="S2",
        operator="l2.net_add_pressure",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Pressure",
        description="(add_bid - cancel_bid) - (add_ask - cancel_ask). Net add-side pressure.",
        depends_on=(Dep(name="add_rate_ask_spot_2bps_1s", kind="col"), Dep(name="add_rate_bid_spot_2bps_1s", kind="col"), Dep(name="cancel_rate_ask_spot_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_2bps_1s", kind="col"),),
        feature_id=2618,
    ),
    FeatureSpec(
        name="net_add_pressure_spot_5bps_1s",
        stage="S2",
        operator="l2.net_add_pressure",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Pressure",
        description="(add_bid - cancel_bid) - (add_ask - cancel_ask). Net add-side pressure.",
        depends_on=(Dep(name="add_rate_ask_spot_5bps_1s", kind="col"), Dep(name="add_rate_bid_spot_5bps_1s", kind="col"), Dep(name="cancel_rate_ask_spot_5bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_5bps_1s", kind="col"),),
        feature_id=2619,
    ),

    # === l2.net_cancel_pressure ===
    FeatureSpec(
        name="net_cancel_pressure_fut_10bps_1s",
        stage="S2",
        operator="l2.net_cancel_pressure",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Pressure",
        description="(cancel_ask - cancel_bid). Net cancel pressure asymmetry.",
        depends_on=(Dep(name="cancel_rate_ask_fut_10bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_10bps_1s", kind="col"),),
        feature_id=2620,
    ),
    FeatureSpec(
        name="net_cancel_pressure_fut_2bps_1s",
        stage="S2",
        operator="l2.net_cancel_pressure",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Pressure",
        description="(cancel_ask - cancel_bid). Net cancel pressure asymmetry.",
        depends_on=(Dep(name="cancel_rate_ask_fut_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_2bps_1s", kind="col"),),
        feature_id=2621,
    ),
    FeatureSpec(
        name="net_cancel_pressure_fut_5bps_1s",
        stage="S2",
        operator="l2.net_cancel_pressure",
        params={'market_scope': 'Futures', 'window_s': 1, 'resample': '1s'},
        group="Pressure",
        description="(cancel_ask - cancel_bid). Net cancel pressure asymmetry.",
        depends_on=(Dep(name="cancel_rate_ask_fut_5bps_1s", kind="col"), Dep(name="cancel_rate_bid_fut_5bps_1s", kind="col"),),
        feature_id=2622,
    ),
    FeatureSpec(
        name="net_cancel_pressure_spot_10bps_1s",
        stage="S2",
        operator="l2.net_cancel_pressure",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Pressure",
        description="(cancel_ask - cancel_bid). Net cancel pressure asymmetry.",
        depends_on=(Dep(name="cancel_rate_ask_spot_10bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_10bps_1s", kind="col"),),
        feature_id=2623,
    ),
    FeatureSpec(
        name="net_cancel_pressure_spot_2bps_1s",
        stage="S2",
        operator="l2.net_cancel_pressure",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Pressure",
        description="(cancel_ask - cancel_bid). Net cancel pressure asymmetry.",
        depends_on=(Dep(name="cancel_rate_ask_spot_2bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_2bps_1s", kind="col"),),
        feature_id=2624,
    ),
    FeatureSpec(
        name="net_cancel_pressure_spot_5bps_1s",
        stage="S2",
        operator="l2.net_cancel_pressure",
        params={'market_scope': 'Spot', 'window_s': 1, 'resample': '1s'},
        group="Pressure",
        description="(cancel_ask - cancel_bid). Net cancel pressure asymmetry.",
        depends_on=(Dep(name="cancel_rate_ask_spot_5bps_1s", kind="col"), Dep(name="cancel_rate_bid_spot_5bps_1s", kind="col"),),
        feature_id=2625,
    ),
]