# S4 Dynamics Features
# ==============================================================================
# Overview:
#   Temporal dynamics and regime-detection features built on top of S3/S4
#   rolling aggregates. Six sub-families:
#
#   1) d1_/d2_net_pressure: First and second temporal differences (velocity
#      and acceleration) of net pressure across {2,5,10}bps and {5,15}s.
#   2) median_/mad_: Rolling median and MAD for net_pressure, vacuum_score,
#      and absorption_break. Foundation for robust shock detection.
#   3) *_shock_*: Robust shock detectors: |x - median| / (MAD + eps).
#      Applied to net_pressure, vacuum_score, absorption_break, return.
#   4) signal_persist/signal_flip_rate: Directional persistence and
#      sign-change frequency for net pressure and trade absorption ratio.
#   5) ret_shock_{15,60}s: Return shock via robust z-score.
#
# Operators used:
#   derived.d1, derived.d2, derived.rolling_median, derived.rolling_mad,
#   derived.robust_shock, derived.signal_persist, derived.signal_flip_rate
#
# Dependencies: S3 net_pressure, vacuum_score, absorption_break, ret,
#               taker_imbalance_shock, trade_absorption_ratio
# ==============================================================================

from typing import List
from etl.spec import FeatureSpec, Dep

S4_DYNAMICS_FEATURES: List[FeatureSpec] = [

    # === derived.robust_shock ===

    FeatureSpec(
        name="absorption_break_shock_fut_60s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Futures",
                 "value_col": "absorption_break_fut_60s",
                 "median_col": "median_absorption_break_fut_60s",
                 "mad_col": "mad_absorption_break_fut_60s",
                 "eps": "1e-9"},
        label="Absorption Break Shock Fut 60S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |absorption_break - median| / (MAD + eps) (Futures, 60s).",
        depends_on=(
            Dep(name="absorption_break_fut_60s", kind="col"),
            Dep(name="mad_absorption_break_fut_60s", kind="col"),
            Dep(name="median_absorption_break_fut_60s", kind="col"),
        ),
        feature_id=4014,
    ),

    FeatureSpec(
        name="absorption_break_shock_spot_60s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Spot",
                 "value_col": "absorption_break_spot_60s",
                 "median_col": "median_absorption_break_spot_60s",
                 "mad_col": "mad_absorption_break_spot_60s",
                 "eps": "1e-9"},
        label="Absorption Break Shock Spot 60S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |absorption_break - median| / (MAD + eps) (Spot, 60s).",
        depends_on=(
            Dep(name="absorption_break_spot_60s", kind="col"),
            Dep(name="mad_absorption_break_spot_60s", kind="col"),
            Dep(name="median_absorption_break_spot_60s", kind="col"),
        ),
        feature_id=4015,
    ),

    # === derived.d1 ===

    FeatureSpec(
        name="d1_net_pressure_fut_10bps_15s",
        stage="S4",
        operator="derived.d1",
        params={"market_scope": "Futures", "input_col": "net_pressure_fut_10bps_15s"},
        label="D1 Net Pressure Fut 10Bps 15S (Binance)",
        group="Dynamics",
        description="First temporal difference (velocity) of net pressure (Futures, 10bps, 15s).",
        depends_on=(Dep(name="net_pressure_fut_10bps_15s", kind="col"),),
        feature_id=4016,
    ),

    FeatureSpec(
        name="d1_net_pressure_fut_10bps_5s",
        stage="S4",
        operator="derived.d1",
        params={"market_scope": "Futures", "input_col": "net_pressure_fut_10bps_5s"},
        label="D1 Net Pressure Fut 10Bps 5S (Binance)",
        group="Dynamics",
        description="First temporal difference (velocity) of net pressure (Futures, 10bps, 5s).",
        depends_on=(Dep(name="net_pressure_fut_10bps_5s", kind="col"),),
        feature_id=4017,
    ),

    FeatureSpec(
        name="d1_net_pressure_fut_2bps_15s",
        stage="S4",
        operator="derived.d1",
        params={"market_scope": "Futures", "input_col": "net_pressure_fut_2bps_15s"},
        label="D1 Net Pressure Fut 2Bps 15S (Binance)",
        group="Dynamics",
        description="First temporal difference (velocity) of net pressure (Futures, 2bps, 15s).",
        depends_on=(Dep(name="net_pressure_fut_2bps_15s", kind="col"),),
        feature_id=4018,
    ),

    FeatureSpec(
        name="d1_net_pressure_fut_2bps_5s",
        stage="S4",
        operator="derived.d1",
        params={"market_scope": "Futures", "input_col": "net_pressure_fut_2bps_5s"},
        label="D1 Net Pressure Fut 2Bps 5S (Binance)",
        group="Dynamics",
        description="First temporal difference (velocity) of net pressure (Futures, 2bps, 5s).",
        depends_on=(Dep(name="net_pressure_fut_2bps_5s", kind="col"),),
        feature_id=4019,
    ),

    FeatureSpec(
        name="d1_net_pressure_fut_5bps_15s",
        stage="S4",
        operator="derived.d1",
        params={"market_scope": "Futures", "input_col": "net_pressure_fut_5bps_15s"},
        label="D1 Net Pressure Fut 5Bps 15S (Binance)",
        group="Dynamics",
        description="First temporal difference (velocity) of net pressure (Futures, 5bps, 15s).",
        depends_on=(Dep(name="net_pressure_fut_5bps_15s", kind="col"),),
        feature_id=4020,
    ),

    FeatureSpec(
        name="d1_net_pressure_fut_5bps_5s",
        stage="S4",
        operator="derived.d1",
        params={"market_scope": "Futures", "input_col": "net_pressure_fut_5bps_5s"},
        label="D1 Net Pressure Fut 5Bps 5S (Binance)",
        group="Dynamics",
        description="First temporal difference (velocity) of net pressure (Futures, 5bps, 5s).",
        depends_on=(Dep(name="net_pressure_fut_5bps_5s", kind="col"),),
        feature_id=4021,
    ),

    FeatureSpec(
        name="d1_net_pressure_spot_10bps_15s",
        stage="S4",
        operator="derived.d1",
        params={"market_scope": "Spot", "input_col": "net_pressure_spot_10bps_15s"},
        label="D1 Net Pressure Spot 10Bps 15S (Binance)",
        group="Dynamics",
        description="First temporal difference (velocity) of net pressure (Spot, 10bps, 15s).",
        depends_on=(Dep(name="net_pressure_spot_10bps_15s", kind="col"),),
        feature_id=4022,
    ),

    FeatureSpec(
        name="d1_net_pressure_spot_10bps_5s",
        stage="S4",
        operator="derived.d1",
        params={"market_scope": "Spot", "input_col": "net_pressure_spot_10bps_5s"},
        label="D1 Net Pressure Spot 10Bps 5S (Binance)",
        group="Dynamics",
        description="First temporal difference (velocity) of net pressure (Spot, 10bps, 5s).",
        depends_on=(Dep(name="net_pressure_spot_10bps_5s", kind="col"),),
        feature_id=4023,
    ),

    FeatureSpec(
        name="d1_net_pressure_spot_2bps_15s",
        stage="S4",
        operator="derived.d1",
        params={"market_scope": "Spot", "input_col": "net_pressure_spot_2bps_15s"},
        label="D1 Net Pressure Spot 2Bps 15S (Binance)",
        group="Dynamics",
        description="First temporal difference (velocity) of net pressure (Spot, 2bps, 15s).",
        depends_on=(Dep(name="net_pressure_spot_2bps_15s", kind="col"),),
        feature_id=4024,
    ),

    FeatureSpec(
        name="d1_net_pressure_spot_2bps_5s",
        stage="S4",
        operator="derived.d1",
        params={"market_scope": "Spot", "input_col": "net_pressure_spot_2bps_5s"},
        label="D1 Net Pressure Spot 2Bps 5S (Binance)",
        group="Dynamics",
        description="First temporal difference (velocity) of net pressure (Spot, 2bps, 5s).",
        depends_on=(Dep(name="net_pressure_spot_2bps_5s", kind="col"),),
        feature_id=4025,
    ),

    FeatureSpec(
        name="d1_net_pressure_spot_5bps_15s",
        stage="S4",
        operator="derived.d1",
        params={"market_scope": "Spot", "input_col": "net_pressure_spot_5bps_15s"},
        label="D1 Net Pressure Spot 5Bps 15S (Binance)",
        group="Dynamics",
        description="First temporal difference (velocity) of net pressure (Spot, 5bps, 15s).",
        depends_on=(Dep(name="net_pressure_spot_5bps_15s", kind="col"),),
        feature_id=4026,
    ),

    FeatureSpec(
        name="d1_net_pressure_spot_5bps_5s",
        stage="S4",
        operator="derived.d1",
        params={"market_scope": "Spot", "input_col": "net_pressure_spot_5bps_5s"},
        label="D1 Net Pressure Spot 5Bps 5S (Binance)",
        group="Dynamics",
        description="First temporal difference (velocity) of net pressure (Spot, 5bps, 5s).",
        depends_on=(Dep(name="net_pressure_spot_5bps_5s", kind="col"),),
        feature_id=4027,
    ),

    # === derived.d2 ===

    FeatureSpec(
        name="d2_net_pressure_fut_10bps_15s",
        stage="S4",
        operator="derived.d2",
        params={"market_scope": "Futures",
                 "d1_col": "d1_net_pressure_fut_10bps_15s",
                 "base_col": "net_pressure_fut_10bps_15s"},
        label="D2 Net Pressure Fut 10Bps 15S (Binance)",
        group="Dynamics",
        description="Second temporal difference (acceleration) of net pressure (Futures, 10bps, 15s).",
        depends_on=(
            Dep(name="d1_net_pressure_fut_10bps_15s", kind="col"),
            Dep(name="net_pressure_fut_10bps_15s", kind="col"),
        ),
        feature_id=4028,
    ),

    FeatureSpec(
        name="d2_net_pressure_fut_10bps_5s",
        stage="S4",
        operator="derived.d2",
        params={"market_scope": "Futures",
                 "d1_col": "d1_net_pressure_fut_10bps_5s",
                 "base_col": "net_pressure_fut_10bps_5s"},
        label="D2 Net Pressure Fut 10Bps 5S (Binance)",
        group="Dynamics",
        description="Second temporal difference (acceleration) of net pressure (Futures, 10bps, 5s).",
        depends_on=(
            Dep(name="d1_net_pressure_fut_10bps_5s", kind="col"),
            Dep(name="net_pressure_fut_10bps_5s", kind="col"),
        ),
        feature_id=4029,
    ),

    FeatureSpec(
        name="d2_net_pressure_fut_2bps_15s",
        stage="S4",
        operator="derived.d2",
        params={"market_scope": "Futures",
                 "d1_col": "d1_net_pressure_fut_2bps_15s",
                 "base_col": "net_pressure_fut_2bps_15s"},
        label="D2 Net Pressure Fut 2Bps 15S (Binance)",
        group="Dynamics",
        description="Second temporal difference (acceleration) of net pressure (Futures, 2bps, 15s).",
        depends_on=(
            Dep(name="d1_net_pressure_fut_2bps_15s", kind="col"),
            Dep(name="net_pressure_fut_2bps_15s", kind="col"),
        ),
        feature_id=4030,
    ),

    FeatureSpec(
        name="d2_net_pressure_fut_2bps_5s",
        stage="S4",
        operator="derived.d2",
        params={"market_scope": "Futures",
                 "d1_col": "d1_net_pressure_fut_2bps_5s",
                 "base_col": "net_pressure_fut_2bps_5s"},
        label="D2 Net Pressure Fut 2Bps 5S (Binance)",
        group="Dynamics",
        description="Second temporal difference (acceleration) of net pressure (Futures, 2bps, 5s).",
        depends_on=(
            Dep(name="d1_net_pressure_fut_2bps_5s", kind="col"),
            Dep(name="net_pressure_fut_2bps_5s", kind="col"),
        ),
        feature_id=4031,
    ),

    FeatureSpec(
        name="d2_net_pressure_fut_5bps_15s",
        stage="S4",
        operator="derived.d2",
        params={"market_scope": "Futures",
                 "d1_col": "d1_net_pressure_fut_5bps_15s",
                 "base_col": "net_pressure_fut_5bps_15s"},
        label="D2 Net Pressure Fut 5Bps 15S (Binance)",
        group="Dynamics",
        description="Second temporal difference (acceleration) of net pressure (Futures, 5bps, 15s).",
        depends_on=(
            Dep(name="d1_net_pressure_fut_5bps_15s", kind="col"),
            Dep(name="net_pressure_fut_5bps_15s", kind="col"),
        ),
        feature_id=4032,
    ),

    FeatureSpec(
        name="d2_net_pressure_fut_5bps_5s",
        stage="S4",
        operator="derived.d2",
        params={"market_scope": "Futures",
                 "d1_col": "d1_net_pressure_fut_5bps_5s",
                 "base_col": "net_pressure_fut_5bps_5s"},
        label="D2 Net Pressure Fut 5Bps 5S (Binance)",
        group="Dynamics",
        description="Second temporal difference (acceleration) of net pressure (Futures, 5bps, 5s).",
        depends_on=(
            Dep(name="d1_net_pressure_fut_5bps_5s", kind="col"),
            Dep(name="net_pressure_fut_5bps_5s", kind="col"),
        ),
        feature_id=4033,
    ),

    FeatureSpec(
        name="d2_net_pressure_spot_10bps_15s",
        stage="S4",
        operator="derived.d2",
        params={"market_scope": "Spot",
                 "d1_col": "d1_net_pressure_spot_10bps_15s",
                 "base_col": "net_pressure_spot_10bps_15s"},
        label="D2 Net Pressure Spot 10Bps 15S (Binance)",
        group="Dynamics",
        description="Second temporal difference (acceleration) of net pressure (Spot, 10bps, 15s).",
        depends_on=(
            Dep(name="d1_net_pressure_spot_10bps_15s", kind="col"),
            Dep(name="net_pressure_spot_10bps_15s", kind="col"),
        ),
        feature_id=4034,
    ),

    FeatureSpec(
        name="d2_net_pressure_spot_10bps_5s",
        stage="S4",
        operator="derived.d2",
        params={"market_scope": "Spot",
                 "d1_col": "d1_net_pressure_spot_10bps_5s",
                 "base_col": "net_pressure_spot_10bps_5s"},
        label="D2 Net Pressure Spot 10Bps 5S (Binance)",
        group="Dynamics",
        description="Second temporal difference (acceleration) of net pressure (Spot, 10bps, 5s).",
        depends_on=(
            Dep(name="d1_net_pressure_spot_10bps_5s", kind="col"),
            Dep(name="net_pressure_spot_10bps_5s", kind="col"),
        ),
        feature_id=4035,
    ),

    FeatureSpec(
        name="d2_net_pressure_spot_2bps_15s",
        stage="S4",
        operator="derived.d2",
        params={"market_scope": "Spot",
                 "d1_col": "d1_net_pressure_spot_2bps_15s",
                 "base_col": "net_pressure_spot_2bps_15s"},
        label="D2 Net Pressure Spot 2Bps 15S (Binance)",
        group="Dynamics",
        description="Second temporal difference (acceleration) of net pressure (Spot, 2bps, 15s).",
        depends_on=(
            Dep(name="d1_net_pressure_spot_2bps_15s", kind="col"),
            Dep(name="net_pressure_spot_2bps_15s", kind="col"),
        ),
        feature_id=4036,
    ),

    FeatureSpec(
        name="d2_net_pressure_spot_2bps_5s",
        stage="S4",
        operator="derived.d2",
        params={"market_scope": "Spot",
                 "d1_col": "d1_net_pressure_spot_2bps_5s",
                 "base_col": "net_pressure_spot_2bps_5s"},
        label="D2 Net Pressure Spot 2Bps 5S (Binance)",
        group="Dynamics",
        description="Second temporal difference (acceleration) of net pressure (Spot, 2bps, 5s).",
        depends_on=(
            Dep(name="d1_net_pressure_spot_2bps_5s", kind="col"),
            Dep(name="net_pressure_spot_2bps_5s", kind="col"),
        ),
        feature_id=4037,
    ),

    FeatureSpec(
        name="d2_net_pressure_spot_5bps_15s",
        stage="S4",
        operator="derived.d2",
        params={"market_scope": "Spot",
                 "d1_col": "d1_net_pressure_spot_5bps_15s",
                 "base_col": "net_pressure_spot_5bps_15s"},
        label="D2 Net Pressure Spot 5Bps 15S (Binance)",
        group="Dynamics",
        description="Second temporal difference (acceleration) of net pressure (Spot, 5bps, 15s).",
        depends_on=(
            Dep(name="d1_net_pressure_spot_5bps_15s", kind="col"),
            Dep(name="net_pressure_spot_5bps_15s", kind="col"),
        ),
        feature_id=4038,
    ),

    FeatureSpec(
        name="d2_net_pressure_spot_5bps_5s",
        stage="S4",
        operator="derived.d2",
        params={"market_scope": "Spot",
                 "d1_col": "d1_net_pressure_spot_5bps_5s",
                 "base_col": "net_pressure_spot_5bps_5s"},
        label="D2 Net Pressure Spot 5Bps 5S (Binance)",
        group="Dynamics",
        description="Second temporal difference (acceleration) of net pressure (Spot, 5bps, 5s).",
        depends_on=(
            Dep(name="d1_net_pressure_spot_5bps_5s", kind="col"),
            Dep(name="net_pressure_spot_5bps_5s", kind="col"),
        ),
        feature_id=4039,
    ),

    # === derived.rolling_mad ===

    FeatureSpec(
        name="mad_absorption_break_fut_60s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Futures",
                 "base_col": "absorption_break_fut_60s",
                 "median_col": "median_absorption_break_fut_60s",
                 "window_s": "60"},
        label="Mad Absorption Break Fut 60S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of absorption_break_fut_60s.",
        depends_on=(
            Dep(name="absorption_break_fut_60s", kind="col"),
            Dep(name="median_absorption_break_fut_60s", kind="col"),
        ),
        feature_id=4040,
    ),

    FeatureSpec(
        name="mad_absorption_break_spot_60s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Spot",
                 "base_col": "absorption_break_spot_60s",
                 "median_col": "median_absorption_break_spot_60s",
                 "window_s": "60"},
        label="Mad Absorption Break Spot 60S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of absorption_break_spot_60s.",
        depends_on=(
            Dep(name="absorption_break_spot_60s", kind="col"),
            Dep(name="median_absorption_break_spot_60s", kind="col"),
        ),
        feature_id=4041,
    ),

    FeatureSpec(
        name="mad_net_pressure_fut_10bps_15s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Futures",
                 "base_col": "net_pressure_fut_10bps_15s",
                 "median_col": "median_net_pressure_fut_10bps_15s",
                 "window_s": "15"},
        label="Mad Net Pressure Fut 10Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_fut_10bps_15s.",
        depends_on=(
            Dep(name="median_net_pressure_fut_10bps_15s", kind="col"),
            Dep(name="net_pressure_fut_10bps_15s", kind="col"),
        ),
        feature_id=4042,
    ),

    FeatureSpec(
        name="mad_net_pressure_fut_10bps_5s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Futures",
                 "base_col": "net_pressure_fut_10bps_5s",
                 "median_col": "median_net_pressure_fut_10bps_5s",
                 "window_s": "5"},
        label="Mad Net Pressure Fut 10Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_fut_10bps_5s.",
        depends_on=(
            Dep(name="median_net_pressure_fut_10bps_5s", kind="col"),
            Dep(name="net_pressure_fut_10bps_5s", kind="col"),
        ),
        feature_id=4043,
    ),

    FeatureSpec(
        name="mad_net_pressure_fut_10bps_60s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Futures",
                 "base_col": "net_pressure_fut_10bps_60s",
                 "median_col": "median_net_pressure_fut_10bps_60s",
                 "window_s": "60"},
        label="Mad Net Pressure Fut 10Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_fut_10bps_60s.",
        depends_on=(
            Dep(name="median_net_pressure_fut_10bps_60s", kind="col"),
            Dep(name="net_pressure_fut_10bps_60s", kind="col"),
        ),
        feature_id=4044,
    ),

    FeatureSpec(
        name="mad_net_pressure_fut_2bps_15s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Futures",
                 "base_col": "net_pressure_fut_2bps_15s",
                 "median_col": "median_net_pressure_fut_2bps_15s",
                 "window_s": "15"},
        label="Mad Net Pressure Fut 2Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_fut_2bps_15s.",
        depends_on=(
            Dep(name="median_net_pressure_fut_2bps_15s", kind="col"),
            Dep(name="net_pressure_fut_2bps_15s", kind="col"),
        ),
        feature_id=4045,
    ),

    FeatureSpec(
        name="mad_net_pressure_fut_2bps_5s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Futures",
                 "base_col": "net_pressure_fut_2bps_5s",
                 "median_col": "median_net_pressure_fut_2bps_5s",
                 "window_s": "5"},
        label="Mad Net Pressure Fut 2Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_fut_2bps_5s.",
        depends_on=(
            Dep(name="median_net_pressure_fut_2bps_5s", kind="col"),
            Dep(name="net_pressure_fut_2bps_5s", kind="col"),
        ),
        feature_id=4046,
    ),

    FeatureSpec(
        name="mad_net_pressure_fut_2bps_60s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Futures",
                 "base_col": "net_pressure_fut_2bps_60s",
                 "median_col": "median_net_pressure_fut_2bps_60s",
                 "window_s": "60"},
        label="Mad Net Pressure Fut 2Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_fut_2bps_60s.",
        depends_on=(
            Dep(name="median_net_pressure_fut_2bps_60s", kind="col"),
            Dep(name="net_pressure_fut_2bps_60s", kind="col"),
        ),
        feature_id=4047,
    ),

    FeatureSpec(
        name="mad_net_pressure_fut_5bps_15s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Futures",
                 "base_col": "net_pressure_fut_5bps_15s",
                 "median_col": "median_net_pressure_fut_5bps_15s",
                 "window_s": "15"},
        label="Mad Net Pressure Fut 5Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_fut_5bps_15s.",
        depends_on=(
            Dep(name="median_net_pressure_fut_5bps_15s", kind="col"),
            Dep(name="net_pressure_fut_5bps_15s", kind="col"),
        ),
        feature_id=4048,
    ),

    FeatureSpec(
        name="mad_net_pressure_fut_5bps_5s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Futures",
                 "base_col": "net_pressure_fut_5bps_5s",
                 "median_col": "median_net_pressure_fut_5bps_5s",
                 "window_s": "5"},
        label="Mad Net Pressure Fut 5Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_fut_5bps_5s.",
        depends_on=(
            Dep(name="median_net_pressure_fut_5bps_5s", kind="col"),
            Dep(name="net_pressure_fut_5bps_5s", kind="col"),
        ),
        feature_id=4049,
    ),

    FeatureSpec(
        name="mad_net_pressure_fut_5bps_60s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Futures",
                 "base_col": "net_pressure_fut_5bps_60s",
                 "median_col": "median_net_pressure_fut_5bps_60s",
                 "window_s": "60"},
        label="Mad Net Pressure Fut 5Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_fut_5bps_60s.",
        depends_on=(
            Dep(name="median_net_pressure_fut_5bps_60s", kind="col"),
            Dep(name="net_pressure_fut_5bps_60s", kind="col"),
        ),
        feature_id=4050,
    ),

    FeatureSpec(
        name="mad_net_pressure_spot_10bps_15s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Spot",
                 "base_col": "net_pressure_spot_10bps_15s",
                 "median_col": "median_net_pressure_spot_10bps_15s",
                 "window_s": "15"},
        label="Mad Net Pressure Spot 10Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_spot_10bps_15s.",
        depends_on=(
            Dep(name="median_net_pressure_spot_10bps_15s", kind="col"),
            Dep(name="net_pressure_spot_10bps_15s", kind="col"),
        ),
        feature_id=4051,
    ),

    FeatureSpec(
        name="mad_net_pressure_spot_10bps_5s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Spot",
                 "base_col": "net_pressure_spot_10bps_5s",
                 "median_col": "median_net_pressure_spot_10bps_5s",
                 "window_s": "5"},
        label="Mad Net Pressure Spot 10Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_spot_10bps_5s.",
        depends_on=(
            Dep(name="median_net_pressure_spot_10bps_5s", kind="col"),
            Dep(name="net_pressure_spot_10bps_5s", kind="col"),
        ),
        feature_id=4052,
    ),

    FeatureSpec(
        name="mad_net_pressure_spot_10bps_60s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Spot",
                 "base_col": "net_pressure_spot_10bps_60s",
                 "median_col": "median_net_pressure_spot_10bps_60s",
                 "window_s": "60"},
        label="Mad Net Pressure Spot 10Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_spot_10bps_60s.",
        depends_on=(
            Dep(name="median_net_pressure_spot_10bps_60s", kind="col"),
            Dep(name="net_pressure_spot_10bps_60s", kind="col"),
        ),
        feature_id=4053,
    ),

    FeatureSpec(
        name="mad_net_pressure_spot_2bps_15s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Spot",
                 "base_col": "net_pressure_spot_2bps_15s",
                 "median_col": "median_net_pressure_spot_2bps_15s",
                 "window_s": "15"},
        label="Mad Net Pressure Spot 2Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_spot_2bps_15s.",
        depends_on=(
            Dep(name="median_net_pressure_spot_2bps_15s", kind="col"),
            Dep(name="net_pressure_spot_2bps_15s", kind="col"),
        ),
        feature_id=4054,
    ),

    FeatureSpec(
        name="mad_net_pressure_spot_2bps_5s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Spot",
                 "base_col": "net_pressure_spot_2bps_5s",
                 "median_col": "median_net_pressure_spot_2bps_5s",
                 "window_s": "5"},
        label="Mad Net Pressure Spot 2Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_spot_2bps_5s.",
        depends_on=(
            Dep(name="median_net_pressure_spot_2bps_5s", kind="col"),
            Dep(name="net_pressure_spot_2bps_5s", kind="col"),
        ),
        feature_id=4055,
    ),

    FeatureSpec(
        name="mad_net_pressure_spot_2bps_60s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Spot",
                 "base_col": "net_pressure_spot_2bps_60s",
                 "median_col": "median_net_pressure_spot_2bps_60s",
                 "window_s": "60"},
        label="Mad Net Pressure Spot 2Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_spot_2bps_60s.",
        depends_on=(
            Dep(name="median_net_pressure_spot_2bps_60s", kind="col"),
            Dep(name="net_pressure_spot_2bps_60s", kind="col"),
        ),
        feature_id=4056,
    ),

    FeatureSpec(
        name="mad_net_pressure_spot_5bps_15s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Spot",
                 "base_col": "net_pressure_spot_5bps_15s",
                 "median_col": "median_net_pressure_spot_5bps_15s",
                 "window_s": "15"},
        label="Mad Net Pressure Spot 5Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_spot_5bps_15s.",
        depends_on=(
            Dep(name="median_net_pressure_spot_5bps_15s", kind="col"),
            Dep(name="net_pressure_spot_5bps_15s", kind="col"),
        ),
        feature_id=4057,
    ),

    FeatureSpec(
        name="mad_net_pressure_spot_5bps_5s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Spot",
                 "base_col": "net_pressure_spot_5bps_5s",
                 "median_col": "median_net_pressure_spot_5bps_5s",
                 "window_s": "5"},
        label="Mad Net Pressure Spot 5Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_spot_5bps_5s.",
        depends_on=(
            Dep(name="median_net_pressure_spot_5bps_5s", kind="col"),
            Dep(name="net_pressure_spot_5bps_5s", kind="col"),
        ),
        feature_id=4058,
    ),

    FeatureSpec(
        name="mad_net_pressure_spot_5bps_60s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Spot",
                 "base_col": "net_pressure_spot_5bps_60s",
                 "median_col": "median_net_pressure_spot_5bps_60s",
                 "window_s": "60"},
        label="Mad Net Pressure Spot 5Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of net_pressure_spot_5bps_60s.",
        depends_on=(
            Dep(name="median_net_pressure_spot_5bps_60s", kind="col"),
            Dep(name="net_pressure_spot_5bps_60s", kind="col"),
        ),
        feature_id=4059,
    ),

    FeatureSpec(
        name="mad_vacuum_score_fut_10bps_15s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Futures",
                 "base_col": "vacuum_score_fut_10bps_15s",
                 "median_col": "median_vacuum_score_fut_10bps_15s",
                 "window_s": "15"},
        label="Mad Vacuum Score Fut 10Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of vacuum_score_fut_10bps_15s.",
        depends_on=(
            Dep(name="median_vacuum_score_fut_10bps_15s", kind="col"),
            Dep(name="vacuum_score_fut_10bps_15s", kind="col"),
        ),
        feature_id=4060,
    ),

    FeatureSpec(
        name="mad_vacuum_score_fut_10bps_5s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Futures",
                 "base_col": "vacuum_score_fut_10bps_5s",
                 "median_col": "median_vacuum_score_fut_10bps_5s",
                 "window_s": "5"},
        label="Mad Vacuum Score Fut 10Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of vacuum_score_fut_10bps_5s.",
        depends_on=(
            Dep(name="median_vacuum_score_fut_10bps_5s", kind="col"),
            Dep(name="vacuum_score_fut_10bps_5s", kind="col"),
        ),
        feature_id=4061,
    ),

    FeatureSpec(
        name="mad_vacuum_score_fut_10bps_60s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Futures",
                 "base_col": "vacuum_score_fut_10bps_60s",
                 "median_col": "median_vacuum_score_fut_10bps_60s",
                 "window_s": "60"},
        label="Mad Vacuum Score Fut 10Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of vacuum_score_fut_10bps_60s.",
        depends_on=(
            Dep(name="median_vacuum_score_fut_10bps_60s", kind="col"),
            Dep(name="vacuum_score_fut_10bps_60s", kind="col"),
        ),
        feature_id=4062,
    ),

    FeatureSpec(
        name="mad_vacuum_score_fut_5bps_15s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Futures",
                 "base_col": "vacuum_score_fut_5bps_15s",
                 "median_col": "median_vacuum_score_fut_5bps_15s",
                 "window_s": "15"},
        label="Mad Vacuum Score Fut 5Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of vacuum_score_fut_5bps_15s.",
        depends_on=(
            Dep(name="median_vacuum_score_fut_5bps_15s", kind="col"),
            Dep(name="vacuum_score_fut_5bps_15s", kind="col"),
        ),
        feature_id=4063,
    ),

    FeatureSpec(
        name="mad_vacuum_score_fut_5bps_5s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Futures",
                 "base_col": "vacuum_score_fut_5bps_5s",
                 "median_col": "median_vacuum_score_fut_5bps_5s",
                 "window_s": "5"},
        label="Mad Vacuum Score Fut 5Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of vacuum_score_fut_5bps_5s.",
        depends_on=(
            Dep(name="median_vacuum_score_fut_5bps_5s", kind="col"),
            Dep(name="vacuum_score_fut_5bps_5s", kind="col"),
        ),
        feature_id=4064,
    ),

    FeatureSpec(
        name="mad_vacuum_score_fut_5bps_60s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Futures",
                 "base_col": "vacuum_score_fut_5bps_60s",
                 "median_col": "median_vacuum_score_fut_5bps_60s",
                 "window_s": "60"},
        label="Mad Vacuum Score Fut 5Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of vacuum_score_fut_5bps_60s.",
        depends_on=(
            Dep(name="median_vacuum_score_fut_5bps_60s", kind="col"),
            Dep(name="vacuum_score_fut_5bps_60s", kind="col"),
        ),
        feature_id=4065,
    ),

    FeatureSpec(
        name="mad_vacuum_score_spot_10bps_15s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Spot",
                 "base_col": "vacuum_score_spot_10bps_15s",
                 "median_col": "median_vacuum_score_spot_10bps_15s",
                 "window_s": "15"},
        label="Mad Vacuum Score Spot 10Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of vacuum_score_spot_10bps_15s.",
        depends_on=(
            Dep(name="median_vacuum_score_spot_10bps_15s", kind="col"),
            Dep(name="vacuum_score_spot_10bps_15s", kind="col"),
        ),
        feature_id=4066,
    ),

    FeatureSpec(
        name="mad_vacuum_score_spot_10bps_5s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Spot",
                 "base_col": "vacuum_score_spot_10bps_5s",
                 "median_col": "median_vacuum_score_spot_10bps_5s",
                 "window_s": "5"},
        label="Mad Vacuum Score Spot 10Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of vacuum_score_spot_10bps_5s.",
        depends_on=(
            Dep(name="median_vacuum_score_spot_10bps_5s", kind="col"),
            Dep(name="vacuum_score_spot_10bps_5s", kind="col"),
        ),
        feature_id=4067,
    ),

    FeatureSpec(
        name="mad_vacuum_score_spot_10bps_60s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Spot",
                 "base_col": "vacuum_score_spot_10bps_60s",
                 "median_col": "median_vacuum_score_spot_10bps_60s",
                 "window_s": "60"},
        label="Mad Vacuum Score Spot 10Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of vacuum_score_spot_10bps_60s.",
        depends_on=(
            Dep(name="median_vacuum_score_spot_10bps_60s", kind="col"),
            Dep(name="vacuum_score_spot_10bps_60s", kind="col"),
        ),
        feature_id=4068,
    ),

    FeatureSpec(
        name="mad_vacuum_score_spot_5bps_15s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Spot",
                 "base_col": "vacuum_score_spot_5bps_15s",
                 "median_col": "median_vacuum_score_spot_5bps_15s",
                 "window_s": "15"},
        label="Mad Vacuum Score Spot 5Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of vacuum_score_spot_5bps_15s.",
        depends_on=(
            Dep(name="median_vacuum_score_spot_5bps_15s", kind="col"),
            Dep(name="vacuum_score_spot_5bps_15s", kind="col"),
        ),
        feature_id=4069,
    ),

    FeatureSpec(
        name="mad_vacuum_score_spot_5bps_5s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Spot",
                 "base_col": "vacuum_score_spot_5bps_5s",
                 "median_col": "median_vacuum_score_spot_5bps_5s",
                 "window_s": "5"},
        label="Mad Vacuum Score Spot 5Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of vacuum_score_spot_5bps_5s.",
        depends_on=(
            Dep(name="median_vacuum_score_spot_5bps_5s", kind="col"),
            Dep(name="vacuum_score_spot_5bps_5s", kind="col"),
        ),
        feature_id=4070,
    ),

    FeatureSpec(
        name="mad_vacuum_score_spot_5bps_60s",
        stage="S4",
        operator="derived.rolling_mad",
        params={"market_scope": "Spot",
                 "base_col": "vacuum_score_spot_5bps_60s",
                 "median_col": "median_vacuum_score_spot_5bps_60s",
                 "window_s": "60"},
        label="Mad Vacuum Score Spot 5Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling MAD (median absolute deviation) of vacuum_score_spot_5bps_60s.",
        depends_on=(
            Dep(name="median_vacuum_score_spot_5bps_60s", kind="col"),
            Dep(name="vacuum_score_spot_5bps_60s", kind="col"),
        ),
        feature_id=4071,
    ),

    # === derived.rolling_median ===

    FeatureSpec(
        name="median_absorption_break_fut_60s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Futures",
                 "input_col": "absorption_break_fut_60s",
                 "window_s": "60"},
        label="Median Absorption Break Fut 60S (Binance)",
        group="Dynamics",
        description="Rolling median of absorption_break_fut_60s.",
        depends_on=(Dep(name="absorption_break_fut_60s", kind="col"),),
        feature_id=4072,
    ),

    FeatureSpec(
        name="median_absorption_break_spot_60s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Spot",
                 "input_col": "absorption_break_spot_60s",
                 "window_s": "60"},
        label="Median Absorption Break Spot 60S (Binance)",
        group="Dynamics",
        description="Rolling median of absorption_break_spot_60s.",
        depends_on=(Dep(name="absorption_break_spot_60s", kind="col"),),
        feature_id=4073,
    ),

    FeatureSpec(
        name="median_net_pressure_fut_10bps_15s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Futures",
                 "input_col": "net_pressure_fut_10bps_15s",
                 "window_s": "15"},
        label="Median Net Pressure Fut 10Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_fut_10bps_15s.",
        depends_on=(Dep(name="net_pressure_fut_10bps_15s", kind="col"),),
        feature_id=4074,
    ),

    FeatureSpec(
        name="median_net_pressure_fut_10bps_5s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Futures",
                 "input_col": "net_pressure_fut_10bps_5s",
                 "window_s": "5"},
        label="Median Net Pressure Fut 10Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_fut_10bps_5s.",
        depends_on=(Dep(name="net_pressure_fut_10bps_5s", kind="col"),),
        feature_id=4075,
    ),

    FeatureSpec(
        name="median_net_pressure_fut_10bps_60s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Futures",
                 "input_col": "net_pressure_fut_10bps_60s",
                 "window_s": "60"},
        label="Median Net Pressure Fut 10Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_fut_10bps_60s.",
        depends_on=(Dep(name="net_pressure_fut_10bps_60s", kind="col"),),
        feature_id=4076,
    ),

    FeatureSpec(
        name="median_net_pressure_fut_2bps_15s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Futures",
                 "input_col": "net_pressure_fut_2bps_15s",
                 "window_s": "15"},
        label="Median Net Pressure Fut 2Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_fut_2bps_15s.",
        depends_on=(Dep(name="net_pressure_fut_2bps_15s", kind="col"),),
        feature_id=4077,
    ),

    FeatureSpec(
        name="median_net_pressure_fut_2bps_5s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Futures",
                 "input_col": "net_pressure_fut_2bps_5s",
                 "window_s": "5"},
        label="Median Net Pressure Fut 2Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_fut_2bps_5s.",
        depends_on=(Dep(name="net_pressure_fut_2bps_5s", kind="col"),),
        feature_id=4078,
    ),

    FeatureSpec(
        name="median_net_pressure_fut_2bps_60s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Futures",
                 "input_col": "net_pressure_fut_2bps_60s",
                 "window_s": "60"},
        label="Median Net Pressure Fut 2Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_fut_2bps_60s.",
        depends_on=(Dep(name="net_pressure_fut_2bps_60s", kind="col"),),
        feature_id=4079,
    ),

    FeatureSpec(
        name="median_net_pressure_fut_5bps_15s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Futures",
                 "input_col": "net_pressure_fut_5bps_15s",
                 "window_s": "15"},
        label="Median Net Pressure Fut 5Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_fut_5bps_15s.",
        depends_on=(Dep(name="net_pressure_fut_5bps_15s", kind="col"),),
        feature_id=4080,
    ),

    FeatureSpec(
        name="median_net_pressure_fut_5bps_5s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Futures",
                 "input_col": "net_pressure_fut_5bps_5s",
                 "window_s": "5"},
        label="Median Net Pressure Fut 5Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_fut_5bps_5s.",
        depends_on=(Dep(name="net_pressure_fut_5bps_5s", kind="col"),),
        feature_id=4081,
    ),

    FeatureSpec(
        name="median_net_pressure_fut_5bps_60s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Futures",
                 "input_col": "net_pressure_fut_5bps_60s",
                 "window_s": "60"},
        label="Median Net Pressure Fut 5Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_fut_5bps_60s.",
        depends_on=(Dep(name="net_pressure_fut_5bps_60s", kind="col"),),
        feature_id=4082,
    ),

    FeatureSpec(
        name="median_net_pressure_spot_10bps_15s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Spot",
                 "input_col": "net_pressure_spot_10bps_15s",
                 "window_s": "15"},
        label="Median Net Pressure Spot 10Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_spot_10bps_15s.",
        depends_on=(Dep(name="net_pressure_spot_10bps_15s", kind="col"),),
        feature_id=4083,
    ),

    FeatureSpec(
        name="median_net_pressure_spot_10bps_5s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Spot",
                 "input_col": "net_pressure_spot_10bps_5s",
                 "window_s": "5"},
        label="Median Net Pressure Spot 10Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_spot_10bps_5s.",
        depends_on=(Dep(name="net_pressure_spot_10bps_5s", kind="col"),),
        feature_id=4084,
    ),

    FeatureSpec(
        name="median_net_pressure_spot_10bps_60s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Spot",
                 "input_col": "net_pressure_spot_10bps_60s",
                 "window_s": "60"},
        label="Median Net Pressure Spot 10Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_spot_10bps_60s.",
        depends_on=(Dep(name="net_pressure_spot_10bps_60s", kind="col"),),
        feature_id=4085,
    ),

    FeatureSpec(
        name="median_net_pressure_spot_2bps_15s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Spot",
                 "input_col": "net_pressure_spot_2bps_15s",
                 "window_s": "15"},
        label="Median Net Pressure Spot 2Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_spot_2bps_15s.",
        depends_on=(Dep(name="net_pressure_spot_2bps_15s", kind="col"),),
        feature_id=4086,
    ),

    FeatureSpec(
        name="median_net_pressure_spot_2bps_5s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Spot",
                 "input_col": "net_pressure_spot_2bps_5s",
                 "window_s": "5"},
        label="Median Net Pressure Spot 2Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_spot_2bps_5s.",
        depends_on=(Dep(name="net_pressure_spot_2bps_5s", kind="col"),),
        feature_id=4087,
    ),

    FeatureSpec(
        name="median_net_pressure_spot_2bps_60s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Spot",
                 "input_col": "net_pressure_spot_2bps_60s",
                 "window_s": "60"},
        label="Median Net Pressure Spot 2Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_spot_2bps_60s.",
        depends_on=(Dep(name="net_pressure_spot_2bps_60s", kind="col"),),
        feature_id=4088,
    ),

    FeatureSpec(
        name="median_net_pressure_spot_5bps_15s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Spot",
                 "input_col": "net_pressure_spot_5bps_15s",
                 "window_s": "15"},
        label="Median Net Pressure Spot 5Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_spot_5bps_15s.",
        depends_on=(Dep(name="net_pressure_spot_5bps_15s", kind="col"),),
        feature_id=4089,
    ),

    FeatureSpec(
        name="median_net_pressure_spot_5bps_5s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Spot",
                 "input_col": "net_pressure_spot_5bps_5s",
                 "window_s": "5"},
        label="Median Net Pressure Spot 5Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_spot_5bps_5s.",
        depends_on=(Dep(name="net_pressure_spot_5bps_5s", kind="col"),),
        feature_id=4090,
    ),

    FeatureSpec(
        name="median_net_pressure_spot_5bps_60s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Spot",
                 "input_col": "net_pressure_spot_5bps_60s",
                 "window_s": "60"},
        label="Median Net Pressure Spot 5Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling median of net_pressure_spot_5bps_60s.",
        depends_on=(Dep(name="net_pressure_spot_5bps_60s", kind="col"),),
        feature_id=4091,
    ),

    FeatureSpec(
        name="median_vacuum_score_fut_10bps_15s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Futures",
                 "input_col": "vacuum_score_fut_10bps_15s",
                 "window_s": "15"},
        label="Median Vacuum Score Fut 10Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling median of vacuum_score_fut_10bps_15s.",
        depends_on=(Dep(name="vacuum_score_fut_10bps_15s", kind="col"),),
        feature_id=4092,
    ),

    FeatureSpec(
        name="median_vacuum_score_fut_10bps_5s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Futures",
                 "input_col": "vacuum_score_fut_10bps_5s",
                 "window_s": "5"},
        label="Median Vacuum Score Fut 10Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling median of vacuum_score_fut_10bps_5s.",
        depends_on=(Dep(name="vacuum_score_fut_10bps_5s", kind="col"),),
        feature_id=4093,
    ),

    FeatureSpec(
        name="median_vacuum_score_fut_10bps_60s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Futures",
                 "input_col": "vacuum_score_fut_10bps_60s",
                 "window_s": "60"},
        label="Median Vacuum Score Fut 10Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling median of vacuum_score_fut_10bps_60s.",
        depends_on=(Dep(name="vacuum_score_fut_10bps_60s", kind="col"),),
        feature_id=4094,
    ),

    FeatureSpec(
        name="median_vacuum_score_fut_5bps_15s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Futures",
                 "input_col": "vacuum_score_fut_5bps_15s",
                 "window_s": "15"},
        label="Median Vacuum Score Fut 5Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling median of vacuum_score_fut_5bps_15s.",
        depends_on=(Dep(name="vacuum_score_fut_5bps_15s", kind="col"),),
        feature_id=4095,
    ),

    FeatureSpec(
        name="median_vacuum_score_fut_5bps_5s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Futures",
                 "input_col": "vacuum_score_fut_5bps_5s",
                 "window_s": "5"},
        label="Median Vacuum Score Fut 5Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling median of vacuum_score_fut_5bps_5s.",
        depends_on=(Dep(name="vacuum_score_fut_5bps_5s", kind="col"),),
        feature_id=4096,
    ),

    FeatureSpec(
        name="median_vacuum_score_fut_5bps_60s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Futures",
                 "input_col": "vacuum_score_fut_5bps_60s",
                 "window_s": "60"},
        label="Median Vacuum Score Fut 5Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling median of vacuum_score_fut_5bps_60s.",
        depends_on=(Dep(name="vacuum_score_fut_5bps_60s", kind="col"),),
        feature_id=4097,
    ),

    FeatureSpec(
        name="median_vacuum_score_spot_10bps_15s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Spot",
                 "input_col": "vacuum_score_spot_10bps_15s",
                 "window_s": "15"},
        label="Median Vacuum Score Spot 10Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling median of vacuum_score_spot_10bps_15s.",
        depends_on=(Dep(name="vacuum_score_spot_10bps_15s", kind="col"),),
        feature_id=4098,
    ),

    FeatureSpec(
        name="median_vacuum_score_spot_10bps_5s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Spot",
                 "input_col": "vacuum_score_spot_10bps_5s",
                 "window_s": "5"},
        label="Median Vacuum Score Spot 10Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling median of vacuum_score_spot_10bps_5s.",
        depends_on=(Dep(name="vacuum_score_spot_10bps_5s", kind="col"),),
        feature_id=4099,
    ),

    FeatureSpec(
        name="median_vacuum_score_spot_10bps_60s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Spot",
                 "input_col": "vacuum_score_spot_10bps_60s",
                 "window_s": "60"},
        label="Median Vacuum Score Spot 10Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling median of vacuum_score_spot_10bps_60s.",
        depends_on=(Dep(name="vacuum_score_spot_10bps_60s", kind="col"),),
        feature_id=4100,
    ),

    FeatureSpec(
        name="median_vacuum_score_spot_5bps_15s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Spot",
                 "input_col": "vacuum_score_spot_5bps_15s",
                 "window_s": "15"},
        label="Median Vacuum Score Spot 5Bps 15S (Binance)",
        group="Dynamics",
        description="Rolling median of vacuum_score_spot_5bps_15s.",
        depends_on=(Dep(name="vacuum_score_spot_5bps_15s", kind="col"),),
        feature_id=4101,
    ),

    FeatureSpec(
        name="median_vacuum_score_spot_5bps_5s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Spot",
                 "input_col": "vacuum_score_spot_5bps_5s",
                 "window_s": "5"},
        label="Median Vacuum Score Spot 5Bps 5S (Binance)",
        group="Dynamics",
        description="Rolling median of vacuum_score_spot_5bps_5s.",
        depends_on=(Dep(name="vacuum_score_spot_5bps_5s", kind="col"),),
        feature_id=4102,
    ),

    FeatureSpec(
        name="median_vacuum_score_spot_5bps_60s",
        stage="S4",
        operator="derived.rolling_median",
        params={"market_scope": "Spot",
                 "input_col": "vacuum_score_spot_5bps_60s",
                 "window_s": "60"},
        label="Median Vacuum Score Spot 5Bps 60S (Binance)",
        group="Dynamics",
        description="Rolling median of vacuum_score_spot_5bps_60s.",
        depends_on=(Dep(name="vacuum_score_spot_5bps_60s", kind="col"),),
        feature_id=4103,
    ),

    # === derived.signal_flip_rate ===

    FeatureSpec(
        name="net_pressure_flip_rate_fut_10bps_60s",
        stage="S4",
        operator="derived.signal_flip_rate",
        params={"market_scope": "Futures",
                 "window_s": "60",
                 "input_col": "net_pressure_fut_10bps_60s"},
        label="Net Pressure Flip Rate Fut 10Bps 60S (Binance)",
        group="Dynamics",
        description="Sign-change frequency of net pressure within window (Futures, 10bps, 60s).",
        depends_on=(Dep(name="net_pressure_fut_10bps_60s", kind="col"),),
        feature_id=4104,
    ),

    FeatureSpec(
        name="net_pressure_flip_rate_fut_5bps_60s",
        stage="S4",
        operator="derived.signal_flip_rate",
        params={"market_scope": "Futures",
                 "window_s": "60",
                 "input_col": "net_pressure_fut_5bps_60s"},
        label="Net Pressure Flip Rate Fut 5Bps 60S (Binance)",
        group="Dynamics",
        description="Sign-change frequency of net pressure within window (Futures, 5bps, 60s).",
        depends_on=(Dep(name="net_pressure_fut_5bps_60s", kind="col"),),
        feature_id=4105,
    ),

    FeatureSpec(
        name="net_pressure_flip_rate_spot_10bps_60s",
        stage="S4",
        operator="derived.signal_flip_rate",
        params={"market_scope": "Spot",
                 "window_s": "60",
                 "input_col": "net_pressure_spot_10bps_60s"},
        label="Net Pressure Flip Rate Spot 10Bps 60S (Binance)",
        group="Dynamics",
        description="Sign-change frequency of net pressure within window (Spot, 10bps, 60s).",
        depends_on=(Dep(name="net_pressure_spot_10bps_60s", kind="col"),),
        feature_id=4106,
    ),

    FeatureSpec(
        name="net_pressure_flip_rate_spot_5bps_60s",
        stage="S4",
        operator="derived.signal_flip_rate",
        params={"market_scope": "Spot",
                 "window_s": "60",
                 "input_col": "net_pressure_spot_5bps_60s"},
        label="Net Pressure Flip Rate Spot 5Bps 60S (Binance)",
        group="Dynamics",
        description="Sign-change frequency of net pressure within window (Spot, 5bps, 60s).",
        depends_on=(Dep(name="net_pressure_spot_5bps_60s", kind="col"),),
        feature_id=4107,
    ),

    # === derived.signal_persist ===

    FeatureSpec(
        name="net_pressure_persist_fut_10bps_60s",
        stage="S4",
        operator="derived.signal_persist",
        params={"market_scope": "Futures",
                 "window_s": "60",
                 "input_col": "net_pressure_fut_10bps_60s"},
        label="Net Pressure Persist Fut 10Bps 60S (Binance)",
        group="Dynamics",
        description="Persistence: fraction of 5s sub-buckets with consistent sign (Futures, 10bps, 60s).",
        depends_on=(Dep(name="net_pressure_fut_10bps_60s", kind="col"),),
        feature_id=4108,
    ),

    FeatureSpec(
        name="net_pressure_persist_fut_5bps_60s",
        stage="S4",
        operator="derived.signal_persist",
        params={"market_scope": "Futures",
                 "window_s": "60",
                 "input_col": "net_pressure_fut_5bps_60s"},
        label="Net Pressure Persist Fut 5Bps 60S (Binance)",
        group="Dynamics",
        description="Persistence: fraction of 5s sub-buckets with consistent sign (Futures, 5bps, 60s).",
        depends_on=(Dep(name="net_pressure_fut_5bps_60s", kind="col"),),
        feature_id=4109,
    ),

    FeatureSpec(
        name="net_pressure_persist_spot_10bps_60s",
        stage="S4",
        operator="derived.signal_persist",
        params={"market_scope": "Spot",
                 "window_s": "60",
                 "input_col": "net_pressure_spot_10bps_60s"},
        label="Net Pressure Persist Spot 10Bps 60S (Binance)",
        group="Dynamics",
        description="Persistence: fraction of 5s sub-buckets with consistent sign (Spot, 10bps, 60s).",
        depends_on=(Dep(name="net_pressure_spot_10bps_60s", kind="col"),),
        feature_id=4110,
    ),

    FeatureSpec(
        name="net_pressure_persist_spot_5bps_60s",
        stage="S4",
        operator="derived.signal_persist",
        params={"market_scope": "Spot",
                 "window_s": "60",
                 "input_col": "net_pressure_spot_5bps_60s"},
        label="Net Pressure Persist Spot 5Bps 60S (Binance)",
        group="Dynamics",
        description="Persistence: fraction of 5s sub-buckets with consistent sign (Spot, 5bps, 60s).",
        depends_on=(Dep(name="net_pressure_spot_5bps_60s", kind="col"),),
        feature_id=4111,
    ),

    # === derived.robust_shock ===

    FeatureSpec(
        name="net_pressure_shock_fut_10bps_15s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Futures",
                 "value_col": "net_pressure_fut_10bps_15s",
                 "median_col": "median_net_pressure_fut_10bps_15s",
                 "mad_col": "mad_net_pressure_fut_10bps_15s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Fut 10Bps 15S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Futures, 10bps, 15s).",
        depends_on=(
            Dep(name="mad_net_pressure_fut_10bps_15s", kind="col"),
            Dep(name="median_net_pressure_fut_10bps_15s", kind="col"),
            Dep(name="net_pressure_fut_10bps_15s", kind="col"),
        ),
        feature_id=4112,
    ),

    FeatureSpec(
        name="net_pressure_shock_fut_10bps_5s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Futures",
                 "value_col": "net_pressure_fut_10bps_5s",
                 "median_col": "median_net_pressure_fut_10bps_5s",
                 "mad_col": "mad_net_pressure_fut_10bps_5s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Fut 10Bps 5S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Futures, 10bps, 5s).",
        depends_on=(
            Dep(name="mad_net_pressure_fut_10bps_5s", kind="col"),
            Dep(name="median_net_pressure_fut_10bps_5s", kind="col"),
            Dep(name="net_pressure_fut_10bps_5s", kind="col"),
        ),
        feature_id=4113,
    ),

    FeatureSpec(
        name="net_pressure_shock_fut_10bps_60s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Futures",
                 "value_col": "net_pressure_fut_10bps_60s",
                 "median_col": "median_net_pressure_fut_10bps_60s",
                 "mad_col": "mad_net_pressure_fut_10bps_60s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Fut 10Bps 60S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Futures, 10bps, 60s).",
        depends_on=(
            Dep(name="mad_net_pressure_fut_10bps_60s", kind="col"),
            Dep(name="median_net_pressure_fut_10bps_60s", kind="col"),
            Dep(name="net_pressure_fut_10bps_60s", kind="col"),
        ),
        feature_id=4114,
    ),

    FeatureSpec(
        name="net_pressure_shock_fut_2bps_15s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Futures",
                 "value_col": "net_pressure_fut_2bps_15s",
                 "median_col": "median_net_pressure_fut_2bps_15s",
                 "mad_col": "mad_net_pressure_fut_2bps_15s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Fut 2Bps 15S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Futures, 2bps, 15s).",
        depends_on=(
            Dep(name="mad_net_pressure_fut_2bps_15s", kind="col"),
            Dep(name="median_net_pressure_fut_2bps_15s", kind="col"),
            Dep(name="net_pressure_fut_2bps_15s", kind="col"),
        ),
        feature_id=4115,
    ),

    FeatureSpec(
        name="net_pressure_shock_fut_2bps_5s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Futures",
                 "value_col": "net_pressure_fut_2bps_5s",
                 "median_col": "median_net_pressure_fut_2bps_5s",
                 "mad_col": "mad_net_pressure_fut_2bps_5s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Fut 2Bps 5S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Futures, 2bps, 5s).",
        depends_on=(
            Dep(name="mad_net_pressure_fut_2bps_5s", kind="col"),
            Dep(name="median_net_pressure_fut_2bps_5s", kind="col"),
            Dep(name="net_pressure_fut_2bps_5s", kind="col"),
        ),
        feature_id=4116,
    ),

    FeatureSpec(
        name="net_pressure_shock_fut_2bps_60s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Futures",
                 "value_col": "net_pressure_fut_2bps_60s",
                 "median_col": "median_net_pressure_fut_2bps_60s",
                 "mad_col": "mad_net_pressure_fut_2bps_60s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Fut 2Bps 60S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Futures, 2bps, 60s).",
        depends_on=(
            Dep(name="mad_net_pressure_fut_2bps_60s", kind="col"),
            Dep(name="median_net_pressure_fut_2bps_60s", kind="col"),
            Dep(name="net_pressure_fut_2bps_60s", kind="col"),
        ),
        feature_id=4117,
    ),

    FeatureSpec(
        name="net_pressure_shock_fut_5bps_15s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Futures",
                 "value_col": "net_pressure_fut_5bps_15s",
                 "median_col": "median_net_pressure_fut_5bps_15s",
                 "mad_col": "mad_net_pressure_fut_5bps_15s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Fut 5Bps 15S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Futures, 5bps, 15s).",
        depends_on=(
            Dep(name="mad_net_pressure_fut_5bps_15s", kind="col"),
            Dep(name="median_net_pressure_fut_5bps_15s", kind="col"),
            Dep(name="net_pressure_fut_5bps_15s", kind="col"),
        ),
        feature_id=4118,
    ),

    FeatureSpec(
        name="net_pressure_shock_fut_5bps_5s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Futures",
                 "value_col": "net_pressure_fut_5bps_5s",
                 "median_col": "median_net_pressure_fut_5bps_5s",
                 "mad_col": "mad_net_pressure_fut_5bps_5s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Fut 5Bps 5S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Futures, 5bps, 5s).",
        depends_on=(
            Dep(name="mad_net_pressure_fut_5bps_5s", kind="col"),
            Dep(name="median_net_pressure_fut_5bps_5s", kind="col"),
            Dep(name="net_pressure_fut_5bps_5s", kind="col"),
        ),
        feature_id=4119,
    ),

    FeatureSpec(
        name="net_pressure_shock_fut_5bps_60s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Futures",
                 "value_col": "net_pressure_fut_5bps_60s",
                 "median_col": "median_net_pressure_fut_5bps_60s",
                 "mad_col": "mad_net_pressure_fut_5bps_60s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Fut 5Bps 60S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Futures, 5bps, 60s).",
        depends_on=(
            Dep(name="mad_net_pressure_fut_5bps_60s", kind="col"),
            Dep(name="median_net_pressure_fut_5bps_60s", kind="col"),
            Dep(name="net_pressure_fut_5bps_60s", kind="col"),
        ),
        feature_id=4120,
    ),

    FeatureSpec(
        name="net_pressure_shock_spot_10bps_15s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Spot",
                 "value_col": "net_pressure_spot_10bps_15s",
                 "median_col": "median_net_pressure_spot_10bps_15s",
                 "mad_col": "mad_net_pressure_spot_10bps_15s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Spot 10Bps 15S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Spot, 10bps, 15s).",
        depends_on=(
            Dep(name="mad_net_pressure_spot_10bps_15s", kind="col"),
            Dep(name="median_net_pressure_spot_10bps_15s", kind="col"),
            Dep(name="net_pressure_spot_10bps_15s", kind="col"),
        ),
        feature_id=4121,
    ),

    FeatureSpec(
        name="net_pressure_shock_spot_10bps_5s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Spot",
                 "value_col": "net_pressure_spot_10bps_5s",
                 "median_col": "median_net_pressure_spot_10bps_5s",
                 "mad_col": "mad_net_pressure_spot_10bps_5s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Spot 10Bps 5S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Spot, 10bps, 5s).",
        depends_on=(
            Dep(name="mad_net_pressure_spot_10bps_5s", kind="col"),
            Dep(name="median_net_pressure_spot_10bps_5s", kind="col"),
            Dep(name="net_pressure_spot_10bps_5s", kind="col"),
        ),
        feature_id=4122,
    ),

    FeatureSpec(
        name="net_pressure_shock_spot_10bps_60s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Spot",
                 "value_col": "net_pressure_spot_10bps_60s",
                 "median_col": "median_net_pressure_spot_10bps_60s",
                 "mad_col": "mad_net_pressure_spot_10bps_60s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Spot 10Bps 60S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Spot, 10bps, 60s).",
        depends_on=(
            Dep(name="mad_net_pressure_spot_10bps_60s", kind="col"),
            Dep(name="median_net_pressure_spot_10bps_60s", kind="col"),
            Dep(name="net_pressure_spot_10bps_60s", kind="col"),
        ),
        feature_id=4123,
    ),

    FeatureSpec(
        name="net_pressure_shock_spot_2bps_15s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Spot",
                 "value_col": "net_pressure_spot_2bps_15s",
                 "median_col": "median_net_pressure_spot_2bps_15s",
                 "mad_col": "mad_net_pressure_spot_2bps_15s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Spot 2Bps 15S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Spot, 2bps, 15s).",
        depends_on=(
            Dep(name="mad_net_pressure_spot_2bps_15s", kind="col"),
            Dep(name="median_net_pressure_spot_2bps_15s", kind="col"),
            Dep(name="net_pressure_spot_2bps_15s", kind="col"),
        ),
        feature_id=4124,
    ),

    FeatureSpec(
        name="net_pressure_shock_spot_2bps_5s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Spot",
                 "value_col": "net_pressure_spot_2bps_5s",
                 "median_col": "median_net_pressure_spot_2bps_5s",
                 "mad_col": "mad_net_pressure_spot_2bps_5s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Spot 2Bps 5S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Spot, 2bps, 5s).",
        depends_on=(
            Dep(name="mad_net_pressure_spot_2bps_5s", kind="col"),
            Dep(name="median_net_pressure_spot_2bps_5s", kind="col"),
            Dep(name="net_pressure_spot_2bps_5s", kind="col"),
        ),
        feature_id=4125,
    ),

    FeatureSpec(
        name="net_pressure_shock_spot_2bps_60s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Spot",
                 "value_col": "net_pressure_spot_2bps_60s",
                 "median_col": "median_net_pressure_spot_2bps_60s",
                 "mad_col": "mad_net_pressure_spot_2bps_60s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Spot 2Bps 60S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Spot, 2bps, 60s).",
        depends_on=(
            Dep(name="mad_net_pressure_spot_2bps_60s", kind="col"),
            Dep(name="median_net_pressure_spot_2bps_60s", kind="col"),
            Dep(name="net_pressure_spot_2bps_60s", kind="col"),
        ),
        feature_id=4126,
    ),

    FeatureSpec(
        name="net_pressure_shock_spot_5bps_15s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Spot",
                 "value_col": "net_pressure_spot_5bps_15s",
                 "median_col": "median_net_pressure_spot_5bps_15s",
                 "mad_col": "mad_net_pressure_spot_5bps_15s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Spot 5Bps 15S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Spot, 5bps, 15s).",
        depends_on=(
            Dep(name="mad_net_pressure_spot_5bps_15s", kind="col"),
            Dep(name="median_net_pressure_spot_5bps_15s", kind="col"),
            Dep(name="net_pressure_spot_5bps_15s", kind="col"),
        ),
        feature_id=4127,
    ),

    FeatureSpec(
        name="net_pressure_shock_spot_5bps_5s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Spot",
                 "value_col": "net_pressure_spot_5bps_5s",
                 "median_col": "median_net_pressure_spot_5bps_5s",
                 "mad_col": "mad_net_pressure_spot_5bps_5s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Spot 5Bps 5S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Spot, 5bps, 5s).",
        depends_on=(
            Dep(name="mad_net_pressure_spot_5bps_5s", kind="col"),
            Dep(name="median_net_pressure_spot_5bps_5s", kind="col"),
            Dep(name="net_pressure_spot_5bps_5s", kind="col"),
        ),
        feature_id=4128,
    ),

    FeatureSpec(
        name="net_pressure_shock_spot_5bps_60s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Spot",
                 "value_col": "net_pressure_spot_5bps_60s",
                 "median_col": "median_net_pressure_spot_5bps_60s",
                 "mad_col": "mad_net_pressure_spot_5bps_60s",
                 "eps": "1e-9"},
        label="Net Pressure Shock Spot 5Bps 60S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |net_pressure - median| / (MAD + eps) (Spot, 5bps, 60s).",
        depends_on=(
            Dep(name="mad_net_pressure_spot_5bps_60s", kind="col"),
            Dep(name="median_net_pressure_spot_5bps_60s", kind="col"),
            Dep(name="net_pressure_spot_5bps_60s", kind="col"),
        ),
        feature_id=4129,
    ),

    # === derived.robust_shock ===

    FeatureSpec(
        name="ret_shock_15s",
        stage="S4",
        operator="derived.robust_zscore",
        params={"input_col": "ret_15s", "window_s": "300", "eps": "1e-9"},
        label="Ret Shock 15S (Binance)",
        group="Dynamics",
        description="Robust z-score of 15s return: (ret - rolling_median) / (MAD * 1.4826), 300s window.",
        depends_on=(Dep(name="ret_15s", kind="col"),),
        feature_id=4130,
    ),

    FeatureSpec(
        name="ret_shock_60s",
        stage="S4",
        operator="derived.robust_zscore",
        params={"input_col": "ret_60s", "window_s": "900", "eps": "1e-9"},  # was 3600
        label="Ret Shock 60S (Binance)",
        group="Dynamics",
        description="Robust z-score of 60s return: (ret - rolling_median) / (MAD * 1.4826), 900s window.",
        depends_on=(Dep(name="ret_60s", kind="col"),),
        feature_id=4131,
    ),

    # === derived.signal_persist ===

    FeatureSpec(
        name="trade_absorption_ratio_fut_persist_60s",
        stage="S4",
        operator="derived.signal_persist",
        params={"market_scope": "Futures",
                 "window_s": "60",
                 "input_col": "trade_absorption_ratio_fut_60s"},
        label="Trade Absorption Ratio Fut Persist 60S (Binance)",
        group="Dynamics",
        description="Persistence: fraction of sub-buckets where sign stays consistent (Futures, 60s).",
        depends_on=(Dep(name="trade_absorption_ratio_fut_60s", kind="col"),),
        feature_id=4132,
    ),

    FeatureSpec(
        name="trade_absorption_ratio_fut_persist_900s",
        stage="S4",
        operator="derived.signal_persist",
        params={"market_scope": "Futures",
                 "window_s": "900",
                 "input_col": "trade_absorption_ratio_fut_900s"},
        label="Trade Absorption Ratio Fut Persist 900S (Binance)",
        group="Dynamics",
        description="Persistence: fraction of sub-buckets where sign stays consistent (Futures, 900s).",
        depends_on=(Dep(name="trade_absorption_ratio_fut_900s", kind="col"),),
        feature_id=4133,
    ),

    FeatureSpec(
        name="trade_absorption_ratio_spot_persist_60s",
        stage="S4",
        operator="derived.signal_persist",
        params={"market_scope": "Spot",
                 "window_s": "60",
                 "input_col": "trade_absorption_ratio_spot_60s"},
        label="Trade Absorption Ratio Spot Persist 60S (Binance)",
        group="Dynamics",
        description="Persistence: fraction of sub-buckets where sign stays consistent (Spot, 60s).",
        depends_on=(Dep(name="trade_absorption_ratio_spot_60s", kind="col"),),
        feature_id=4134,
    ),

    FeatureSpec(
        name="trade_absorption_ratio_spot_persist_900s",
        stage="S4",
        operator="derived.signal_persist",
        params={"market_scope": "Spot",
                 "window_s": "900",
                 "input_col": "trade_absorption_ratio_spot_900s"},
        label="Trade Absorption Ratio Spot Persist 900S (Binance)",
        group="Dynamics",
        description="Persistence: fraction of sub-buckets where sign stays consistent (Spot, 900s).",
        depends_on=(Dep(name="trade_absorption_ratio_spot_900s", kind="col"),),
        feature_id=4135,
    ),

    # === derived.robust_shock ===

    FeatureSpec(
        name="vacuum_score_shock_fut_10bps_15s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Futures",
                 "value_col": "vacuum_score_fut_10bps_15s",
                 "median_col": "median_vacuum_score_fut_10bps_15s",
                 "mad_col": "mad_vacuum_score_fut_10bps_15s",
                 "eps": "1e-9"},
        label="Vacuum Score Shock Fut 10Bps 15S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |vacuum_score - median| / (MAD + eps) (Futures, 10bps, 15s).",
        depends_on=(
            Dep(name="mad_vacuum_score_fut_10bps_15s", kind="col"),
            Dep(name="median_vacuum_score_fut_10bps_15s", kind="col"),
            Dep(name="vacuum_score_fut_10bps_15s", kind="col"),
        ),
        feature_id=4136,
    ),

    FeatureSpec(
        name="vacuum_score_shock_fut_10bps_5s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Futures",
                 "value_col": "vacuum_score_fut_10bps_5s",
                 "median_col": "median_vacuum_score_fut_10bps_5s",
                 "mad_col": "mad_vacuum_score_fut_10bps_5s",
                 "eps": "1e-9"},
        label="Vacuum Score Shock Fut 10Bps 5S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |vacuum_score - median| / (MAD + eps) (Futures, 10bps, 5s).",
        depends_on=(
            Dep(name="mad_vacuum_score_fut_10bps_5s", kind="col"),
            Dep(name="median_vacuum_score_fut_10bps_5s", kind="col"),
            Dep(name="vacuum_score_fut_10bps_5s", kind="col"),
        ),
        feature_id=4137,
    ),

    FeatureSpec(
        name="vacuum_score_shock_fut_10bps_60s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Futures",
                 "value_col": "vacuum_score_fut_10bps_60s",
                 "median_col": "median_vacuum_score_fut_10bps_60s",
                 "mad_col": "mad_vacuum_score_fut_10bps_60s",
                 "eps": "1e-9"},
        label="Vacuum Score Shock Fut 10Bps 60S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |vacuum_score - median| / (MAD + eps) (Futures, 10bps, 60s).",
        depends_on=(
            Dep(name="mad_vacuum_score_fut_10bps_60s", kind="col"),
            Dep(name="median_vacuum_score_fut_10bps_60s", kind="col"),
            Dep(name="vacuum_score_fut_10bps_60s", kind="col"),
        ),
        feature_id=4138,
    ),

    FeatureSpec(
        name="vacuum_score_shock_fut_5bps_15s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Futures",
                 "value_col": "vacuum_score_fut_5bps_15s",
                 "median_col": "median_vacuum_score_fut_5bps_15s",
                 "mad_col": "mad_vacuum_score_fut_5bps_15s",
                 "eps": "1e-9"},
        label="Vacuum Score Shock Fut 5Bps 15S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |vacuum_score - median| / (MAD + eps) (Futures, 5bps, 15s).",
        depends_on=(
            Dep(name="mad_vacuum_score_fut_5bps_15s", kind="col"),
            Dep(name="median_vacuum_score_fut_5bps_15s", kind="col"),
            Dep(name="vacuum_score_fut_5bps_15s", kind="col"),
        ),
        feature_id=4139,
    ),

    FeatureSpec(
        name="vacuum_score_shock_fut_5bps_5s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Futures",
                 "value_col": "vacuum_score_fut_5bps_5s",
                 "median_col": "median_vacuum_score_fut_5bps_5s",
                 "mad_col": "mad_vacuum_score_fut_5bps_5s",
                 "eps": "1e-9"},
        label="Vacuum Score Shock Fut 5Bps 5S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |vacuum_score - median| / (MAD + eps) (Futures, 5bps, 5s).",
        depends_on=(
            Dep(name="mad_vacuum_score_fut_5bps_5s", kind="col"),
            Dep(name="median_vacuum_score_fut_5bps_5s", kind="col"),
            Dep(name="vacuum_score_fut_5bps_5s", kind="col"),
        ),
        feature_id=4140,
    ),

    FeatureSpec(
        name="vacuum_score_shock_fut_5bps_60s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Futures",
                 "value_col": "vacuum_score_fut_5bps_60s",
                 "median_col": "median_vacuum_score_fut_5bps_60s",
                 "mad_col": "mad_vacuum_score_fut_5bps_60s",
                 "eps": "1e-9"},
        label="Vacuum Score Shock Fut 5Bps 60S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |vacuum_score - median| / (MAD + eps) (Futures, 5bps, 60s).",
        depends_on=(
            Dep(name="mad_vacuum_score_fut_5bps_60s", kind="col"),
            Dep(name="median_vacuum_score_fut_5bps_60s", kind="col"),
            Dep(name="vacuum_score_fut_5bps_60s", kind="col"),
        ),
        feature_id=4141,
    ),

    FeatureSpec(
        name="vacuum_score_shock_spot_10bps_15s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Spot",
                 "value_col": "vacuum_score_spot_10bps_15s",
                 "median_col": "median_vacuum_score_spot_10bps_15s",
                 "mad_col": "mad_vacuum_score_spot_10bps_15s",
                 "eps": "1e-9"},
        label="Vacuum Score Shock Spot 10Bps 15S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |vacuum_score - median| / (MAD + eps) (Spot, 10bps, 15s).",
        depends_on=(
            Dep(name="mad_vacuum_score_spot_10bps_15s", kind="col"),
            Dep(name="median_vacuum_score_spot_10bps_15s", kind="col"),
            Dep(name="vacuum_score_spot_10bps_15s", kind="col"),
        ),
        feature_id=4142,
    ),

    FeatureSpec(
        name="vacuum_score_shock_spot_10bps_5s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Spot",
                 "value_col": "vacuum_score_spot_10bps_5s",
                 "median_col": "median_vacuum_score_spot_10bps_5s",
                 "mad_col": "mad_vacuum_score_spot_10bps_5s",
                 "eps": "1e-9"},
        label="Vacuum Score Shock Spot 10Bps 5S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |vacuum_score - median| / (MAD + eps) (Spot, 10bps, 5s).",
        depends_on=(
            Dep(name="mad_vacuum_score_spot_10bps_5s", kind="col"),
            Dep(name="median_vacuum_score_spot_10bps_5s", kind="col"),
            Dep(name="vacuum_score_spot_10bps_5s", kind="col"),
        ),
        feature_id=4143,
    ),

    FeatureSpec(
        name="vacuum_score_shock_spot_10bps_60s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Spot",
                 "value_col": "vacuum_score_spot_10bps_60s",
                 "median_col": "median_vacuum_score_spot_10bps_60s",
                 "mad_col": "mad_vacuum_score_spot_10bps_60s",
                 "eps": "1e-9"},
        label="Vacuum Score Shock Spot 10Bps 60S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |vacuum_score - median| / (MAD + eps) (Spot, 10bps, 60s).",
        depends_on=(
            Dep(name="mad_vacuum_score_spot_10bps_60s", kind="col"),
            Dep(name="median_vacuum_score_spot_10bps_60s", kind="col"),
            Dep(name="vacuum_score_spot_10bps_60s", kind="col"),
        ),
        feature_id=4144,
    ),

    FeatureSpec(
        name="vacuum_score_shock_spot_5bps_15s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Spot",
                 "value_col": "vacuum_score_spot_5bps_15s",
                 "median_col": "median_vacuum_score_spot_5bps_15s",
                 "mad_col": "mad_vacuum_score_spot_5bps_15s",
                 "eps": "1e-9"},
        label="Vacuum Score Shock Spot 5Bps 15S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |vacuum_score - median| / (MAD + eps) (Spot, 5bps, 15s).",
        depends_on=(
            Dep(name="mad_vacuum_score_spot_5bps_15s", kind="col"),
            Dep(name="median_vacuum_score_spot_5bps_15s", kind="col"),
            Dep(name="vacuum_score_spot_5bps_15s", kind="col"),
        ),
        feature_id=4145,
    ),

    FeatureSpec(
        name="vacuum_score_shock_spot_5bps_5s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Spot",
                 "value_col": "vacuum_score_spot_5bps_5s",
                 "median_col": "median_vacuum_score_spot_5bps_5s",
                 "mad_col": "mad_vacuum_score_spot_5bps_5s",
                 "eps": "1e-9"},
        label="Vacuum Score Shock Spot 5Bps 5S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |vacuum_score - median| / (MAD + eps) (Spot, 5bps, 5s).",
        depends_on=(
            Dep(name="mad_vacuum_score_spot_5bps_5s", kind="col"),
            Dep(name="median_vacuum_score_spot_5bps_5s", kind="col"),
            Dep(name="vacuum_score_spot_5bps_5s", kind="col"),
        ),
        feature_id=4146,
    ),

    FeatureSpec(
        name="vacuum_score_shock_spot_5bps_60s",
        stage="S4",
        operator="derived.robust_shock",
        params={"market_scope": "Spot",
                 "value_col": "vacuum_score_spot_5bps_60s",
                 "median_col": "median_vacuum_score_spot_5bps_60s",
                 "mad_col": "mad_vacuum_score_spot_5bps_60s",
                 "eps": "1e-9"},
        label="Vacuum Score Shock Spot 5Bps 60S (Binance)",
        group="Dynamics",
        description="Robust shock detector: |vacuum_score - median| / (MAD + eps) (Spot, 5bps, 60s).",
        depends_on=(
            Dep(name="mad_vacuum_score_spot_5bps_60s", kind="col"),
            Dep(name="median_vacuum_score_spot_5bps_60s", kind="col"),
            Dep(name="vacuum_score_spot_5bps_60s", kind="col"),
        ),
        feature_id=4147,
    ),
]