# S4 Pressure Features
# ==============================================================================
# Overview:
#   Rolling aggregations and transformations of net order-flow pressure.
#   Three sub-families:
#
#   1) net_add/net_cancel rolling sums: Short-horizon (5s, 15s, 60s)
#      aggregation of 1s net-add and net-cancel pressure across
#      {2,5,10}bps bands, both Futures and Spot. (36 features)
#   2) net_pressure_logratio: Log-ratio of inner/outer depth bands
#      (2bps/5bps, 5bps/10bps) to detect pressure migration. (4 features)
#   3) net_pressure_pct_rank: Rolling percentile rank of net pressure
#      for non-parametric signal strength. (6 features)
#   4) net_pressure_robust_z: Robust z-score on rolling net-add-pressure
#      sums at {5,10}bps for {60,300}s. (8 features)
#
# Operators used:
#   derived.roll_sum, derived.logratio, derived.pct_rank, derived.robust_zscore
#
# Dependencies: S3 net_add_*_1s, net_cancel_*_1s, net_pressure_logratio_*_1s,
#               net_pressure_*, net_add_pressure_*
# ==============================================================================

from typing import List
from etl.spec import FeatureSpec, Dep

S4_PRESSURE_FEATURES: List[FeatureSpec] = [

    # === derived.roll_sum ===

    FeatureSpec(
        name="net_add_fut_10bps_15s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_add_fut_10bps_1s",
                 "window_s": "15"},
        label="Net Add Fut 10Bps 15S (Binance)",
        group="Pressure",
        description="Rolling sum over 15s (Futures, 10bps).",
        depends_on=(Dep(name="net_add_fut_10bps_1s", kind="col"),),
        feature_id=4200,
    ),

    FeatureSpec(
        name="net_add_fut_10bps_5s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_add_fut_10bps_1s",
                 "window_s": "5"},
        label="Net Add Fut 10Bps 5S (Binance)",
        group="Pressure",
        description="Rolling sum over 5s (Futures, 10bps).",
        depends_on=(Dep(name="net_add_fut_10bps_1s", kind="col"),),
        feature_id=4201,
    ),

    FeatureSpec(
        name="net_add_fut_10bps_60s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_add_fut_10bps_1s",
                 "window_s": "60"},
        label="Net Add Fut 10Bps 60S (Binance)",
        group="Pressure",
        description="Rolling sum over 60s (Futures, 10bps).",
        depends_on=(Dep(name="net_add_fut_10bps_1s", kind="col"),),
        feature_id=4202,
    ),

    FeatureSpec(
        name="net_add_fut_2bps_15s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_add_fut_2bps_1s",
                 "window_s": "15"},
        label="Net Add Fut 2Bps 15S (Binance)",
        group="Pressure",
        description="Rolling sum over 15s (Futures, 2bps).",
        depends_on=(Dep(name="net_add_fut_2bps_1s", kind="col"),),
        feature_id=4203,
    ),

    FeatureSpec(
        name="net_add_fut_2bps_5s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_add_fut_2bps_1s",
                 "window_s": "5"},
        label="Net Add Fut 2Bps 5S (Binance)",
        group="Pressure",
        description="Rolling sum over 5s (Futures, 2bps).",
        depends_on=(Dep(name="net_add_fut_2bps_1s", kind="col"),),
        feature_id=4204,
    ),

    FeatureSpec(
        name="net_add_fut_2bps_60s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_add_fut_2bps_1s",
                 "window_s": "60"},
        label="Net Add Fut 2Bps 60S (Binance)",
        group="Pressure",
        description="Rolling sum over 60s (Futures, 2bps).",
        depends_on=(Dep(name="net_add_fut_2bps_1s", kind="col"),),
        feature_id=4205,
    ),

    FeatureSpec(
        name="net_add_fut_5bps_15s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_add_fut_5bps_1s",
                 "window_s": "15"},
        label="Net Add Fut 5Bps 15S (Binance)",
        group="Pressure",
        description="Rolling sum over 15s (Futures, 5bps).",
        depends_on=(Dep(name="net_add_fut_5bps_1s", kind="col"),),
        feature_id=4206,
    ),

    FeatureSpec(
        name="net_add_fut_5bps_5s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_add_fut_5bps_1s",
                 "window_s": "5"},
        label="Net Add Fut 5Bps 5S (Binance)",
        group="Pressure",
        description="Rolling sum over 5s (Futures, 5bps).",
        depends_on=(Dep(name="net_add_fut_5bps_1s", kind="col"),),
        feature_id=4207,
    ),

    FeatureSpec(
        name="net_add_fut_5bps_60s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_add_fut_5bps_1s",
                 "window_s": "60"},
        label="Net Add Fut 5Bps 60S (Binance)",
        group="Pressure",
        description="Rolling sum over 60s (Futures, 5bps).",
        depends_on=(Dep(name="net_add_fut_5bps_1s", kind="col"),),
        feature_id=4208,
    ),

    FeatureSpec(
        name="net_add_spot_10bps_15s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_add_spot_10bps_1s",
                 "window_s": "15"},
        label="Net Add Spot 10Bps 15S (Binance)",
        group="Pressure",
        description="Rolling sum over 15s (Spot, 10bps).",
        depends_on=(Dep(name="net_add_spot_10bps_1s", kind="col"),),
        feature_id=4209,
    ),

    FeatureSpec(
        name="net_add_spot_10bps_5s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_add_spot_10bps_1s",
                 "window_s": "5"},
        label="Net Add Spot 10Bps 5S (Binance)",
        group="Pressure",
        description="Rolling sum over 5s (Spot, 10bps).",
        depends_on=(Dep(name="net_add_spot_10bps_1s", kind="col"),),
        feature_id=4210,
    ),

    FeatureSpec(
        name="net_add_spot_10bps_60s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_add_spot_10bps_1s",
                 "window_s": "60"},
        label="Net Add Spot 10Bps 60S (Binance)",
        group="Pressure",
        description="Rolling sum over 60s (Spot, 10bps).",
        depends_on=(Dep(name="net_add_spot_10bps_1s", kind="col"),),
        feature_id=4211,
    ),

    FeatureSpec(
        name="net_add_spot_2bps_15s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_add_spot_2bps_1s",
                 "window_s": "15"},
        label="Net Add Spot 2Bps 15S (Binance)",
        group="Pressure",
        description="Rolling sum over 15s (Spot, 2bps).",
        depends_on=(Dep(name="net_add_spot_2bps_1s", kind="col"),),
        feature_id=4212,
    ),

    FeatureSpec(
        name="net_add_spot_2bps_5s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_add_spot_2bps_1s",
                 "window_s": "5"},
        label="Net Add Spot 2Bps 5S (Binance)",
        group="Pressure",
        description="Rolling sum over 5s (Spot, 2bps).",
        depends_on=(Dep(name="net_add_spot_2bps_1s", kind="col"),),
        feature_id=4213,
    ),

    FeatureSpec(
        name="net_add_spot_2bps_60s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_add_spot_2bps_1s",
                 "window_s": "60"},
        label="Net Add Spot 2Bps 60S (Binance)",
        group="Pressure",
        description="Rolling sum over 60s (Spot, 2bps).",
        depends_on=(Dep(name="net_add_spot_2bps_1s", kind="col"),),
        feature_id=4214,
    ),

    FeatureSpec(
        name="net_add_spot_5bps_15s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_add_spot_5bps_1s",
                 "window_s": "15"},
        label="Net Add Spot 5Bps 15S (Binance)",
        group="Pressure",
        description="Rolling sum over 15s (Spot, 5bps).",
        depends_on=(Dep(name="net_add_spot_5bps_1s", kind="col"),),
        feature_id=4215,
    ),

    FeatureSpec(
        name="net_add_spot_5bps_5s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_add_spot_5bps_1s",
                 "window_s": "5"},
        label="Net Add Spot 5Bps 5S (Binance)",
        group="Pressure",
        description="Rolling sum over 5s (Spot, 5bps).",
        depends_on=(Dep(name="net_add_spot_5bps_1s", kind="col"),),
        feature_id=4216,
    ),

    FeatureSpec(
        name="net_add_spot_5bps_60s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_add_spot_5bps_1s",
                 "window_s": "60"},
        label="Net Add Spot 5Bps 60S (Binance)",
        group="Pressure",
        description="Rolling sum over 60s (Spot, 5bps).",
        depends_on=(Dep(name="net_add_spot_5bps_1s", kind="col"),),
        feature_id=4217,
    ),

    FeatureSpec(
        name="net_cancel_fut_10bps_15s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_cancel_fut_10bps_1s",
                 "window_s": "15"},
        label="Net Cancel Fut 10Bps 15S (Binance)",
        group="Pressure",
        description="Rolling sum over 15s (Futures, 10bps).",
        depends_on=(Dep(name="net_cancel_fut_10bps_1s", kind="col"),),
        feature_id=4218,
    ),

    FeatureSpec(
        name="net_cancel_fut_10bps_5s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_cancel_fut_10bps_1s",
                 "window_s": "5"},
        label="Net Cancel Fut 10Bps 5S (Binance)",
        group="Pressure",
        description="Rolling sum over 5s (Futures, 10bps).",
        depends_on=(Dep(name="net_cancel_fut_10bps_1s", kind="col"),),
        feature_id=4219,
    ),

    FeatureSpec(
        name="net_cancel_fut_10bps_60s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_cancel_fut_10bps_1s",
                 "window_s": "60"},
        label="Net Cancel Fut 10Bps 60S (Binance)",
        group="Pressure",
        description="Rolling sum over 60s (Futures, 10bps).",
        depends_on=(Dep(name="net_cancel_fut_10bps_1s", kind="col"),),
        feature_id=4220,
    ),

    FeatureSpec(
        name="net_cancel_fut_2bps_15s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_cancel_fut_2bps_1s",
                 "window_s": "15"},
        label="Net Cancel Fut 2Bps 15S (Binance)",
        group="Pressure",
        description="Rolling sum over 15s (Futures, 2bps).",
        depends_on=(Dep(name="net_cancel_fut_2bps_1s", kind="col"),),
        feature_id=4221,
    ),

    FeatureSpec(
        name="net_cancel_fut_2bps_5s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_cancel_fut_2bps_1s",
                 "window_s": "5"},
        label="Net Cancel Fut 2Bps 5S (Binance)",
        group="Pressure",
        description="Rolling sum over 5s (Futures, 2bps).",
        depends_on=(Dep(name="net_cancel_fut_2bps_1s", kind="col"),),
        feature_id=4222,
    ),

    FeatureSpec(
        name="net_cancel_fut_2bps_60s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_cancel_fut_2bps_1s",
                 "window_s": "60"},
        label="Net Cancel Fut 2Bps 60S (Binance)",
        group="Pressure",
        description="Rolling sum over 60s (Futures, 2bps).",
        depends_on=(Dep(name="net_cancel_fut_2bps_1s", kind="col"),),
        feature_id=4223,
    ),

    FeatureSpec(
        name="net_cancel_fut_5bps_15s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_cancel_fut_5bps_1s",
                 "window_s": "15"},
        label="Net Cancel Fut 5Bps 15S (Binance)",
        group="Pressure",
        description="Rolling sum over 15s (Futures, 5bps).",
        depends_on=(Dep(name="net_cancel_fut_5bps_1s", kind="col"),),
        feature_id=4224,
    ),

    FeatureSpec(
        name="net_cancel_fut_5bps_5s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_cancel_fut_5bps_1s",
                 "window_s": "5"},
        label="Net Cancel Fut 5Bps 5S (Binance)",
        group="Pressure",
        description="Rolling sum over 5s (Futures, 5bps).",
        depends_on=(Dep(name="net_cancel_fut_5bps_1s", kind="col"),),
        feature_id=4225,
    ),

    FeatureSpec(
        name="net_cancel_fut_5bps_60s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Futures",
                 "input_col": "net_cancel_fut_5bps_1s",
                 "window_s": "60"},
        label="Net Cancel Fut 5Bps 60S (Binance)",
        group="Pressure",
        description="Rolling sum over 60s (Futures, 5bps).",
        depends_on=(Dep(name="net_cancel_fut_5bps_1s", kind="col"),),
        feature_id=4226,
    ),

    FeatureSpec(
        name="net_cancel_spot_10bps_15s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_cancel_spot_10bps_1s",
                 "window_s": "15"},
        label="Net Cancel Spot 10Bps 15S (Binance)",
        group="Pressure",
        description="Rolling sum over 15s (Spot, 10bps).",
        depends_on=(Dep(name="net_cancel_spot_10bps_1s", kind="col"),),
        feature_id=4227,
    ),

    FeatureSpec(
        name="net_cancel_spot_10bps_5s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_cancel_spot_10bps_1s",
                 "window_s": "5"},
        label="Net Cancel Spot 10Bps 5S (Binance)",
        group="Pressure",
        description="Rolling sum over 5s (Spot, 10bps).",
        depends_on=(Dep(name="net_cancel_spot_10bps_1s", kind="col"),),
        feature_id=4228,
    ),

    FeatureSpec(
        name="net_cancel_spot_10bps_60s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_cancel_spot_10bps_1s",
                 "window_s": "60"},
        label="Net Cancel Spot 10Bps 60S (Binance)",
        group="Pressure",
        description="Rolling sum over 60s (Spot, 10bps).",
        depends_on=(Dep(name="net_cancel_spot_10bps_1s", kind="col"),),
        feature_id=4229,
    ),

    FeatureSpec(
        name="net_cancel_spot_2bps_15s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_cancel_spot_2bps_1s",
                 "window_s": "15"},
        label="Net Cancel Spot 2Bps 15S (Binance)",
        group="Pressure",
        description="Rolling sum over 15s (Spot, 2bps).",
        depends_on=(Dep(name="net_cancel_spot_2bps_1s", kind="col"),),
        feature_id=4230,
    ),

    FeatureSpec(
        name="net_cancel_spot_2bps_5s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_cancel_spot_2bps_1s",
                 "window_s": "5"},
        label="Net Cancel Spot 2Bps 5S (Binance)",
        group="Pressure",
        description="Rolling sum over 5s (Spot, 2bps).",
        depends_on=(Dep(name="net_cancel_spot_2bps_1s", kind="col"),),
        feature_id=4231,
    ),

    FeatureSpec(
        name="net_cancel_spot_2bps_60s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_cancel_spot_2bps_1s",
                 "window_s": "60"},
        label="Net Cancel Spot 2Bps 60S (Binance)",
        group="Pressure",
        description="Rolling sum over 60s (Spot, 2bps).",
        depends_on=(Dep(name="net_cancel_spot_2bps_1s", kind="col"),),
        feature_id=4232,
    ),

    FeatureSpec(
        name="net_cancel_spot_5bps_15s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_cancel_spot_5bps_1s",
                 "window_s": "15"},
        label="Net Cancel Spot 5Bps 15S (Binance)",
        group="Pressure",
        description="Rolling sum over 15s (Spot, 5bps).",
        depends_on=(Dep(name="net_cancel_spot_5bps_1s", kind="col"),),
        feature_id=4233,
    ),

    FeatureSpec(
        name="net_cancel_spot_5bps_5s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_cancel_spot_5bps_1s",
                 "window_s": "5"},
        label="Net Cancel Spot 5Bps 5S (Binance)",
        group="Pressure",
        description="Rolling sum over 5s (Spot, 5bps).",
        depends_on=(Dep(name="net_cancel_spot_5bps_1s", kind="col"),),
        feature_id=4234,
    ),

    FeatureSpec(
        name="net_cancel_spot_5bps_60s",
        stage="S4",
        operator="derived.roll_sum",
        params={"market_scope": "Spot",
                 "input_col": "net_cancel_spot_5bps_1s",
                 "window_s": "60"},
        label="Net Cancel Spot 5Bps 60S (Binance)",
        group="Pressure",
        description="Rolling sum over 60s (Spot, 5bps).",
        depends_on=(Dep(name="net_cancel_spot_5bps_1s", kind="col"),),
        feature_id=4235,
    ),


    # === derived.logratio ===

    FeatureSpec(
        name="net_pressure_logratio_2bps_5bps_fut_5s",
        stage="S4",
        operator="derived.logratio",
        params={"market_scope": "Futures",
                 "input_col": "net_pressure_logratio_2bps_5bps_fut_1s",
                 "window_s": "5"},
        label="Net Pressure Logratio 2Bps 5Bps Fut 5S (Binance)",
        group="Pressure",
        description="Log-ratio of inner/outer net pressure bands (Futures, 5s).",
        depends_on=(Dep(name="net_pressure_logratio_2bps_5bps_fut_1s", kind="col"),),
        feature_id=4236,
    ),

    FeatureSpec(
        name="net_pressure_logratio_2bps_5bps_spot_5s",
        stage="S4",
        operator="derived.logratio",
        params={"market_scope": "Spot",
                 "input_col": "net_pressure_logratio_2bps_5bps_spot_1s",
                 "window_s": "5"},
        label="Net Pressure Logratio 2Bps 5Bps Spot 5S (Binance)",
        group="Pressure",
        description="Log-ratio of inner/outer net pressure bands (Spot, 5s).",
        depends_on=(Dep(name="net_pressure_logratio_2bps_5bps_spot_1s", kind="col"),),
        feature_id=4237,
    ),

    FeatureSpec(
        name="net_pressure_logratio_5bps_10bps_fut_5s",
        stage="S4",
        operator="derived.logratio",
        params={"market_scope": "Futures",
                 "input_col": "net_pressure_logratio_5bps_10bps_fut_1s",
                 "window_s": "5"},
        label="Net Pressure Logratio 5Bps 10Bps Fut 5S (Binance)",
        group="Pressure",
        description="Log-ratio of inner/outer net pressure bands (Futures, 5s).",
        depends_on=(Dep(name="net_pressure_logratio_5bps_10bps_fut_1s", kind="col"),),
        feature_id=4238,
    ),

    FeatureSpec(
        name="net_pressure_logratio_5bps_10bps_spot_5s",
        stage="S4",
        operator="derived.logratio",
        params={"market_scope": "Spot",
                 "input_col": "net_pressure_logratio_5bps_10bps_spot_1s",
                 "window_s": "5"},
        label="Net Pressure Logratio 5Bps 10Bps Spot 5S (Binance)",
        group="Pressure",
        description="Log-ratio of inner/outer net pressure bands (Spot, 5s).",
        depends_on=(Dep(name="net_pressure_logratio_5bps_10bps_spot_1s", kind="col"),),
        feature_id=4239,
    ),


    # === derived.pct_rank ===

    FeatureSpec(
        name="net_pressure_pct_rank_fut_2bps_15s",
        stage="S4",
        operator="derived.pct_rank",
        params={"market_scope": "Futures",
                 "input_col": "net_pressure_fut_2bps_15s",
                 "window_s": "15"},
        label="Net Pressure Pct Rank Fut 2Bps 15S (Binance)",
        group="Pressure",
        description="Rolling percentile rank of net pressure (Futures, 2bps, 15s).",
        depends_on=(Dep(name="net_pressure_fut_2bps_15s", kind="col"),),
        feature_id=4240,
    ),

    FeatureSpec(
        name="net_pressure_pct_rank_fut_2bps_5s",
        stage="S4",
        operator="derived.pct_rank",
        params={"market_scope": "Futures",
                 "input_col": "net_pressure_fut_2bps_5s",
                 "window_s": "5"},
        label="Net Pressure Pct Rank Fut 2Bps 5S (Binance)",
        group="Pressure",
        description="Rolling percentile rank of net pressure (Futures, 2bps, 5s).",
        depends_on=(Dep(name="net_pressure_fut_2bps_5s", kind="col"),),
        feature_id=4241,
    ),

    FeatureSpec(
        name="net_pressure_pct_rank_fut_2bps_60s",
        stage="S4",
        operator="derived.pct_rank",
        params={"market_scope": "Futures",
                 "input_col": "net_pressure_fut_2bps_60s",
                 "window_s": "60"},
        label="Net Pressure Pct Rank Fut 2Bps 60S (Binance)",
        group="Pressure",
        description="Rolling percentile rank of net pressure (Futures, 2bps, 60s).",
        depends_on=(Dep(name="net_pressure_fut_2bps_60s", kind="col"),),
        feature_id=4242,
    ),

    FeatureSpec(
        name="net_pressure_pct_rank_fut_5bps_15s",
        stage="S4",
        operator="derived.pct_rank",
        params={"market_scope": "Futures",
                 "input_col": "net_pressure_fut_5bps_15s",
                 "window_s": "15"},
        label="Net Pressure Pct Rank Fut 5Bps 15S (Binance)",
        group="Pressure",
        description="Rolling percentile rank of net pressure (Futures, 5bps, 15s).",
        depends_on=(Dep(name="net_pressure_fut_5bps_15s", kind="col"),),
        feature_id=4243,
    ),

    FeatureSpec(
        name="net_pressure_pct_rank_fut_5bps_5s",
        stage="S4",
        operator="derived.pct_rank",
        params={"market_scope": "Futures",
                 "input_col": "net_pressure_fut_5bps_5s",
                 "window_s": "5"},
        label="Net Pressure Pct Rank Fut 5Bps 5S (Binance)",
        group="Pressure",
        description="Rolling percentile rank of net pressure (Futures, 5bps, 5s).",
        depends_on=(Dep(name="net_pressure_fut_5bps_5s", kind="col"),),
        feature_id=4244,
    ),

    FeatureSpec(
        name="net_pressure_pct_rank_fut_5bps_60s",
        stage="S4",
        operator="derived.pct_rank",
        params={"market_scope": "Futures",
                 "input_col": "net_pressure_fut_5bps_60s",
                 "window_s": "60"},
        label="Net Pressure Pct Rank Fut 5Bps 60S (Binance)",
        group="Pressure",
        description="Rolling percentile rank of net pressure (Futures, 5bps, 60s).",
        depends_on=(Dep(name="net_pressure_fut_5bps_60s", kind="col"),),
        feature_id=4245,
    ),


    # === derived.robust_zscore ===

    FeatureSpec(
        name="net_pressure_robust_z_fut_10bps_300s",
        stage="S4",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures",
                 "input_col": "net_add_pressure_fut_10bps_300s",
                 "window_s": "300"},
        label="Net Pressure Robust Z Fut 10Bps 300S (Binance)",
        group="Pressure",
        description="Robust z-score (median/MAD) of net_pressure_robust_z_fut_10bps_300s.",
        depends_on=(Dep(name="net_add_pressure_fut_10bps_300s", kind="col"),),
        feature_id=4246,
    ),

    FeatureSpec(
        name="net_pressure_robust_z_fut_10bps_60s",
        stage="S4",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures",
                 "input_col": "net_add_pressure_fut_10bps_60s",
                 "window_s": "60"},
        label="Net Pressure Robust Z Fut 10Bps 60S (Binance)",
        group="Pressure",
        description="Robust z-score (median/MAD) of net_pressure_robust_z_fut_10bps_60s.",
        depends_on=(Dep(name="net_add_pressure_fut_10bps_60s", kind="col"),),
        feature_id=4247,
    ),

    FeatureSpec(
        name="net_pressure_robust_z_fut_5bps_300s",
        stage="S4",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures",
                 "input_col": "net_add_pressure_fut_5bps_300s",
                 "window_s": "300"},
        label="Net Pressure Robust Z Fut 5Bps 300S (Binance)",
        group="Pressure",
        description="Robust z-score (median/MAD) of net_pressure_robust_z_fut_5bps_300s.",
        depends_on=(Dep(name="net_add_pressure_fut_5bps_300s", kind="col"),),
        feature_id=4248,
    ),

    FeatureSpec(
        name="net_pressure_robust_z_fut_5bps_60s",
        stage="S4",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures",
                 "input_col": "net_add_pressure_fut_5bps_60s",
                 "window_s": "60"},
        label="Net Pressure Robust Z Fut 5Bps 60S (Binance)",
        group="Pressure",
        description="Robust z-score (median/MAD) of net_pressure_robust_z_fut_5bps_60s.",
        depends_on=(Dep(name="net_add_pressure_fut_5bps_60s", kind="col"),),
        feature_id=4249,
    ),

    FeatureSpec(
        name="net_pressure_robust_z_spot_10bps_300s",
        stage="S4",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot",
                 "input_col": "net_add_pressure_spot_10bps_300s",
                 "window_s": "300"},
        label="Net Pressure Robust Z Spot 10Bps 300S (Binance)",
        group="Pressure",
        description="Robust z-score (median/MAD) of net_pressure_robust_z_spot_10bps_300s.",
        depends_on=(Dep(name="net_add_pressure_spot_10bps_300s", kind="col"),),
        feature_id=4250,
    ),

    FeatureSpec(
        name="net_pressure_robust_z_spot_10bps_60s",
        stage="S4",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot",
                 "input_col": "net_add_pressure_spot_10bps_60s",
                 "window_s": "60"},
        label="Net Pressure Robust Z Spot 10Bps 60S (Binance)",
        group="Pressure",
        description="Robust z-score (median/MAD) of net_pressure_robust_z_spot_10bps_60s.",
        depends_on=(Dep(name="net_add_pressure_spot_10bps_60s", kind="col"),),
        feature_id=4251,
    ),

    FeatureSpec(
        name="net_pressure_robust_z_spot_5bps_300s",
        stage="S4",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot",
                 "input_col": "net_add_pressure_spot_5bps_300s",
                 "window_s": "300"},
        label="Net Pressure Robust Z Spot 5Bps 300S (Binance)",
        group="Pressure",
        description="Robust z-score (median/MAD) of net_pressure_robust_z_spot_5bps_300s.",
        depends_on=(Dep(name="net_add_pressure_spot_5bps_300s", kind="col"),),
        feature_id=4252,
    ),

    FeatureSpec(
        name="net_pressure_robust_z_spot_5bps_60s",
        stage="S4",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot",
                 "input_col": "net_add_pressure_spot_5bps_60s",
                 "window_s": "60"},
        label="Net Pressure Robust Z Spot 5Bps 60S (Binance)",
        group="Pressure",
        description="Robust z-score (median/MAD) of net_pressure_robust_z_spot_5bps_60s.",
        depends_on=(Dep(name="net_add_pressure_spot_5bps_60s", kind="col"),),
        feature_id=4253,
    ),

]