# etl/spec/s3/s3_dynamics.py
# ========================================================================
# S3 Dynamics Features
# Temporal dynamics and statistical regime features that capture rate-of-change,
# acceleration, persistence, and shock behavior of key microstructure signals.
#
# Key concepts:
#   - d1_* (first derivative): Rate of change of rolling signals.
#   - d2_* (second derivative): Acceleration of rate of change.
#   - median_* / mad_*: Rolling robust statistics. Foundation for shock detection.
#   - *_shock_*: Robust z-score shocks: (value - median) / (1.4826*MAD + eps).
#   - *_persist_*: Sign persistence — fraction of sub-buckets with same sign.
#   - net_pressure_flip_rate / net_pressure_persist: Order flow decisiveness.
#   - impact_per_signed_persist / impact_per_signed_shock: Price impact analytics.
#   - dir_consistency_persist: Cross-timeframe direction consistency.
#
# Dependencies: S2 pull_rate, refill_rate, queue_pressure, taker_imbalance,
#               impact_per_signed, net_add_pressure, dir_consistency, refill_vs_pull.
#
#   for 1bps/2bps bands (pull_rate, refill_rate, queue_pressure).
#   Root cause: sparse thin bands → MAD≈0 → shock always NaN.
#   Only 5bps+ bands retained for shock detection.
#   persist/d1/d2 features for 1bps/2bps are KEPT (no MAD dependency).
#
# Feature count: 101  (was 103; removed 2 × 3600s features)
# [FIX-3600] Removed all window_s=3600 features (impact_per_signed _persist_3600s).
#            3600s rolling windows require 1h prior data even with context;
#            produce 99-100% NaN on 1h Parquet files. The 900s variants
#            provide equivalent microstructure regime coverage.  (was 157)
# Feature ID range: see individual entries
# ========================================================================

from typing import List
from etl.spec import FeatureSpec, Dep

S3_DYNAMICS_FEATURES: List[FeatureSpec] = [

    # ── d1: first temporal derivatives ───────────────────────────────────────

    FeatureSpec(
        name="d1_pull_rate_fut_1bps_15s",
        stage="S3",
        operator="s3.temporal_d1",
        params={"market_scope": "Futures"},
        label="Dynamics: d1_pull_rate_fut_1bps_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="First temporal derivative of pull_rate_fut_1bps_15s.",
        depends_on=(Dep(name="pull_rate_fut_1bps_15s", kind="col"),),
        feature_id=3069,
    ),
    FeatureSpec(
        name="d1_pull_rate_fut_2bps_15s",
        stage="S3",
        operator="s3.temporal_d1",
        params={"market_scope": "Futures"},
        label="Dynamics: d1_pull_rate_fut_2bps_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="First temporal derivative of pull_rate_fut_2bps_15s.",
        depends_on=(Dep(name="pull_rate_fut_2bps_15s", kind="col"),),
        feature_id=3070,
    ),
    FeatureSpec(
        name="d1_pull_rate_spot_1bps_15s",
        stage="S3",
        operator="s3.temporal_d1",
        params={"market_scope": "Spot"},
        label="Dynamics: d1_pull_rate_spot_1bps_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="First temporal derivative of pull_rate_spot_1bps_15s.",
        depends_on=(Dep(name="pull_rate_spot_1bps_15s", kind="col"),),
        feature_id=3071,
    ),
    FeatureSpec(
        name="d1_pull_rate_spot_2bps_15s",
        stage="S3",
        operator="s3.temporal_d1",
        params={"market_scope": "Spot"},
        label="Dynamics: d1_pull_rate_spot_2bps_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="First temporal derivative of pull_rate_spot_2bps_15s.",
        depends_on=(Dep(name="pull_rate_spot_2bps_15s", kind="col"),),
        feature_id=3072,
    ),
    FeatureSpec(
        name="d1_queue_pressure_fut_1bps_15s",
        stage="S3",
        operator="s3.temporal_d1",
        params={"market_scope": "Futures"},
        label="Dynamics: d1_queue_pressure_fut_1bps_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="First temporal derivative of queue_pressure_fut_1bps_15s.",
        depends_on=(Dep(name="queue_pressure_fut_1bps_15s", kind="col"),),
        feature_id=3073,
    ),
    FeatureSpec(
        name="d1_queue_pressure_spot_1bps_15s",
        stage="S3",
        operator="s3.temporal_d1",
        params={"market_scope": "Spot"},
        label="Dynamics: d1_queue_pressure_spot_1bps_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="First temporal derivative of queue_pressure_spot_1bps_15s.",
        depends_on=(Dep(name="queue_pressure_spot_1bps_15s", kind="col"),),
        feature_id=3074,
    ),
    FeatureSpec(
        name="d1_refill_rate_fut_1bps_15s",
        stage="S3",
        operator="s3.temporal_d1",
        params={"market_scope": "Futures"},
        label="Dynamics: d1_refill_rate_fut_1bps_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="First temporal derivative of refill_rate_fut_1bps_15s.",
        depends_on=(Dep(name="refill_rate_fut_1bps_15s", kind="col"),),
        feature_id=3075,
    ),
    FeatureSpec(
        name="d1_refill_rate_fut_1bps_5s",
        stage="S3",
        operator="s3.temporal_d1",
        params={"market_scope": "Futures"},
        label="Dynamics: d1_refill_rate_fut_1bps_5s (Futures) [5s] (Binance)",
        group="Dynamics",
        description="First temporal derivative of refill_rate_fut_1bps_5s.",
        depends_on=(Dep(name="refill_rate_fut_1bps_5s", kind="col"),),
        feature_id=3076,
    ),
    FeatureSpec(
        name="d1_refill_rate_fut_2bps_15s",
        stage="S3",
        operator="s3.temporal_d1",
        params={"market_scope": "Futures"},
        label="Dynamics: d1_refill_rate_fut_2bps_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="First temporal derivative of refill_rate_fut_2bps_15s.",
        depends_on=(Dep(name="refill_rate_fut_2bps_15s", kind="col"),),
        feature_id=3077,
    ),
    FeatureSpec(
        name="d1_refill_rate_spot_1bps_15s",
        stage="S3",
        operator="s3.temporal_d1",
        params={"market_scope": "Spot"},
        label="Dynamics: d1_refill_rate_spot_1bps_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="First temporal derivative of refill_rate_spot_1bps_15s.",
        depends_on=(Dep(name="refill_rate_spot_1bps_15s", kind="col"),),
        feature_id=3078,
    ),
    FeatureSpec(
        name="d1_refill_rate_spot_1bps_5s",
        stage="S3",
        operator="s3.temporal_d1",
        params={"market_scope": "Spot"},
        label="Dynamics: d1_refill_rate_spot_1bps_5s (Spot) [5s] (Binance)",
        group="Dynamics",
        description="First temporal derivative of refill_rate_spot_1bps_5s.",
        depends_on=(Dep(name="refill_rate_spot_1bps_5s", kind="col"),),
        feature_id=3079,
    ),
    FeatureSpec(
        name="d1_refill_rate_spot_2bps_15s",
        stage="S3",
        operator="s3.temporal_d1",
        params={"market_scope": "Spot"},
        label="Dynamics: d1_refill_rate_spot_2bps_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="First temporal derivative of refill_rate_spot_2bps_15s.",
        depends_on=(Dep(name="refill_rate_spot_2bps_15s", kind="col"),),
        feature_id=3080,
    ),
    FeatureSpec(
        name="d1_taker_imbalance_fut_15s",
        stage="S3",
        operator="s3.temporal_d1",
        params={"market_scope": "Futures"},
        label="Dynamics: d1_taker_imbalance_fut_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="First temporal derivative of taker_imbalance_fut_15s.",
        depends_on=(Dep(name="taker_imbalance_fut_15s", kind="col"),),
        feature_id=3081,
    ),
    FeatureSpec(
        name="d1_taker_imbalance_fut_5s",
        stage="S3",
        operator="s3.temporal_d1",
        params={"market_scope": "Futures"},
        label="Dynamics: d1_taker_imbalance_fut_5s (Futures) [5s] (Binance)",
        group="Dynamics",
        description="First temporal derivative of taker_imbalance_fut_5s.",
        depends_on=(Dep(name="taker_imbalance_fut_5s", kind="col"),),
        feature_id=3082,
    ),
    FeatureSpec(
        name="d1_taker_imbalance_spot_15s",
        stage="S3",
        operator="s3.temporal_d1",
        params={"market_scope": "Spot"},
        label="Dynamics: d1_taker_imbalance_spot_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="First temporal derivative of taker_imbalance_spot_15s.",
        depends_on=(Dep(name="taker_imbalance_spot_15s", kind="col"),),
        feature_id=3083,
    ),
    FeatureSpec(
        name="d1_taker_imbalance_spot_5s",
        stage="S3",
        operator="s3.temporal_d1",
        params={"market_scope": "Spot"},
        label="Dynamics: d1_taker_imbalance_spot_5s (Spot) [5s] (Binance)",
        group="Dynamics",
        description="First temporal derivative of taker_imbalance_spot_5s.",
        depends_on=(Dep(name="taker_imbalance_spot_5s", kind="col"),),
        feature_id=3084,
    ),

    # ── d2: second temporal derivatives ──────────────────────────────────────

    FeatureSpec(
        name="d2_pull_rate_fut_1bps_15s",
        stage="S3",
        operator="s3.temporal_d2",
        params={"market_scope": "Futures"},
        label="Dynamics: d2_pull_rate_fut_1bps_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Second temporal derivative: d1(d1_pull_rate_fut_1bps_15s) - d1(d1_pull_rate_fut_1bps_15s).shift(1).",
        depends_on=(
            Dep(name="d1_pull_rate_fut_1bps_15s", kind="col"),
            Dep(name="pull_rate_fut_1bps_15s", kind="col"),
        ),
        feature_id=3085,
    ),
    FeatureSpec(
        name="d2_pull_rate_fut_2bps_15s",
        stage="S3",
        operator="s3.temporal_d2",
        params={"market_scope": "Futures"},
        label="Dynamics: d2_pull_rate_fut_2bps_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Second temporal derivative: d1(d1_pull_rate_fut_2bps_15s) - d1(d1_pull_rate_fut_2bps_15s).shift(1).",
        depends_on=(
            Dep(name="d1_pull_rate_fut_2bps_15s", kind="col"),
            Dep(name="pull_rate_fut_2bps_15s", kind="col"),
        ),
        feature_id=3086,
    ),
    FeatureSpec(
        name="d2_pull_rate_spot_1bps_15s",
        stage="S3",
        operator="s3.temporal_d2",
        params={"market_scope": "Spot"},
        label="Dynamics: d2_pull_rate_spot_1bps_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Second temporal derivative: d1(d1_pull_rate_spot_1bps_15s) - d1(d1_pull_rate_spot_1bps_15s).shift(1).",
        depends_on=(
            Dep(name="d1_pull_rate_spot_1bps_15s", kind="col"),
            Dep(name="pull_rate_spot_1bps_15s", kind="col"),
        ),
        feature_id=3087,
    ),
    FeatureSpec(
        name="d2_pull_rate_spot_2bps_15s",
        stage="S3",
        operator="s3.temporal_d2",
        params={"market_scope": "Spot"},
        label="Dynamics: d2_pull_rate_spot_2bps_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Second temporal derivative: d1(d1_pull_rate_spot_2bps_15s) - d1(d1_pull_rate_spot_2bps_15s).shift(1).",
        depends_on=(
            Dep(name="d1_pull_rate_spot_2bps_15s", kind="col"),
            Dep(name="pull_rate_spot_2bps_15s", kind="col"),
        ),
        feature_id=3088,
    ),
    FeatureSpec(
        name="d2_queue_pressure_fut_1bps_15s",
        stage="S3",
        operator="s3.temporal_d2",
        params={"market_scope": "Futures"},
        label="Dynamics: d2_queue_pressure_fut_1bps_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Second temporal derivative: d1(d1_queue_pressure_fut_1bps_15s) - d1(d1_queue_pressure_fut_1bps_15s).shift(1).",
        depends_on=(
            Dep(name="d1_queue_pressure_fut_1bps_15s", kind="col"),
            Dep(name="queue_pressure_fut_1bps_15s", kind="col"),
        ),
        feature_id=3089,
    ),
    FeatureSpec(
        name="d2_queue_pressure_spot_1bps_15s",
        stage="S3",
        operator="s3.temporal_d2",
        params={"market_scope": "Spot"},
        label="Dynamics: d2_queue_pressure_spot_1bps_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Second temporal derivative: d1(d1_queue_pressure_spot_1bps_15s) - d1(d1_queue_pressure_spot_1bps_15s).shift(1).",
        depends_on=(
            Dep(name="d1_queue_pressure_spot_1bps_15s", kind="col"),
            Dep(name="queue_pressure_spot_1bps_15s", kind="col"),
        ),
        feature_id=3090,
    ),
    FeatureSpec(
        name="d2_refill_rate_fut_1bps_15s",
        stage="S3",
        operator="s3.temporal_d2",
        params={"market_scope": "Futures"},
        label="Dynamics: d2_refill_rate_fut_1bps_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Second temporal derivative: d1(d1_refill_rate_fut_1bps_15s) - d1(d1_refill_rate_fut_1bps_15s).shift(1).",
        depends_on=(
            Dep(name="d1_refill_rate_fut_1bps_15s", kind="col"),
            Dep(name="refill_rate_fut_1bps_15s", kind="col"),
        ),
        feature_id=3091,
    ),
    FeatureSpec(
        name="d2_refill_rate_fut_1bps_5s",
        stage="S3",
        operator="s3.temporal_d2",
        params={"market_scope": "Futures"},
        label="Dynamics: d2_refill_rate_fut_1bps_5s (Futures) [5s] (Binance)",
        group="Dynamics",
        description="Second temporal derivative: d1(d1_refill_rate_fut_1bps_5s) - d1(d1_refill_rate_fut_1bps_5s).shift(1).",
        depends_on=(
            Dep(name="d1_refill_rate_fut_1bps_5s", kind="col"),
            Dep(name="refill_rate_fut_1bps_5s", kind="col"),
        ),
        feature_id=3092,
    ),
    FeatureSpec(
        name="d2_refill_rate_fut_2bps_15s",
        stage="S3",
        operator="s3.temporal_d2",
        params={"market_scope": "Futures"},
        label="Dynamics: d2_refill_rate_fut_2bps_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Second temporal derivative: d1(d1_refill_rate_fut_2bps_15s) - d1(d1_refill_rate_fut_2bps_15s).shift(1).",
        depends_on=(
            Dep(name="d1_refill_rate_fut_2bps_15s", kind="col"),
            Dep(name="refill_rate_fut_2bps_15s", kind="col"),
        ),
        feature_id=3093,
    ),
    FeatureSpec(
        name="d2_refill_rate_spot_1bps_15s",
        stage="S3",
        operator="s3.temporal_d2",
        params={"market_scope": "Spot"},
        label="Dynamics: d2_refill_rate_spot_1bps_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Second temporal derivative: d1(d1_refill_rate_spot_1bps_15s) - d1(d1_refill_rate_spot_1bps_15s).shift(1).",
        depends_on=(
            Dep(name="d1_refill_rate_spot_1bps_15s", kind="col"),
            Dep(name="refill_rate_spot_1bps_15s", kind="col"),
        ),
        feature_id=3094,
    ),
    FeatureSpec(
        name="d2_refill_rate_spot_1bps_5s",
        stage="S3",
        operator="s3.temporal_d2",
        params={"market_scope": "Spot"},
        label="Dynamics: d2_refill_rate_spot_1bps_5s (Spot) [5s] (Binance)",
        group="Dynamics",
        description="Second temporal derivative: d1(d1_refill_rate_spot_1bps_5s) - d1(d1_refill_rate_spot_1bps_5s).shift(1).",
        depends_on=(
            Dep(name="d1_refill_rate_spot_1bps_5s", kind="col"),
            Dep(name="refill_rate_spot_1bps_5s", kind="col"),
        ),
        feature_id=3095,
    ),
    FeatureSpec(
        name="d2_refill_rate_spot_2bps_15s",
        stage="S3",
        operator="s3.temporal_d2",
        params={"market_scope": "Spot"},
        label="Dynamics: d2_refill_rate_spot_2bps_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Second temporal derivative: d1(d1_refill_rate_spot_2bps_15s) - d1(d1_refill_rate_spot_2bps_15s).shift(1).",
        depends_on=(
            Dep(name="d1_refill_rate_spot_2bps_15s", kind="col"),
            Dep(name="refill_rate_spot_2bps_15s", kind="col"),
        ),
        feature_id=3096,
    ),
    FeatureSpec(
        name="d2_taker_imbalance_fut_15s",
        stage="S3",
        operator="s3.temporal_d2",
        params={"market_scope": "Futures"},
        label="Dynamics: d2_taker_imbalance_fut_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Second temporal derivative: d1(d1_taker_imbalance_fut_15s) - d1(d1_taker_imbalance_fut_15s).shift(1).",
        depends_on=(
            Dep(name="d1_taker_imbalance_fut_15s", kind="col"),
            Dep(name="taker_imbalance_fut_15s", kind="col"),
        ),
        feature_id=3097,
    ),
    FeatureSpec(
        name="d2_taker_imbalance_fut_5s",
        stage="S3",
        operator="s3.temporal_d2",
        params={"market_scope": "Futures"},
        label="Dynamics: d2_taker_imbalance_fut_5s (Futures) [5s] (Binance)",
        group="Dynamics",
        description="Second temporal derivative: d1(d1_taker_imbalance_fut_5s) - d1(d1_taker_imbalance_fut_5s).shift(1).",
        depends_on=(
            Dep(name="d1_taker_imbalance_fut_5s", kind="col"),
            Dep(name="taker_imbalance_fut_5s", kind="col"),
        ),
        feature_id=3098,
    ),
    FeatureSpec(
        name="d2_taker_imbalance_spot_15s",
        stage="S3",
        operator="s3.temporal_d2",
        params={"market_scope": "Spot"},
        label="Dynamics: d2_taker_imbalance_spot_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Second temporal derivative: d1(d1_taker_imbalance_spot_15s) - d1(d1_taker_imbalance_spot_15s).shift(1).",
        depends_on=(
            Dep(name="d1_taker_imbalance_spot_15s", kind="col"),
            Dep(name="taker_imbalance_spot_15s", kind="col"),
        ),
        feature_id=3099,
    ),
    FeatureSpec(
        name="d2_taker_imbalance_spot_5s",
        stage="S3",
        operator="s3.temporal_d2",
        params={"market_scope": "Spot"},
        label="Dynamics: d2_taker_imbalance_spot_5s (Spot) [5s] (Binance)",
        group="Dynamics",
        description="Second temporal derivative: d1(d1_taker_imbalance_spot_5s) - d1(d1_taker_imbalance_spot_5s).shift(1).",
        depends_on=(
            Dep(name="d1_taker_imbalance_spot_5s", kind="col"),
            Dep(name="taker_imbalance_spot_5s", kind="col"),
        ),
        feature_id=3100,
    ),

    # ── dir_consistency ───────────────────────────────────────────────────────

    FeatureSpec(
        name="dir_consistency_persist_spot_60_over_900",
        stage="S3",
        operator="s3.dir_consistency_persist",
        params={"market_scope": "Spot"},
        label="Dynamics: dir_consistency_persist_spot_60_over_900 (Spot) [900s] (Binance)",
        group="Dynamics",
        description="Direction consistency persistence across timeframes: dir_consistency_spot_60s vs dir_consistency_spot_900s.",
        depends_on=(
            Dep(name="dir_consistency_spot_60s", kind="col"),
            Dep(name="dir_consistency_spot_900s", kind="col"),
        ),
        feature_id=3101,
    ),

    # ── impact_per_signed: persist ────────────────────────────────────────────

    FeatureSpec(
        name="impact_per_signed_fut_persist_60s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Dynamics: impact_per_signed_fut_persist_60s (Futures) [60s] (Binance)",
        group="Dynamics",
        description="Sign persistence of impact_per_signed_fut_60s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="impact_per_signed_fut_60s", kind="col"),),
        feature_id=3102,
    ),
    FeatureSpec(
        name="impact_per_signed_fut_persist_900s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Futures", "window_s": "900"},
        label="Dynamics: impact_per_signed_fut_persist_900s (Futures) [900s] (Binance)",
        group="Dynamics",
        description="Sign persistence of impact_per_signed_fut_900s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="impact_per_signed_fut_900s", kind="col"),),
        feature_id=3103,
    ),

    # ── impact_per_signed: shock ──────────────────────────────────────────────

    FeatureSpec(
        name="impact_per_signed_shock_fut_15s",
        stage="S3",
        operator="s3.shock",
        params={"market_scope": "Futures"},
        label="Dynamics: impact_per_signed_shock_fut_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Shock score: (impact - median) / (MAD * 1.4826 + eps).",
        depends_on=(
            Dep(name="impact_per_signed_fut_15s", kind="col"),
            Dep(name="mad_impact_per_signed_fut_15s", kind="col"),
            Dep(name="median_impact_per_signed_fut_15s", kind="col"),
        ),
        feature_id=3104,
    ),
    FeatureSpec(
        name="impact_per_signed_shock_fut_5s",
        stage="S3",
        operator="s3.shock",
        params={"market_scope": "Futures"},
        label="Dynamics: impact_per_signed_shock_fut_5s (Futures) [5s] (Binance)",
        group="Dynamics",
        description="Shock score: (impact - median) / (MAD * 1.4826 + eps).",
        depends_on=(
            Dep(name="impact_per_signed_fut_5s", kind="col"),
            Dep(name="mad_impact_per_signed_fut_5s", kind="col"),
            Dep(name="median_impact_per_signed_fut_5s", kind="col"),
        ),
        feature_id=3105,
    ),
    FeatureSpec(
        name="impact_per_signed_shock_fut_60s",
        stage="S3",
        operator="s3.shock",
        params={"market_scope": "Futures"},
        label="Dynamics: impact_per_signed_shock_fut_60s (Futures) [60s] (Binance)",
        group="Dynamics",
        description="Shock score: (impact - median) / (MAD * 1.4826 + eps).",
        depends_on=(
            Dep(name="impact_per_signed_fut_60s", kind="col"),
            Dep(name="mad_impact_per_signed_fut_60s", kind="col"),
            Dep(name="median_impact_per_signed_fut_60s", kind="col"),
        ),
        feature_id=3106,
    ),
    FeatureSpec(
        name="impact_per_signed_shock_spot_15s",
        stage="S3",
        operator="s3.shock",
        params={"market_scope": "Spot"},
        label="Dynamics: impact_per_signed_shock_spot_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Shock score: (impact - median) / (MAD * 1.4826 + eps).",
        depends_on=(
            Dep(name="impact_per_signed_spot_15s", kind="col"),
            Dep(name="mad_impact_per_signed_spot_15s", kind="col"),
            Dep(name="median_impact_per_signed_spot_15s", kind="col"),
        ),
        feature_id=3107,
    ),
    FeatureSpec(
        name="impact_per_signed_shock_spot_5s",
        stage="S3",
        operator="s3.shock",
        params={"market_scope": "Spot"},
        label="Dynamics: impact_per_signed_shock_spot_5s (Spot) [5s] (Binance)",
        group="Dynamics",
        description="Shock score: (impact - median) / (MAD * 1.4826 + eps).",
        depends_on=(
            Dep(name="impact_per_signed_spot_5s", kind="col"),
            Dep(name="mad_impact_per_signed_spot_5s", kind="col"),
            Dep(name="median_impact_per_signed_spot_5s", kind="col"),
        ),
        feature_id=3108,
    ),
    FeatureSpec(
        name="impact_per_signed_shock_spot_60s",
        stage="S3",
        operator="s3.shock",
        params={"market_scope": "Spot"},
        label="Dynamics: impact_per_signed_shock_spot_60s (Spot) [60s] (Binance)",
        group="Dynamics",
        description="Shock score: (impact - median) / (MAD * 1.4826 + eps).",
        depends_on=(
            Dep(name="impact_per_signed_spot_60s", kind="col"),
            Dep(name="mad_impact_per_signed_spot_60s", kind="col"),
            Dep(name="median_impact_per_signed_spot_60s", kind="col"),
        ),
        feature_id=3109,
    ),

    # ── impact_per_signed: spot persist ──────────────────────────────────────

    FeatureSpec(
        name="impact_per_signed_spot_persist_60s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Dynamics: impact_per_signed_spot_persist_60s (Spot) [60s] (Binance)",
        group="Dynamics",
        description="Sign persistence of impact_per_signed_spot_60s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="impact_per_signed_spot_60s", kind="col"),),
        feature_id=3110,
    ),
    FeatureSpec(
        name="impact_per_signed_spot_persist_900s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Spot", "window_s": "900"},
        label="Dynamics: impact_per_signed_spot_persist_900s (Spot) [900s] (Binance)",
        group="Dynamics",
        description="Sign persistence of impact_per_signed_spot_900s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="impact_per_signed_spot_900s", kind="col"),),
        feature_id=3111,
    ),

    # ── mad_impact_per_signed (kept — used by impact_per_signed shocks) ───────

    FeatureSpec(
        name="mad_impact_per_signed_fut_15s",
        stage="S3",
        operator="s3.roll_mad",
        params={"market_scope": "Futures"},
        label="Dynamics: mad_impact_per_signed_fut_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Rolling MAD of impact_per_signed_fut_15s around its median.",
        depends_on=(
            Dep(name="impact_per_signed_fut_15s", kind="col"),
            Dep(name="median_impact_per_signed_fut_15s", kind="col"),
        ),
        feature_id=3112,
    ),
    FeatureSpec(
        name="mad_impact_per_signed_fut_5s",
        stage="S3",
        operator="s3.roll_mad",
        params={"market_scope": "Futures"},
        label="Dynamics: mad_impact_per_signed_fut_5s (Futures) [5s] (Binance)",
        group="Dynamics",
        description="Rolling MAD of impact_per_signed_fut_5s around its median.",
        depends_on=(
            Dep(name="impact_per_signed_fut_5s", kind="col"),
            Dep(name="median_impact_per_signed_fut_5s", kind="col"),
        ),
        feature_id=3113,
    ),
    FeatureSpec(
        name="mad_impact_per_signed_fut_60s",
        stage="S3",
        operator="s3.roll_mad",
        params={"market_scope": "Futures"},
        label="Dynamics: mad_impact_per_signed_fut_60s (Futures) [60s] (Binance)",
        group="Dynamics",
        description="Rolling MAD of impact_per_signed_fut_60s around its median.",
        depends_on=(
            Dep(name="impact_per_signed_fut_60s", kind="col"),
            Dep(name="median_impact_per_signed_fut_60s", kind="col"),
        ),
        feature_id=3114,
    ),
    FeatureSpec(
        name="mad_impact_per_signed_spot_15s",
        stage="S3",
        operator="s3.roll_mad",
        params={"market_scope": "Spot"},
        label="Dynamics: mad_impact_per_signed_spot_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Rolling MAD of impact_per_signed_spot_15s around its median.",
        depends_on=(
            Dep(name="impact_per_signed_spot_15s", kind="col"),
            Dep(name="median_impact_per_signed_spot_15s", kind="col"),
        ),
        feature_id=3115,
    ),
    FeatureSpec(
        name="mad_impact_per_signed_spot_5s",
        stage="S3",
        operator="s3.roll_mad",
        params={"market_scope": "Spot"},
        label="Dynamics: mad_impact_per_signed_spot_5s (Spot) [5s] (Binance)",
        group="Dynamics",
        description="Rolling MAD of impact_per_signed_spot_5s around its median.",
        depends_on=(
            Dep(name="impact_per_signed_spot_5s", kind="col"),
            Dep(name="median_impact_per_signed_spot_5s", kind="col"),
        ),
        feature_id=3116,
    ),
    FeatureSpec(
        name="mad_impact_per_signed_spot_60s",
        stage="S3",
        operator="s3.roll_mad",
        params={"market_scope": "Spot"},
        label="Dynamics: mad_impact_per_signed_spot_60s (Spot) [60s] (Binance)",
        group="Dynamics",
        description="Rolling MAD of impact_per_signed_spot_60s around its median.",
        depends_on=(
            Dep(name="impact_per_signed_spot_60s", kind="col"),
            Dep(name="median_impact_per_signed_spot_60s", kind="col"),
        ),
        feature_id=3117,
    ),

    # ── mad_taker_imbalance (kept — used by taker_imbalance shocks) ───────────

    FeatureSpec(
        name="mad_taker_imbalance_fut_15s",
        stage="S3",
        operator="s3.roll_mad",
        params={"market_scope": "Futures"},
        label="Dynamics: mad_taker_imbalance_fut_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Rolling MAD of median_taker_imbalance_fut_15s around its median.",
        depends_on=(
            Dep(name="median_taker_imbalance_fut_15s", kind="col"),
            Dep(name="taker_imbalance_fut_15s", kind="col"),
        ),
        feature_id=3118,
    ),
    FeatureSpec(
        name="mad_taker_imbalance_fut_5s",
        stage="S3",
        operator="s3.roll_mad",
        params={"market_scope": "Futures"},
        label="Dynamics: mad_taker_imbalance_fut_5s (Futures) [5s] (Binance)",
        group="Dynamics",
        description="Rolling MAD of median_taker_imbalance_fut_5s around its median.",
        depends_on=(
            Dep(name="median_taker_imbalance_fut_5s", kind="col"),
            Dep(name="taker_imbalance_fut_5s", kind="col"),
        ),
        feature_id=3119,
    ),
    FeatureSpec(
        name="mad_taker_imbalance_fut_60s",
        stage="S3",
        operator="s3.roll_mad",
        params={"market_scope": "Futures"},
        label="Dynamics: mad_taker_imbalance_fut_60s (Futures) [60s] (Binance)",
        group="Dynamics",
        description="Rolling MAD of median_taker_imbalance_fut_60s around its median.",
        depends_on=(
            Dep(name="median_taker_imbalance_fut_60s", kind="col"),
            Dep(name="taker_imbalance_fut_60s", kind="col"),
        ),
        feature_id=3120,
    ),
    FeatureSpec(
        name="mad_taker_imbalance_spot_15s",
        stage="S3",
        operator="s3.roll_mad",
        params={"market_scope": "Spot"},
        label="Dynamics: mad_taker_imbalance_spot_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Rolling MAD of median_taker_imbalance_spot_15s around its median.",
        depends_on=(
            Dep(name="median_taker_imbalance_spot_15s", kind="col"),
            Dep(name="taker_imbalance_spot_15s", kind="col"),
        ),
        feature_id=3121,
    ),
    FeatureSpec(
        name="mad_taker_imbalance_spot_5s",
        stage="S3",
        operator="s3.roll_mad",
        params={"market_scope": "Spot"},
        label="Dynamics: mad_taker_imbalance_spot_5s (Spot) [5s] (Binance)",
        group="Dynamics",
        description="Rolling MAD of median_taker_imbalance_spot_5s around its median.",
        depends_on=(
            Dep(name="median_taker_imbalance_spot_5s", kind="col"),
            Dep(name="taker_imbalance_spot_5s", kind="col"),
        ),
        feature_id=3122,
    ),
    FeatureSpec(
        name="mad_taker_imbalance_spot_60s",
        stage="S3",
        operator="s3.roll_mad",
        params={"market_scope": "Spot"},
        label="Dynamics: mad_taker_imbalance_spot_60s (Spot) [60s] (Binance)",
        group="Dynamics",
        description="Rolling MAD of median_taker_imbalance_spot_60s around its median.",
        depends_on=(
            Dep(name="median_taker_imbalance_spot_60s", kind="col"),
            Dep(name="taker_imbalance_spot_60s", kind="col"),
        ),
        feature_id=3123,
    ),

    # ── median_impact_per_signed (kept — used by impact_per_signed shocks) ────

    FeatureSpec(
        name="median_impact_per_signed_fut_15s",
        stage="S3",
        operator="s3.roll_median",
        params={"market_scope": "Futures"},
        label="Dynamics: median_impact_per_signed_fut_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Rolling median of impact_per_signed_fut_15s.",
        depends_on=(Dep(name="impact_per_signed_fut_15s", kind="col"),),
        feature_id=3124,
    ),
    FeatureSpec(
        name="median_impact_per_signed_fut_5s",
        stage="S3",
        operator="s3.roll_median",
        params={"market_scope": "Futures"},
        label="Dynamics: median_impact_per_signed_fut_5s (Futures) [5s] (Binance)",
        group="Dynamics",
        description="Rolling median of impact_per_signed_fut_5s.",
        depends_on=(Dep(name="impact_per_signed_fut_5s", kind="col"),),
        feature_id=3125,
    ),
    FeatureSpec(
        name="median_impact_per_signed_fut_60s",
        stage="S3",
        operator="s3.roll_median",
        params={"market_scope": "Futures"},
        label="Dynamics: median_impact_per_signed_fut_60s (Futures) [60s] (Binance)",
        group="Dynamics",
        description="Rolling median of impact_per_signed_fut_60s.",
        depends_on=(Dep(name="impact_per_signed_fut_60s", kind="col"),),
        feature_id=3126,
    ),
    FeatureSpec(
        name="median_impact_per_signed_spot_15s",
        stage="S3",
        operator="s3.roll_median",
        params={"market_scope": "Spot"},
        label="Dynamics: median_impact_per_signed_spot_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Rolling median of impact_per_signed_spot_15s.",
        depends_on=(Dep(name="impact_per_signed_spot_15s", kind="col"),),
        feature_id=3127,
    ),
    FeatureSpec(
        name="median_impact_per_signed_spot_5s",
        stage="S3",
        operator="s3.roll_median",
        params={"market_scope": "Spot"},
        label="Dynamics: median_impact_per_signed_spot_5s (Spot) [5s] (Binance)",
        group="Dynamics",
        description="Rolling median of impact_per_signed_spot_5s.",
        depends_on=(Dep(name="impact_per_signed_spot_5s", kind="col"),),
        feature_id=3128,
    ),
    FeatureSpec(
        name="median_impact_per_signed_spot_60s",
        stage="S3",
        operator="s3.roll_median",
        params={"market_scope": "Spot"},
        label="Dynamics: median_impact_per_signed_spot_60s (Spot) [60s] (Binance)",
        group="Dynamics",
        description="Rolling median of impact_per_signed_spot_60s.",
        depends_on=(Dep(name="impact_per_signed_spot_60s", kind="col"),),
        feature_id=3129,
    ),

    # ── median_taker_imbalance (kept — used by taker_imbalance shocks) ────────

    FeatureSpec(
        name="median_taker_imbalance_fut_15s",
        stage="S3",
        operator="s3.roll_median",
        params={"market_scope": "Futures"},
        label="Dynamics: median_taker_imbalance_fut_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Rolling median of taker_imbalance_fut_15s.",
        depends_on=(Dep(name="taker_imbalance_fut_15s", kind="col"),),
        feature_id=3130,
    ),
    FeatureSpec(
        name="median_taker_imbalance_fut_5s",
        stage="S3",
        operator="s3.roll_median",
        params={"market_scope": "Futures"},
        label="Dynamics: median_taker_imbalance_fut_5s (Futures) [5s] (Binance)",
        group="Dynamics",
        description="Rolling median of taker_imbalance_fut_5s.",
        depends_on=(Dep(name="taker_imbalance_fut_5s", kind="col"),),
        feature_id=3131,
    ),
    FeatureSpec(
        name="median_taker_imbalance_fut_60s",
        stage="S3",
        operator="s3.roll_median",
        params={"market_scope": "Futures"},
        label="Dynamics: median_taker_imbalance_fut_60s (Futures) [60s] (Binance)",
        group="Dynamics",
        description="Rolling median of taker_imbalance_fut_60s.",
        depends_on=(Dep(name="taker_imbalance_fut_60s", kind="col"),),
        feature_id=3132,
    ),
    FeatureSpec(
        name="median_taker_imbalance_spot_15s",
        stage="S3",
        operator="s3.roll_median",
        params={"market_scope": "Spot"},
        label="Dynamics: median_taker_imbalance_spot_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Rolling median of taker_imbalance_spot_15s.",
        depends_on=(Dep(name="taker_imbalance_spot_15s", kind="col"),),
        feature_id=3133,
    ),
    FeatureSpec(
        name="median_taker_imbalance_spot_5s",
        stage="S3",
        operator="s3.roll_median",
        params={"market_scope": "Spot"},
        label="Dynamics: median_taker_imbalance_spot_5s (Spot) [5s] (Binance)",
        group="Dynamics",
        description="Rolling median of taker_imbalance_spot_5s.",
        depends_on=(Dep(name="taker_imbalance_spot_5s", kind="col"),),
        feature_id=3134,
    ),
    FeatureSpec(
        name="median_taker_imbalance_spot_60s",
        stage="S3",
        operator="s3.roll_median",
        params={"market_scope": "Spot"},
        label="Dynamics: median_taker_imbalance_spot_60s (Spot) [60s] (Binance)",
        group="Dynamics",
        description="Rolling median of taker_imbalance_spot_60s.",
        depends_on=(Dep(name="taker_imbalance_spot_60s", kind="col"),),
        feature_id=3135,
    ),

    # ── net_pressure: flip_rate + persist ─────────────────────────────────────

    FeatureSpec(
        name="net_pressure_flip_rate_fut_10bps_300s",
        stage="S3",
        operator="derived.signal_flip_rate",
        params={"market_scope": "Futures", "window_s": "300"},
        label="Dynamics: net_pressure_flip_rate_fut_10bps_300s (Futures) [300s] (Binance)",
        group="Dynamics",
        description="Sign flip rate of net_add_pressure_fut_10bps_1s over 300s window.",
        depends_on=(Dep(name="net_add_pressure_fut_10bps_1s", kind="col"),),
        feature_id=3136,
    ),
    FeatureSpec(
        name="net_pressure_flip_rate_fut_5bps_300s",
        stage="S3",
        operator="derived.signal_flip_rate",
        params={"market_scope": "Futures", "window_s": "300"},
        label="Dynamics: net_pressure_flip_rate_fut_5bps_300s (Futures) [300s] (Binance)",
        group="Dynamics",
        description="Sign flip rate of net_add_pressure_fut_5bps_1s over 300s window.",
        depends_on=(Dep(name="net_add_pressure_fut_5bps_1s", kind="col"),),
        feature_id=3137,
    ),
    FeatureSpec(
        name="net_pressure_flip_rate_spot_10bps_300s",
        stage="S3",
        operator="derived.signal_flip_rate",
        params={"market_scope": "Spot", "window_s": "300"},
        label="Dynamics: net_pressure_flip_rate_spot_10bps_300s (Spot) [300s] (Binance)",
        group="Dynamics",
        description="Sign flip rate of net_add_pressure_spot_10bps_1s over 300s window.",
        depends_on=(Dep(name="net_add_pressure_spot_10bps_1s", kind="col"),),
        feature_id=3138,
    ),
    FeatureSpec(
        name="net_pressure_flip_rate_spot_5bps_300s",
        stage="S3",
        operator="derived.signal_flip_rate",
        params={"market_scope": "Spot", "window_s": "300"},
        label="Dynamics: net_pressure_flip_rate_spot_5bps_300s (Spot) [300s] (Binance)",
        group="Dynamics",
        description="Sign flip rate of net_add_pressure_spot_5bps_1s over 300s window.",
        depends_on=(Dep(name="net_add_pressure_spot_5bps_1s", kind="col"),),
        feature_id=3139,
    ),
    FeatureSpec(
        name="net_pressure_persist_fut_10bps_300s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Futures", "window_s": "300"},
        label="Dynamics: net_pressure_persist_fut_10bps_300s (Futures) [300s] (Binance)",
        group="Dynamics",
        description="Sign persistence of net_add_pressure_fut_10bps_1s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="net_add_pressure_fut_10bps_1s", kind="col"),),
        feature_id=3140,
    ),
    FeatureSpec(
        name="net_pressure_persist_fut_5bps_300s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Futures", "window_s": "300"},
        label="Dynamics: net_pressure_persist_fut_5bps_300s (Futures) [300s] (Binance)",
        group="Dynamics",
        description="Sign persistence of net_add_pressure_fut_5bps_1s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="net_add_pressure_fut_5bps_1s", kind="col"),),
        feature_id=3141,
    ),
    FeatureSpec(
        name="net_pressure_persist_spot_10bps_300s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Spot", "window_s": "300"},
        label="Dynamics: net_pressure_persist_spot_10bps_300s (Spot) [300s] (Binance)",
        group="Dynamics",
        description="Sign persistence of net_add_pressure_spot_10bps_1s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="net_add_pressure_spot_10bps_1s", kind="col"),),
        feature_id=3142,
    ),
    FeatureSpec(
        name="net_pressure_persist_spot_5bps_300s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Spot", "window_s": "300"},
        label="Dynamics: net_pressure_persist_spot_5bps_300s (Spot) [300s] (Binance)",
        group="Dynamics",
        description="Sign persistence of net_add_pressure_spot_5bps_1s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="net_add_pressure_spot_5bps_1s", kind="col"),),
        feature_id=3143,
    ),

    # ── pull_rate: persist ────────────────────────────────────────────────────

    FeatureSpec(
        name="pull_rate_fut_1bps_persist_15s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Dynamics: pull_rate_fut_1bps_persist_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Sign persistence of pull_rate_fut_1bps_15s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="pull_rate_fut_1bps_15s", kind="col"),),
        feature_id=3144,
    ),
    FeatureSpec(
        name="pull_rate_fut_2bps_persist_15s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Dynamics: pull_rate_fut_2bps_persist_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Sign persistence of pull_rate_fut_2bps_15s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="pull_rate_fut_2bps_15s", kind="col"),),
        feature_id=3145,
    ),
    FeatureSpec(
        name="pull_rate_fut_2bps_persist_60s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Dynamics: pull_rate_fut_2bps_persist_60s (Futures) [60s] (Binance)",
        group="Dynamics",
        description="Sign persistence of pull_rate_fut_2bps_60s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="pull_rate_fut_2bps_60s", kind="col"),),
        feature_id=3146,
    ),
    FeatureSpec(
        name="pull_rate_spot_1bps_persist_15s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Dynamics: pull_rate_spot_1bps_persist_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Sign persistence of pull_rate_spot_1bps_15s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="pull_rate_spot_1bps_15s", kind="col"),),
        feature_id=3147,
    ),
    FeatureSpec(
        name="pull_rate_spot_2bps_persist_15s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Dynamics: pull_rate_spot_2bps_persist_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Sign persistence of pull_rate_spot_2bps_15s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="pull_rate_spot_2bps_15s", kind="col"),),
        feature_id=3148,
    ),
    FeatureSpec(
        name="pull_rate_spot_2bps_persist_60s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Dynamics: pull_rate_spot_2bps_persist_60s (Spot) [60s] (Binance)",
        group="Dynamics",
        description="Sign persistence of pull_rate_spot_2bps_60s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="pull_rate_spot_2bps_60s", kind="col"),),
        feature_id=3149,
    ),

    # ── refill_rate: persist ──────────────────────────────────────────────────

    FeatureSpec(
        name="refill_rate_fut_1bps_persist_15s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Dynamics: refill_rate_fut_1bps_persist_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Sign persistence of refill_rate_fut_1bps_15s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="refill_rate_fut_1bps_15s", kind="col"),),
        feature_id=3150,
    ),
    FeatureSpec(
        name="refill_rate_fut_2bps_persist_15s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Dynamics: refill_rate_fut_2bps_persist_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Sign persistence of refill_rate_fut_2bps_15s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="refill_rate_fut_2bps_15s", kind="col"),),
        feature_id=3151,
    ),
    FeatureSpec(
        name="refill_rate_fut_2bps_persist_60s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Dynamics: refill_rate_fut_2bps_persist_60s (Futures) [60s] (Binance)",
        group="Dynamics",
        description="Sign persistence of refill_rate_fut_2bps_60s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="refill_rate_fut_2bps_60s", kind="col"),),
        feature_id=3152,
    ),
    FeatureSpec(
        name="refill_rate_spot_1bps_persist_15s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Dynamics: refill_rate_spot_1bps_persist_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Sign persistence of refill_rate_spot_1bps_15s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="refill_rate_spot_1bps_15s", kind="col"),),
        feature_id=3153,
    ),
    FeatureSpec(
        name="refill_rate_spot_2bps_persist_15s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Dynamics: refill_rate_spot_2bps_persist_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Sign persistence of refill_rate_spot_2bps_15s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="refill_rate_spot_2bps_15s", kind="col"),),
        feature_id=3154,
    ),
    FeatureSpec(
        name="refill_rate_spot_2bps_persist_60s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Dynamics: refill_rate_spot_2bps_persist_60s (Spot) [60s] (Binance)",
        group="Dynamics",
        description="Sign persistence of refill_rate_spot_2bps_60s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="refill_rate_spot_2bps_60s", kind="col"),),
        feature_id=3155,
    ),

    # ── refill_vs_pull: persist ───────────────────────────────────────────────

    FeatureSpec(
        name="refill_vs_pull_fut_1bps_persist_15s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Dynamics: refill_vs_pull_fut_1bps_persist_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Sign persistence of refill_vs_pull_fut_1bps_15s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="refill_vs_pull_fut_1bps_15s", kind="col"),),
        feature_id=3156,
    ),
    FeatureSpec(
        name="refill_vs_pull_fut_2bps_persist_60s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Dynamics: refill_vs_pull_fut_2bps_persist_60s (Futures) [60s] (Binance)",
        group="Dynamics",
        description="Sign persistence of refill_vs_pull_fut_2bps_60s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="refill_vs_pull_fut_2bps_60s", kind="col"),),
        feature_id=3157,
    ),
    FeatureSpec(
        name="refill_vs_pull_spot_1bps_persist_15s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Dynamics: refill_vs_pull_spot_1bps_persist_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Sign persistence of refill_vs_pull_spot_1bps_15s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="refill_vs_pull_spot_1bps_15s", kind="col"),),
        feature_id=3158,
    ),
    FeatureSpec(
        name="refill_vs_pull_spot_2bps_persist_60s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Dynamics: refill_vs_pull_spot_2bps_persist_60s (Spot) [60s] (Binance)",
        group="Dynamics",
        description="Sign persistence of refill_vs_pull_spot_2bps_60s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="refill_vs_pull_spot_2bps_60s", kind="col"),),
        feature_id=3159,
    ),

    # ── taker_imbalance: persist + shock ──────────────────────────────────────

    FeatureSpec(
        name="taker_imbalance_fut_persist_15s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Dynamics: taker_imbalance_fut_persist_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Sign persistence of taker_imbalance_fut_15s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="taker_imbalance_fut_15s", kind="col"),),
        feature_id=3160,
    ),
    FeatureSpec(
        name="taker_imbalance_fut_persist_60s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Dynamics: taker_imbalance_fut_persist_60s (Futures) [60s] (Binance)",
        group="Dynamics",
        description="Sign persistence of taker_imbalance_fut_60s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="taker_imbalance_fut_60s", kind="col"),),
        feature_id=3161,
    ),
    FeatureSpec(
        name="taker_imbalance_shock_fut_15s",
        stage="S3",
        operator="s3.shock",
        params={"market_scope": "Futures"},
        label="Dynamics: taker_imbalance_shock_fut_15s (Futures) [15s] (Binance)",
        group="Dynamics",
        description="Shock score: (taker - median) / (MAD * 1.4826 + eps).",
        depends_on=(
            Dep(name="mad_taker_imbalance_fut_15s", kind="col"),
            Dep(name="median_taker_imbalance_fut_15s", kind="col"),
            Dep(name="taker_imbalance_fut_15s", kind="col"),
        ),
        feature_id=3162,
    ),
    FeatureSpec(
        name="taker_imbalance_shock_fut_5s",
        stage="S3",
        operator="s3.shock",
        params={"market_scope": "Futures"},
        label="Dynamics: taker_imbalance_shock_fut_5s (Futures) [5s] (Binance)",
        group="Dynamics",
        description="Shock score: (taker - median) / (MAD * 1.4826 + eps).",
        depends_on=(
            Dep(name="mad_taker_imbalance_fut_5s", kind="col"),
            Dep(name="median_taker_imbalance_fut_5s", kind="col"),
            Dep(name="taker_imbalance_fut_5s", kind="col"),
        ),
        feature_id=3163,
    ),
    FeatureSpec(
        name="taker_imbalance_shock_fut_60s",
        stage="S3",
        operator="s3.shock",
        params={"market_scope": "Futures"},
        label="Dynamics: taker_imbalance_shock_fut_60s (Futures) [60s] (Binance)",
        group="Dynamics",
        description="Shock score: (taker - median) / (MAD * 1.4826 + eps).",
        depends_on=(
            Dep(name="mad_taker_imbalance_fut_60s", kind="col"),
            Dep(name="median_taker_imbalance_fut_60s", kind="col"),
            Dep(name="taker_imbalance_fut_60s", kind="col"),
        ),
        feature_id=3164,
    ),
    FeatureSpec(
        name="taker_imbalance_shock_spot_15s",
        stage="S3",
        operator="s3.shock",
        params={"market_scope": "Spot"},
        label="Dynamics: taker_imbalance_shock_spot_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Shock score: (taker - median) / (MAD * 1.4826 + eps).",
        depends_on=(
            Dep(name="mad_taker_imbalance_spot_15s", kind="col"),
            Dep(name="median_taker_imbalance_spot_15s", kind="col"),
            Dep(name="taker_imbalance_spot_15s", kind="col"),
        ),
        feature_id=3165,
    ),
    FeatureSpec(
        name="taker_imbalance_shock_spot_5s",
        stage="S3",
        operator="s3.shock",
        params={"market_scope": "Spot"},
        label="Dynamics: taker_imbalance_shock_spot_5s (Spot) [5s] (Binance)",
        group="Dynamics",
        description="Shock score: (taker - median) / (MAD * 1.4826 + eps).",
        depends_on=(
            Dep(name="mad_taker_imbalance_spot_5s", kind="col"),
            Dep(name="median_taker_imbalance_spot_5s", kind="col"),
            Dep(name="taker_imbalance_spot_5s", kind="col"),
        ),
        feature_id=3166,
    ),
    FeatureSpec(
        name="taker_imbalance_shock_spot_60s",
        stage="S3",
        operator="s3.shock",
        params={"market_scope": "Spot"},
        label="Dynamics: taker_imbalance_shock_spot_60s (Spot) [60s] (Binance)",
        group="Dynamics",
        description="Shock score: (taker - median) / (MAD * 1.4826 + eps).",
        depends_on=(
            Dep(name="mad_taker_imbalance_spot_60s", kind="col"),
            Dep(name="median_taker_imbalance_spot_60s", kind="col"),
            Dep(name="taker_imbalance_spot_60s", kind="col"),
        ),
        feature_id=3167,
    ),
    FeatureSpec(
        name="taker_imbalance_spot_persist_15s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Dynamics: taker_imbalance_spot_persist_15s (Spot) [15s] (Binance)",
        group="Dynamics",
        description="Sign persistence of taker_imbalance_spot_15s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="taker_imbalance_spot_15s", kind="col"),),
        feature_id=3168,
    ),
    FeatureSpec(
        name="taker_imbalance_spot_persist_60s",
        stage="S3",
        operator="derived.signal_persist",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Dynamics: taker_imbalance_spot_persist_60s (Spot) [60s] (Binance)",
        group="Dynamics",
        description="Sign persistence of taker_imbalance_spot_60s: fraction of sub-buckets with same sign.",
        depends_on=(Dep(name="taker_imbalance_spot_60s", kind="col"),),
        feature_id=3169,
    ),
]