# etl/spec/s3/s3_meta.py
# ========================================================================
# S3 Meta Features
# Higher-order structural features that analyze the consistency and shape of
# microstructure signals across multiple depth bands. These are "features of
# features" — they characterize the quality and structure of the signal
# landscape rather than individual market metrics.
# 
# Key concepts:
#   - dir_consistency_asym: Asymmetry in direction consistency between short
#     (60s) and long (900s) windows. Divergence suggests regime transition.
#   - queue_pressure_depth_coherence: Minimum pairwise sign agreement of
#     queue pressure across BPS bands [1, 2, 5, 10]. High coherence = uniform
#     pressure; low = conflicting signals at different depth levels.
#   - queue_pressure_depth_curvature: Second difference of queue pressure
#     across depth bands. Measures convexity of the pressure profile.
#   - queue_pressure_depth_slope: Linear slope of queue pressure across
#     depth bands. Positive slope = pressure increases with depth.
#   - vacuum_score: z_pull_rate - z_refill_rate. High values indicate
#     aggressive liquidity withdrawal with insufficient replenishment —
#     a "vacuum" forming in the orderbook.
# 
# Dependencies: S2 queue_pressure at 1/2/5/10 bps, z_pull_rate, z_refill_rate,
#               dir_consistency.
#
# Feature count: 31
# Feature ID range: see individual entries
# ========================================================================

from typing import List
from etl.spec import FeatureSpec, Dep

S3_META_FEATURES: List[FeatureSpec] = [
    FeatureSpec(
        name="dir_consistency_asym_spot_60_over_900",
        stage="S3",
        operator="s3.dir_consistency_asym",
        params={"market_scope": "Spot"},
        label="Meta: dir_consistency_asym_spot_60_over_900 (Spot) [900s] (Binance)",
        group="Meta",
        description="Direction consistency asymmetry: dir_consistency_spot_60s - dir_consistency_spot_900s.",
        depends_on=(
            Dep(name="dir_consistency_spot_60s", kind="col"),
            Dep(name="dir_consistency_spot_900s", kind="col"),
        ),
        feature_id=3178,
    ),
    FeatureSpec(
        name="queue_pressure_depth_coherence_fut_15s",
        stage="S3",
        operator="s3.qp_depth_coherence",
        params={"market_scope": "Futures"},
        label="Meta: queue_pressure_depth_coherence_fut_15s (Futures) [15s] (Binance)",
        group="Meta",
        description="Queue pressure depth coherence: min pairwise correlation across BPS bands.",
        depends_on=(
            Dep(name="queue_pressure_fut_10bps_15s", kind="col"),
            Dep(name="queue_pressure_fut_1bps_15s", kind="col"),
            Dep(name="queue_pressure_fut_2bps_15s", kind="col"),
            Dep(name="queue_pressure_fut_5bps_15s", kind="col"),
        ),
        feature_id=3179,
    ),
    FeatureSpec(
        name="queue_pressure_depth_coherence_fut_60s",
        stage="S3",
        operator="s3.qp_depth_coherence",
        params={"market_scope": "Futures"},
        label="Meta: queue_pressure_depth_coherence_fut_60s (Futures) [60s] (Binance)",
        group="Meta",
        description="Queue pressure depth coherence: min pairwise correlation across BPS bands.",
        depends_on=(
            Dep(name="queue_pressure_fut_10bps_60s", kind="col"),
            Dep(name="queue_pressure_fut_1bps_60s", kind="col"),
            Dep(name="queue_pressure_fut_2bps_60s", kind="col"),
            Dep(name="queue_pressure_fut_5bps_60s", kind="col"),
        ),
        feature_id=3180,
    ),
    FeatureSpec(
        name="queue_pressure_depth_coherence_spot_15s",
        stage="S3",
        operator="s3.qp_depth_coherence",
        params={"market_scope": "Spot"},
        label="Meta: queue_pressure_depth_coherence_spot_15s (Spot) [15s] (Binance)",
        group="Meta",
        description="Queue pressure depth coherence: min pairwise correlation across BPS bands.",
        depends_on=(
            Dep(name="queue_pressure_spot_10bps_15s", kind="col"),
            Dep(name="queue_pressure_spot_1bps_15s", kind="col"),
            Dep(name="queue_pressure_spot_2bps_15s", kind="col"),
            Dep(name="queue_pressure_spot_5bps_15s", kind="col"),
        ),
        feature_id=3181,
    ),
    FeatureSpec(
        name="queue_pressure_depth_coherence_spot_60s",
        stage="S3",
        operator="s3.qp_depth_coherence",
        params={"market_scope": "Spot"},
        label="Meta: queue_pressure_depth_coherence_spot_60s (Spot) [60s] (Binance)",
        group="Meta",
        description="Queue pressure depth coherence: min pairwise correlation across BPS bands.",
        depends_on=(
            Dep(name="queue_pressure_spot_10bps_60s", kind="col"),
            Dep(name="queue_pressure_spot_1bps_60s", kind="col"),
            Dep(name="queue_pressure_spot_2bps_60s", kind="col"),
            Dep(name="queue_pressure_spot_5bps_60s", kind="col"),
        ),
        feature_id=3182,
    ),
    FeatureSpec(
        name="queue_pressure_depth_curvature_fut_15s",
        stage="S3",
        operator="s3.qp_depth_curvature",
        params={"market_scope": "Futures"},
        label="Meta: queue_pressure_depth_curvature_fut_15s (Futures) [15s] (Binance)",
        group="Meta",
        description="Queue pressure depth curvature: second difference across BPS bands.",
        depends_on=(
            Dep(name="queue_pressure_fut_10bps_15s", kind="col"),
            Dep(name="queue_pressure_fut_1bps_15s", kind="col"),
            Dep(name="queue_pressure_fut_2bps_15s", kind="col"),
            Dep(name="queue_pressure_fut_5bps_15s", kind="col"),
        ),
        feature_id=3183,
    ),
    FeatureSpec(
        name="queue_pressure_depth_curvature_fut_60s",
        stage="S3",
        operator="s3.qp_depth_curvature",
        params={"market_scope": "Futures"},
        label="Meta: queue_pressure_depth_curvature_fut_60s (Futures) [60s] (Binance)",
        group="Meta",
        description="Queue pressure depth curvature: second difference across BPS bands.",
        depends_on=(
            Dep(name="queue_pressure_fut_10bps_60s", kind="col"),
            Dep(name="queue_pressure_fut_1bps_60s", kind="col"),
            Dep(name="queue_pressure_fut_2bps_60s", kind="col"),
            Dep(name="queue_pressure_fut_5bps_60s", kind="col"),
        ),
        feature_id=3184,
    ),
    FeatureSpec(
        name="queue_pressure_depth_curvature_spot_15s",
        stage="S3",
        operator="s3.qp_depth_curvature",
        params={"market_scope": "Spot"},
        label="Meta: queue_pressure_depth_curvature_spot_15s (Spot) [15s] (Binance)",
        group="Meta",
        description="Queue pressure depth curvature: second difference across BPS bands.",
        depends_on=(
            Dep(name="queue_pressure_spot_10bps_15s", kind="col"),
            Dep(name="queue_pressure_spot_1bps_15s", kind="col"),
            Dep(name="queue_pressure_spot_2bps_15s", kind="col"),
            Dep(name="queue_pressure_spot_5bps_15s", kind="col"),
        ),
        feature_id=3185,
    ),
    FeatureSpec(
        name="queue_pressure_depth_curvature_spot_60s",
        stage="S3",
        operator="s3.qp_depth_curvature",
        params={"market_scope": "Spot"},
        label="Meta: queue_pressure_depth_curvature_spot_60s (Spot) [60s] (Binance)",
        group="Meta",
        description="Queue pressure depth curvature: second difference across BPS bands.",
        depends_on=(
            Dep(name="queue_pressure_spot_10bps_60s", kind="col"),
            Dep(name="queue_pressure_spot_1bps_60s", kind="col"),
            Dep(name="queue_pressure_spot_2bps_60s", kind="col"),
            Dep(name="queue_pressure_spot_5bps_60s", kind="col"),
        ),
        feature_id=3186,
    ),
    FeatureSpec(
        name="queue_pressure_depth_slope_fut_15s",
        stage="S3",
        operator="s3.qp_depth_slope",
        params={"market_scope": "Futures"},
        label="Meta: queue_pressure_depth_slope_fut_15s (Futures) [15s] (Binance)",
        group="Meta",
        description="Queue pressure depth slope: linear slope across BPS bands.",
        depends_on=(
            Dep(name="queue_pressure_fut_10bps_15s", kind="col"),
            Dep(name="queue_pressure_fut_1bps_15s", kind="col"),
            Dep(name="queue_pressure_fut_2bps_15s", kind="col"),
            Dep(name="queue_pressure_fut_5bps_15s", kind="col"),
        ),
        feature_id=3187,
    ),
    FeatureSpec(
        name="queue_pressure_depth_slope_fut_60s",
        stage="S3",
        operator="s3.qp_depth_slope",
        params={"market_scope": "Futures"},
        label="Meta: queue_pressure_depth_slope_fut_60s (Futures) [60s] (Binance)",
        group="Meta",
        description="Queue pressure depth slope: linear slope across BPS bands.",
        depends_on=(
            Dep(name="queue_pressure_fut_10bps_60s", kind="col"),
            Dep(name="queue_pressure_fut_1bps_60s", kind="col"),
            Dep(name="queue_pressure_fut_2bps_60s", kind="col"),
            Dep(name="queue_pressure_fut_5bps_60s", kind="col"),
        ),
        feature_id=3188,
    ),
    FeatureSpec(
        name="queue_pressure_depth_slope_spot_15s",
        stage="S3",
        operator="s3.qp_depth_slope",
        params={"market_scope": "Spot"},
        label="Meta: queue_pressure_depth_slope_spot_15s (Spot) [15s] (Binance)",
        group="Meta",
        description="Queue pressure depth slope: linear slope across BPS bands.",
        depends_on=(
            Dep(name="queue_pressure_spot_10bps_15s", kind="col"),
            Dep(name="queue_pressure_spot_1bps_15s", kind="col"),
            Dep(name="queue_pressure_spot_2bps_15s", kind="col"),
            Dep(name="queue_pressure_spot_5bps_15s", kind="col"),
        ),
        feature_id=3189,
    ),
    FeatureSpec(
        name="queue_pressure_depth_slope_spot_60s",
        stage="S3",
        operator="s3.qp_depth_slope",
        params={"market_scope": "Spot"},
        label="Meta: queue_pressure_depth_slope_spot_60s (Spot) [60s] (Binance)",
        group="Meta",
        description="Queue pressure depth slope: linear slope across BPS bands.",
        depends_on=(
            Dep(name="queue_pressure_spot_10bps_60s", kind="col"),
            Dep(name="queue_pressure_spot_1bps_60s", kind="col"),
            Dep(name="queue_pressure_spot_2bps_60s", kind="col"),
            Dep(name="queue_pressure_spot_5bps_60s", kind="col"),
        ),
        feature_id=3190,
    ),
    FeatureSpec(
        name="vacuum_score_fut_10bps_15s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Futures"},
        label="Meta: vacuum_score_fut_10bps_15s (Futures) [15s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_fut_10bps_15s - z_refill_rate_fut_10bps_15s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_fut_10bps_15s", kind="col"),
            Dep(name="z_refill_rate_fut_10bps_15s", kind="col"),
        ),
        feature_id=3191,
    ),
    FeatureSpec(
        name="vacuum_score_fut_10bps_5s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Futures"},
        label="Meta: vacuum_score_fut_10bps_5s (Futures) [5s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_fut_10bps_5s - z_refill_rate_fut_10bps_5s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_fut_10bps_5s", kind="col"),
            Dep(name="z_refill_rate_fut_10bps_5s", kind="col"),
        ),
        feature_id=3192,
    ),
    FeatureSpec(
        name="vacuum_score_fut_10bps_60s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Futures"},
        label="Meta: vacuum_score_fut_10bps_60s (Futures) [60s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_fut_10bps_60s - z_refill_rate_fut_10bps_60s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_fut_10bps_60s", kind="col"),
            Dep(name="z_refill_rate_fut_10bps_60s", kind="col"),
        ),
        feature_id=3193,
    ),
    FeatureSpec(
        name="vacuum_score_fut_1bps_5s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Futures"},
        label="Meta: vacuum_score_fut_1bps_5s (Futures) [5s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_fut_1bps_5s - z_refill_rate_fut_1bps_5s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_fut_1bps_5s", kind="col"),
            Dep(name="z_refill_rate_fut_1bps_5s", kind="col"),
        ),
        feature_id=3194,
    ),
    FeatureSpec(
        name="vacuum_score_fut_1bps_60s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Futures"},
        label="Meta: vacuum_score_fut_1bps_60s (Futures) [60s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_fut_1bps_60s - z_refill_rate_fut_1bps_60s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_fut_1bps_60s", kind="col"),
            Dep(name="z_refill_rate_fut_1bps_60s", kind="col"),
        ),
        feature_id=3195,
    ),
    FeatureSpec(
        name="vacuum_score_fut_2bps_5s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Futures"},
        label="Meta: vacuum_score_fut_2bps_5s (Futures) [5s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_fut_2bps_5s - z_refill_rate_fut_2bps_5s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_fut_2bps_5s", kind="col"),
            Dep(name="z_refill_rate_fut_2bps_5s", kind="col"),
        ),
        feature_id=3196,
    ),
    FeatureSpec(
        name="vacuum_score_fut_5bps_15s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Futures"},
        label="Meta: vacuum_score_fut_5bps_15s (Futures) [15s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_fut_5bps_15s - z_refill_rate_fut_5bps_15s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_fut_5bps_15s", kind="col"),
            Dep(name="z_refill_rate_fut_5bps_15s", kind="col"),
        ),
        feature_id=3197,
    ),
    FeatureSpec(
        name="vacuum_score_fut_5bps_5s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Futures"},
        label="Meta: vacuum_score_fut_5bps_5s (Futures) [5s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_fut_5bps_5s - z_refill_rate_fut_5bps_5s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_fut_5bps_5s", kind="col"),
            Dep(name="z_refill_rate_fut_5bps_5s", kind="col"),
        ),
        feature_id=3198,
    ),
    FeatureSpec(
        name="vacuum_score_fut_5bps_60s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Futures"},
        label="Meta: vacuum_score_fut_5bps_60s (Futures) [60s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_fut_5bps_60s - z_refill_rate_fut_5bps_60s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_fut_5bps_60s", kind="col"),
            Dep(name="z_refill_rate_fut_5bps_60s", kind="col"),
        ),
        feature_id=3199,
    ),
    FeatureSpec(
        name="vacuum_score_spot_10bps_15s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Spot"},
        label="Meta: vacuum_score_spot_10bps_15s (Spot) [15s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_spot_10bps_15s - z_refill_rate_spot_10bps_15s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_spot_10bps_15s", kind="col"),
            Dep(name="z_refill_rate_spot_10bps_15s", kind="col"),
        ),
        feature_id=3200,
    ),
    FeatureSpec(
        name="vacuum_score_spot_10bps_5s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Spot"},
        label="Meta: vacuum_score_spot_10bps_5s (Spot) [5s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_spot_10bps_5s - z_refill_rate_spot_10bps_5s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_spot_10bps_5s", kind="col"),
            Dep(name="z_refill_rate_spot_10bps_5s", kind="col"),
        ),
        feature_id=3201,
    ),
    FeatureSpec(
        name="vacuum_score_spot_10bps_60s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Spot"},
        label="Meta: vacuum_score_spot_10bps_60s (Spot) [60s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_spot_10bps_60s - z_refill_rate_spot_10bps_60s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_spot_10bps_60s", kind="col"),
            Dep(name="z_refill_rate_spot_10bps_60s", kind="col"),
        ),
        feature_id=3202,
    ),
    FeatureSpec(
        name="vacuum_score_spot_1bps_5s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Spot"},
        label="Meta: vacuum_score_spot_1bps_5s (Spot) [5s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_spot_1bps_5s - z_refill_rate_spot_1bps_5s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_spot_1bps_5s", kind="col"),
            Dep(name="z_refill_rate_spot_1bps_5s", kind="col"),
        ),
        feature_id=3203,
    ),
    FeatureSpec(
        name="vacuum_score_spot_1bps_60s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Spot"},
        label="Meta: vacuum_score_spot_1bps_60s (Spot) [60s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_spot_1bps_60s - z_refill_rate_spot_1bps_60s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_spot_1bps_60s", kind="col"),
            Dep(name="z_refill_rate_spot_1bps_60s", kind="col"),
        ),
        feature_id=3204,
    ),
    FeatureSpec(
        name="vacuum_score_spot_2bps_5s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Spot"},
        label="Meta: vacuum_score_spot_2bps_5s (Spot) [5s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_spot_2bps_5s - z_refill_rate_spot_2bps_5s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_spot_2bps_5s", kind="col"),
            Dep(name="z_refill_rate_spot_2bps_5s", kind="col"),
        ),
        feature_id=3205,
    ),
    FeatureSpec(
        name="vacuum_score_spot_5bps_15s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Spot"},
        label="Meta: vacuum_score_spot_5bps_15s (Spot) [15s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_spot_5bps_15s - z_refill_rate_spot_5bps_15s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_spot_5bps_15s", kind="col"),
            Dep(name="z_refill_rate_spot_5bps_15s", kind="col"),
        ),
        feature_id=3206,
    ),
    FeatureSpec(
        name="vacuum_score_spot_5bps_5s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Spot"},
        label="Meta: vacuum_score_spot_5bps_5s (Spot) [5s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_spot_5bps_5s - z_refill_rate_spot_5bps_5s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_spot_5bps_5s", kind="col"),
            Dep(name="z_refill_rate_spot_5bps_5s", kind="col"),
        ),
        feature_id=3207,
    ),
    FeatureSpec(
        name="vacuum_score_spot_5bps_60s",
        stage="S3",
        operator="s3.vacuum_score",
        params={"market_scope": "Spot"},
        label="Meta: vacuum_score_spot_5bps_60s (Spot) [60s] (Binance)",
        group="Meta",
        description="Vacuum score: z_pull_rate_spot_5bps_60s - z_refill_rate_spot_5bps_60s. High pull + low refill = vacuum.",
        depends_on=(
            Dep(name="z_pull_rate_spot_5bps_60s", kind="col"),
            Dep(name="z_refill_rate_spot_5bps_60s", kind="col"),
        ),
        feature_id=3208,
    ),

]