# etl/spec/s3/s3_normalization.py
# ========================================================================
# S3 Normalization Features
# Robust z-score normalization of key S2 signals, making them comparable
# across time regimes and asset conditions. All use the robust z-score
# formula: (x - rolling_median) / (1.4826 * rolling_MAD + eps).
# 
# Key concepts:
#   - z_absorb_refill_ask/bid: Normalized absorption refill per side/market/bps.
#   - z_book_asymmetry: Normalized book asymmetry at struct50/struct100 levels.
#   - z_depth_gradient / z_liq_concentration: Normalized bookshape metrics.
#   - z_impact_per_signed: Normalized price impact per signed volume.
#   - z_price_deviation: Normalized VWAP-mid deviation (cross-market).
#   - z_pull_rate / z_refill_rate / z_refill_vs_pull: Normalized maker behavior.
#   - z_queue_pressure: Normalized queue pressure log-ratio.
#   - z_taker_imbalance: Normalized taker imbalance across all timeframes.
#   - z_trade_absorption_ratio: Normalized TAR at the 1s level.
# 
# Dependencies: Corresponding S2 base signals (absorb_refill, book_asymmetry,
#               depth_gradient, impact_per_signed, mid_touch_dev, price_deviation,
#               pull_rate, queue_pressure, refill_rate, refill_vs_pull,
#               taker_imbalance, trade_absorption_ratio).
#
# Feature count: 72  (was 81; removed 7 × 3600s features; removed 2 × z_mid_touch_dev)
# Fixes applied:
#   [FIX-1s]   All window_s=1 z-scores → window_s=5 (1s rolling z-score is always
#              NaN: MAD=0 with a single point). Sparse signals get min_periods=2.
#              Feature names retain _1s suffix (describes input signal resolution,
#              not the normalization window). Downstream specs are unaffected.
#   [FIX-3600] Removed all window_s=3600 features (7 total). 3600s rolling z-score
#              requires 1h of prior data even with context; signals are 99%+ NaN.
#              Microstructure regime is adequately covered by the 900s variants.
#              If downstream specs reference any removed feature names, those
#              depend_on entries must also be updated (search codebase for each
#              removed name and remove or substitute with the 900s variant).
# Feature ID range: see individual entries
# ========================================================================

from typing import List
from etl.spec import FeatureSpec, Dep

S3_NORMALIZATION_FEATURES: List[FeatureSpec] = [
    FeatureSpec(
        name="z_absorb_refill_ask_fut_10bps_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "5", "min_periods": 2},
        label="Normalization: z_absorb_refill_ask_fut_10bps_1s (Futures) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of absorb_refill_ask_fut_10bps_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="absorb_refill_ask_fut_10bps_1s", kind="col"),),
        feature_id=3209,
    ),
    FeatureSpec(
        name="z_absorb_refill_ask_fut_2bps_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "5", "min_periods": 2},
        label="Normalization: z_absorb_refill_ask_fut_2bps_1s (Futures) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of absorb_refill_ask_fut_2bps_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="absorb_refill_ask_fut_2bps_1s", kind="col"),),
        feature_id=3210,
    ),
    FeatureSpec(
        name="z_absorb_refill_ask_fut_5bps_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "5", "min_periods": 2},
        label="Normalization: z_absorb_refill_ask_fut_5bps_1s (Futures) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of absorb_refill_ask_fut_5bps_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="absorb_refill_ask_fut_5bps_1s", kind="col"),),
        feature_id=3211,
    ),
    FeatureSpec(
        name="z_absorb_refill_ask_spot_10bps_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "5", "min_periods": 2},
        label="Normalization: z_absorb_refill_ask_spot_10bps_1s (Spot) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of absorb_refill_ask_spot_10bps_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="absorb_refill_ask_spot_10bps_1s", kind="col"),),
        feature_id=3212,
    ),
    FeatureSpec(
        name="z_absorb_refill_ask_spot_2bps_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "5", "min_periods": 2},
        label="Normalization: z_absorb_refill_ask_spot_2bps_1s (Spot) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of absorb_refill_ask_spot_2bps_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="absorb_refill_ask_spot_2bps_1s", kind="col"),),
        feature_id=3213,
    ),
    FeatureSpec(
        name="z_absorb_refill_ask_spot_5bps_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "5", "min_periods": 2},
        label="Normalization: z_absorb_refill_ask_spot_5bps_1s (Spot) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of absorb_refill_ask_spot_5bps_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="absorb_refill_ask_spot_5bps_1s", kind="col"),),
        feature_id=3214,
    ),
    FeatureSpec(
        name="z_absorb_refill_bid_fut_10bps_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "5", "min_periods": 2},
        label="Normalization: z_absorb_refill_bid_fut_10bps_1s (Futures) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of absorb_refill_bid_fut_10bps_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="absorb_refill_bid_fut_10bps_1s", kind="col"),),
        feature_id=3215,
    ),
    FeatureSpec(
        name="z_absorb_refill_bid_fut_2bps_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "5", "min_periods": 2},
        label="Normalization: z_absorb_refill_bid_fut_2bps_1s (Futures) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of absorb_refill_bid_fut_2bps_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="absorb_refill_bid_fut_2bps_1s", kind="col"),),
        feature_id=3216,
    ),
    FeatureSpec(
        name="z_absorb_refill_bid_fut_5bps_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "5", "min_periods": 2},
        label="Normalization: z_absorb_refill_bid_fut_5bps_1s (Futures) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of absorb_refill_bid_fut_5bps_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="absorb_refill_bid_fut_5bps_1s", kind="col"),),
        feature_id=3217,
    ),
    FeatureSpec(
        name="z_absorb_refill_bid_spot_10bps_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "5", "min_periods": 2},
        label="Normalization: z_absorb_refill_bid_spot_10bps_1s (Spot) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of absorb_refill_bid_spot_10bps_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="absorb_refill_bid_spot_10bps_1s", kind="col"),),
        feature_id=3218,
    ),
    FeatureSpec(
        name="z_absorb_refill_bid_spot_2bps_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "5", "min_periods": 2},
        label="Normalization: z_absorb_refill_bid_spot_2bps_1s (Spot) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of absorb_refill_bid_spot_2bps_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="absorb_refill_bid_spot_2bps_1s", kind="col"),),
        feature_id=3219,
    ),
    FeatureSpec(
        name="z_absorb_refill_bid_spot_5bps_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "5", "min_periods": 2},
        label="Normalization: z_absorb_refill_bid_spot_5bps_1s (Spot) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of absorb_refill_bid_spot_5bps_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="absorb_refill_bid_spot_5bps_1s", kind="col"),),
        feature_id=3220,
    ),
    FeatureSpec(
        name="z_book_asymmetry_fut_struct100_300s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "300"},
        label="Normalization: z_book_asymmetry_fut_struct100_300s (Futures) [300s] (Binance)",
        group="Normalization",
        description="Robust z-score of book_asymmetry_fut_struct100_300s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="book_asymmetry_fut_struct100_300s", kind="col"),),
        feature_id=3221,
    ),
    FeatureSpec(
        name="z_book_asymmetry_fut_struct100_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Normalization: z_book_asymmetry_fut_struct100_60s (Futures) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of book_asymmetry_fut_struct100_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="book_asymmetry_fut_struct100_60s", kind="col"),),
        feature_id=3222,
    ),
    FeatureSpec(
        name="z_book_asymmetry_fut_struct100_900s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "900"},
        label="Normalization: z_book_asymmetry_fut_struct100_900s (Futures) [900s] (Binance)",
        group="Normalization",
        description="Robust z-score of book_asymmetry_fut_struct100_900s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="book_asymmetry_fut_struct100_900s", kind="col"),),
        feature_id=3223,
    ),
    FeatureSpec(
        name="z_book_asymmetry_fut_struct50_300s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "300"},
        label="Normalization: z_book_asymmetry_fut_struct50_300s (Futures) [300s] (Binance)",
        group="Normalization",
        description="Robust z-score of book_asymmetry_fut_struct50_300s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="book_asymmetry_fut_struct50_300s", kind="col"),),
        feature_id=3224,
    ),
    FeatureSpec(
        name="z_book_asymmetry_fut_struct50_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Normalization: z_book_asymmetry_fut_struct50_60s (Futures) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of book_asymmetry_fut_struct50_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="book_asymmetry_fut_struct50_60s", kind="col"),),
        feature_id=3225,
    ),
    FeatureSpec(
        name="z_book_asymmetry_fut_struct50_900s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "900"},
        label="Normalization: z_book_asymmetry_fut_struct50_900s (Futures) [900s] (Binance)",
        group="Normalization",
        description="Robust z-score of book_asymmetry_fut_struct50_900s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="book_asymmetry_fut_struct50_900s", kind="col"),),
        feature_id=3226,
    ),
    FeatureSpec(
        name="z_book_asymmetry_spot_struct100_300s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "300"},
        label="Normalization: z_book_asymmetry_spot_struct100_300s (Spot) [300s] (Binance)",
        group="Normalization",
        description="Robust z-score of book_asymmetry_spot_struct100_300s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="book_asymmetry_spot_struct100_300s", kind="col"),),
        feature_id=3227,
    ),
    FeatureSpec(
        name="z_book_asymmetry_spot_struct100_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Normalization: z_book_asymmetry_spot_struct100_60s (Spot) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of book_asymmetry_spot_struct100_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="book_asymmetry_spot_struct100_60s", kind="col"),),
        feature_id=3228,
    ),
    FeatureSpec(
        name="z_book_asymmetry_spot_struct100_900s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "900"},
        label="Normalization: z_book_asymmetry_spot_struct100_900s (Spot) [900s] (Binance)",
        group="Normalization",
        description="Robust z-score of book_asymmetry_spot_struct100_900s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="book_asymmetry_spot_struct100_900s", kind="col"),),
        feature_id=3229,
    ),
    FeatureSpec(
        name="z_book_asymmetry_spot_struct50_300s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "300"},
        label="Normalization: z_book_asymmetry_spot_struct50_300s (Spot) [300s] (Binance)",
        group="Normalization",
        description="Robust z-score of book_asymmetry_spot_struct50_300s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="book_asymmetry_spot_struct50_300s", kind="col"),),
        feature_id=3230,
    ),
    FeatureSpec(
        name="z_book_asymmetry_spot_struct50_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Normalization: z_book_asymmetry_spot_struct50_60s (Spot) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of book_asymmetry_spot_struct50_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="book_asymmetry_spot_struct50_60s", kind="col"),),
        feature_id=3231,
    ),
    FeatureSpec(
        name="z_book_asymmetry_spot_struct50_900s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "900"},
        label="Normalization: z_book_asymmetry_spot_struct50_900s (Spot) [900s] (Binance)",
        group="Normalization",
        description="Robust z-score of book_asymmetry_spot_struct50_900s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="book_asymmetry_spot_struct50_900s", kind="col"),),
        feature_id=3232,
    ),
    FeatureSpec(
        name="z_depth_gradient_fut_struct100_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "5"},
        label="Normalization: z_depth_gradient_fut_struct100_1s (Futures) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of depth_gradient_fut_struct100_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="depth_gradient_fut_struct100_1s", kind="col"),),
        feature_id=3233,
    ),
    FeatureSpec(
        name="z_depth_gradient_fut_struct50_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "5"},
        label="Normalization: z_depth_gradient_fut_struct50_1s (Futures) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of depth_gradient_fut_struct50_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="depth_gradient_fut_struct50_1s", kind="col"),),
        feature_id=3234,
    ),
    FeatureSpec(
        name="z_depth_gradient_spot_struct100_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "5"},
        label="Normalization: z_depth_gradient_spot_struct100_1s (Spot) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of depth_gradient_spot_struct100_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="depth_gradient_spot_struct100_1s", kind="col"),),
        feature_id=3235,
    ),
    FeatureSpec(
        name="z_depth_gradient_spot_struct50_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "5"},
        label="Normalization: z_depth_gradient_spot_struct50_1s (Spot) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of depth_gradient_spot_struct50_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="depth_gradient_spot_struct50_1s", kind="col"),),
        feature_id=3236,
    ),
    FeatureSpec(
        name="z_impact_per_signed_fut_15s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Normalization: z_impact_per_signed_fut_15s (Futures) [15s] (Binance)",
        group="Normalization",
        description="Robust z-score of impact_per_signed_fut_15s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="impact_per_signed_fut_15s", kind="col"),),
        feature_id=3237,
    ),
    FeatureSpec(
        name="z_impact_per_signed_fut_5s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "5"},
        label="Normalization: z_impact_per_signed_fut_5s (Futures) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of impact_per_signed_fut_5s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="impact_per_signed_fut_5s", kind="col"),),
        feature_id=3238,
    ),
    FeatureSpec(
        name="z_impact_per_signed_fut_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Normalization: z_impact_per_signed_fut_60s (Futures) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of impact_per_signed_fut_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="impact_per_signed_fut_60s", kind="col"),),
        feature_id=3239,
    ),
    FeatureSpec(
        name="z_liq_concentration_fut_struct100_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "5"},
        label="Normalization: z_liq_concentration_fut_struct100_1s (Futures) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of liq_concentration_fut_struct100_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="liq_concentration_fut_struct100_1s", kind="col"),),
        feature_id=3240,
    ),
    FeatureSpec(
        name="z_liq_concentration_fut_struct50_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "5"},
        label="Normalization: z_liq_concentration_fut_struct50_1s (Futures) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of liq_concentration_fut_struct50_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="liq_concentration_fut_struct50_1s", kind="col"),),
        feature_id=3241,
    ),
    FeatureSpec(
        name="z_liq_concentration_spot_struct100_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "5"},
        label="Normalization: z_liq_concentration_spot_struct100_1s (Spot) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of liq_concentration_spot_struct100_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="liq_concentration_spot_struct100_1s", kind="col"),),
        feature_id=3242,
    ),
    FeatureSpec(
        name="z_liq_concentration_spot_struct50_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "5"},
        label="Normalization: z_liq_concentration_spot_struct50_1s (Spot) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of liq_concentration_spot_struct50_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="liq_concentration_spot_struct50_1s", kind="col"),),
        feature_id=3243,
    ),
    # NOTE: z_mid_touch_dev_fut_{1|2}bps_1s removed (feature_id 3246, 3247).
    # mid_touch_dev_fut_*_1s is always 0.0 (mid_touch_fut_1s = (bid+ask)/2 = mid_fut_1s),
    # so the robust z-score is always NaN (zero-MAD). Removed together with upstream S1/S2 features.
    #
    # min_periods=3. price_deviation_*_1s is NaN in ~5-6% of seconds
    # (no trades → vwap NaN → mid - vwap = NaN). With strict
    # min_periods=window_s the rolling z-score is 100% NaN downstream.
    # min_periods=3 makes it computable from the available non-NaN samples.
    FeatureSpec(
        name="z_price_deviation_300s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot|Futures", "window_s": "300", "min_periods": 3},
        label="Normalization: z_price_deviation_300s (Spot/Futures) [300s] (Binance)",
        group="Normalization",
        description="Robust z-score of price_deviation_fut_1s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(
            Dep(name="price_deviation_fut_1s", kind="col"),
            Dep(name="price_deviation_spot_1s", kind="col"),
        ),
        feature_id=3244,
    ),
    FeatureSpec(
        name="z_price_deviation_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot|Futures", "window_s": "60", "min_periods": 3},
        label="Normalization: z_price_deviation_60s (Spot/Futures) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of price_deviation_fut_1s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(
            Dep(name="price_deviation_fut_1s", kind="col"),
            Dep(name="price_deviation_spot_1s", kind="col"),
        ),
        feature_id=3245,
    ),
    FeatureSpec(
        name="z_price_deviation_900s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot|Futures", "window_s": "900", "min_periods": 3},
        label="Normalization: z_price_deviation_900s (Spot/Futures) [900s] (Binance)",
        group="Normalization",
        description="Robust z-score of price_deviation_fut_1s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(
            Dep(name="price_deviation_fut_1s", kind="col"),
            Dep(name="price_deviation_spot_1s", kind="col"),
        ),
        feature_id=3246,
    ),
    FeatureSpec(
        name="z_pull_rate_fut_1bps_15s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "15", "min_periods": 3},
        label="Normalization: z_pull_rate_fut_1bps_15s (Futures) [15s] (Binance)",
        group="Normalization",
        description="Robust z-score of pull_rate_fut_1bps_15s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="pull_rate_fut_1bps_15s", kind="col"),),
        feature_id=3247,
    ),
    FeatureSpec(
        name="z_pull_rate_fut_2bps_15s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "15", "min_periods": 3},
        label="Normalization: z_pull_rate_fut_2bps_15s (Futures) [15s] (Binance)",
        group="Normalization",
        description="Robust z-score of pull_rate_fut_2bps_15s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="pull_rate_fut_2bps_15s", kind="col"),),
        feature_id=3248,
    ),
    FeatureSpec(
        name="z_pull_rate_fut_2bps_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "60", "min_periods": 5},
        label="Normalization: z_pull_rate_fut_2bps_60s (Futures) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of pull_rate_fut_2bps_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="pull_rate_fut_2bps_60s", kind="col"),),
        feature_id=3249,
    ),
    FeatureSpec(
        name="z_pull_rate_spot_1bps_15s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "15", "min_periods": 3},
        label="Normalization: z_pull_rate_spot_1bps_15s (Spot) [15s] (Binance)",
        group="Normalization",
        description="Robust z-score of pull_rate_spot_1bps_15s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="pull_rate_spot_1bps_15s", kind="col"),),
        feature_id=3250,
    ),
    FeatureSpec(
        name="z_pull_rate_spot_2bps_15s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "15", "min_periods": 3},
        label="Normalization: z_pull_rate_spot_2bps_15s (Spot) [15s] (Binance)",
        group="Normalization",
        description="Robust z-score of pull_rate_spot_2bps_15s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="pull_rate_spot_2bps_15s", kind="col"),),
        feature_id=3251,
    ),
    FeatureSpec(
        name="z_pull_rate_spot_2bps_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "60", "min_periods": 5},
        label="Normalization: z_pull_rate_spot_2bps_60s (Spot) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of pull_rate_spot_2bps_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="pull_rate_spot_2bps_60s", kind="col"),),
        feature_id=3252,
    ),
    FeatureSpec(
        name="z_queue_pressure_fut_1bps_15s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Normalization: z_queue_pressure_fut_1bps_15s (Futures) [15s] (Binance)",
        group="Normalization",
        description="Robust z-score of queue_pressure_fut_1bps_15s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="queue_pressure_fut_1bps_15s", kind="col"),),
        feature_id=3253,
    ),
    FeatureSpec(
        name="z_queue_pressure_fut_1bps_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Normalization: z_queue_pressure_fut_1bps_60s (Futures) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of queue_pressure_fut_1bps_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="queue_pressure_fut_1bps_60s", kind="col"),),
        feature_id=3254,
    ),
    FeatureSpec(
        name="z_queue_pressure_spot_1bps_15s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Normalization: z_queue_pressure_spot_1bps_15s (Spot) [15s] (Binance)",
        group="Normalization",
        description="Robust z-score of queue_pressure_spot_1bps_15s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="queue_pressure_spot_1bps_15s", kind="col"),),
        feature_id=3255,
    ),
    FeatureSpec(
        name="z_queue_pressure_spot_1bps_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Normalization: z_queue_pressure_spot_1bps_60s (Spot) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of queue_pressure_spot_1bps_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="queue_pressure_spot_1bps_60s", kind="col"),),
        feature_id=3256,
    ),
    FeatureSpec(
        name="z_refill_rate_fut_1bps_15s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "15", "min_periods": 3},
        label="Normalization: z_refill_rate_fut_1bps_15s (Futures) [15s] (Binance)",
        group="Normalization",
        description="Robust z-score of refill_rate_fut_1bps_15s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="refill_rate_fut_1bps_15s", kind="col"),),
        feature_id=3257,
    ),
    FeatureSpec(
        name="z_refill_rate_fut_1bps_5s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "5", "min_periods": 2},
        label="Normalization: z_refill_rate_fut_1bps_5s (Futures) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of refill_rate_fut_1bps_5s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="refill_rate_fut_1bps_5s", kind="col"),),
        feature_id=3258,
    ),
    FeatureSpec(
        name="z_refill_rate_fut_2bps_15s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "15", "min_periods": 3},
        label="Normalization: z_refill_rate_fut_2bps_15s (Futures) [15s] (Binance)",
        group="Normalization",
        description="Robust z-score of refill_rate_fut_2bps_15s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="refill_rate_fut_2bps_15s", kind="col"),),
        feature_id=3259,
    ),
    FeatureSpec(
        name="z_refill_rate_fut_2bps_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "60", "min_periods": 5},
        label="Normalization: z_refill_rate_fut_2bps_60s (Futures) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of refill_rate_fut_2bps_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="refill_rate_fut_2bps_60s", kind="col"),),
        feature_id=3260,
    ),
    FeatureSpec(
        name="z_refill_rate_spot_1bps_15s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "15", "min_periods": 3},
        label="Normalization: z_refill_rate_spot_1bps_15s (Spot) [15s] (Binance)",
        group="Normalization",
        description="Robust z-score of refill_rate_spot_1bps_15s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="refill_rate_spot_1bps_15s", kind="col"),),
        feature_id=3261,
    ),
    FeatureSpec(
        name="z_refill_rate_spot_1bps_5s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "5", "min_periods": 2},
        label="Normalization: z_refill_rate_spot_1bps_5s (Spot) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of refill_rate_spot_1bps_5s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="refill_rate_spot_1bps_5s", kind="col"),),
        feature_id=3262,
    ),
    FeatureSpec(
        name="z_refill_rate_spot_2bps_15s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "15", "min_periods": 3},
        label="Normalization: z_refill_rate_spot_2bps_15s (Spot) [15s] (Binance)",
        group="Normalization",
        description="Robust z-score of refill_rate_spot_2bps_15s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="refill_rate_spot_2bps_15s", kind="col"),),
        feature_id=3263,
    ),
    FeatureSpec(
        name="z_refill_rate_spot_2bps_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "60", "min_periods": 5},
        label="Normalization: z_refill_rate_spot_2bps_60s (Spot) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of refill_rate_spot_2bps_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="refill_rate_spot_2bps_60s", kind="col"),),
        feature_id=3264,
    ),
    FeatureSpec(
        name="z_refill_vs_pull_fut_1bps_15s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "15", "min_periods": 3},
        label="Normalization: z_refill_vs_pull_fut_1bps_15s (Futures) [15s] (Binance)",
        group="Normalization",
        description="Robust z-score of refill_vs_pull_fut_1bps_15s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="refill_vs_pull_fut_1bps_15s", kind="col"),),
        feature_id=3265,
    ),
    FeatureSpec(
        name="z_refill_vs_pull_fut_2bps_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "60", "min_periods": 5},
        label="Normalization: z_refill_vs_pull_fut_2bps_60s (Futures) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of refill_vs_pull_fut_2bps_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="refill_vs_pull_fut_2bps_60s", kind="col"),),
        feature_id=3266,
    ),
    FeatureSpec(
        name="z_refill_vs_pull_spot_1bps_15s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "15", "min_periods": 3},
        label="Normalization: z_refill_vs_pull_spot_1bps_15s (Spot) [15s] (Binance)",
        group="Normalization",
        description="Robust z-score of refill_vs_pull_spot_1bps_15s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="refill_vs_pull_spot_1bps_15s", kind="col"),),
        feature_id=3267,
    ),
    FeatureSpec(
        name="z_refill_vs_pull_spot_2bps_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "60", "min_periods": 5},
        label="Normalization: z_refill_vs_pull_spot_2bps_60s (Spot) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of refill_vs_pull_spot_2bps_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="refill_vs_pull_spot_2bps_60s", kind="col"),),
        feature_id=3268,
    ),
    FeatureSpec(
        name="z_taker_imbalance_fut_15s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Normalization: z_taker_imbalance_fut_15s (Futures) [15s] (Binance)",
        group="Normalization",
        description="Robust z-score of taker_imbalance_fut_15s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="taker_imbalance_fut_15s", kind="col"),),
        feature_id=3269,
    ),
    FeatureSpec(
        name="z_taker_imbalance_fut_300s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "300"},
        label="Normalization: z_taker_imbalance_fut_300s (Futures) [300s] (Binance)",
        group="Normalization",
        description="Robust z-score of taker_imbalance_fut_300s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="taker_imbalance_fut_300s", kind="col"),),
        feature_id=3270,
    ),
    FeatureSpec(
        name="z_taker_imbalance_fut_5s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "5"},
        label="Normalization: z_taker_imbalance_fut_5s (Futures) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of taker_imbalance_fut_5s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="taker_imbalance_fut_5s", kind="col"),),
        feature_id=3271,
    ),
    FeatureSpec(
        name="z_taker_imbalance_fut_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Normalization: z_taker_imbalance_fut_60s (Futures) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of taker_imbalance_fut_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="taker_imbalance_fut_60s", kind="col"),),
        feature_id=3272,
    ),
    FeatureSpec(
        name="z_taker_imbalance_fut_900s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "900"},
        label="Normalization: z_taker_imbalance_fut_900s (Futures) [900s] (Binance)",
        group="Normalization",
        description="Robust z-score of taker_imbalance_fut_900s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="taker_imbalance_fut_900s", kind="col"),),
        feature_id=3273,
    ),
    FeatureSpec(
        name="z_taker_imbalance_spot_15s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Normalization: z_taker_imbalance_spot_15s (Spot) [15s] (Binance)",
        group="Normalization",
        description="Robust z-score of taker_imbalance_spot_15s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="taker_imbalance_spot_15s", kind="col"),),
        feature_id=3274,
    ),
    FeatureSpec(
        name="z_taker_imbalance_spot_300s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "300"},
        label="Normalization: z_taker_imbalance_spot_300s (Spot) [300s] (Binance)",
        group="Normalization",
        description="Robust z-score of taker_imbalance_spot_300s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="taker_imbalance_spot_300s", kind="col"),),
        feature_id=3275,
    ),
    FeatureSpec(
        name="z_taker_imbalance_spot_5s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "5"},
        label="Normalization: z_taker_imbalance_spot_5s (Spot) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of taker_imbalance_spot_5s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="taker_imbalance_spot_5s", kind="col"),),
        feature_id=3276,
    ),
    FeatureSpec(
        name="z_taker_imbalance_spot_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Normalization: z_taker_imbalance_spot_60s (Spot) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of taker_imbalance_spot_60s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="taker_imbalance_spot_60s", kind="col"),),
        feature_id=3277,
    ),
    FeatureSpec(
        name="z_taker_imbalance_spot_900s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "900"},
        label="Normalization: z_taker_imbalance_spot_900s (Spot) [900s] (Binance)",
        group="Normalization",
        description="Robust z-score of taker_imbalance_spot_900s: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="taker_imbalance_spot_900s", kind="col"),),
        feature_id=3278,
    ),
    FeatureSpec(
        name="z_trade_absorption_ratio_fut_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "5", "min_periods": 2},
        label="Normalization: z_trade_absorption_ratio_fut_1s (Futures) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of trade_absorption_ratio_fut_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="trade_absorption_ratio_fut_1s", kind="col"),),
        feature_id=3279,
    ),
    FeatureSpec(
        name="z_trade_absorption_ratio_spot_1s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "5", "min_periods": 2},
        label="Normalization: z_trade_absorption_ratio_spot_1s (Spot) [5s] (Binance)",
        group="Normalization",
        description="Robust z-score of trade_absorption_ratio_spot_1s [window=5s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="trade_absorption_ratio_spot_1s", kind="col"),),
        feature_id=3280,
    ),

    # =========================================================================
    # GAP-FILL: Flow-Depth Alignment Normalization
    # Robust z-scores of the S2 flow_depth_align rolling features.
    # Enables the ML model to detect anomalously high/low alignment regimes.
    # Only struct100 at 60s/300s — the most stable variants.
    # =========================================================================
    FeatureSpec(
        name="z_flow_depth_align_fut_struct100_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "60", "min_periods": 2},
        label="Normalization: z_flow_depth_align_fut_struct100_60s (Futures) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of flow_depth_align_fut_struct100_60s [window=60s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="flow_depth_align_fut_struct100_60s", kind="col"),),
        feature_id=3281,
    ),
    FeatureSpec(
        name="z_flow_depth_align_fut_struct100_300s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Futures", "window_s": "300", "min_periods": 2},
        label="Normalization: z_flow_depth_align_fut_struct100_300s (Futures) [300s] (Binance)",
        group="Normalization",
        description="Robust z-score of flow_depth_align_fut_struct100_300s [window=300s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="flow_depth_align_fut_struct100_300s", kind="col"),),
        feature_id=3282,
    ),
    FeatureSpec(
        name="z_flow_depth_align_spot_struct100_60s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "60", "min_periods": 2},
        label="Normalization: z_flow_depth_align_spot_struct100_60s (Spot) [60s] (Binance)",
        group="Normalization",
        description="Robust z-score of flow_depth_align_spot_struct100_60s [window=60s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="flow_depth_align_spot_struct100_60s", kind="col"),),
        feature_id=3283,
    ),
    FeatureSpec(
        name="z_flow_depth_align_spot_struct100_300s",
        stage="S3",
        operator="derived.robust_zscore",
        params={"market_scope": "Spot", "window_s": "300", "min_periods": 2},
        label="Normalization: z_flow_depth_align_spot_struct100_300s (Spot) [300s] (Binance)",
        group="Normalization",
        description="Robust z-score of flow_depth_align_spot_struct100_300s [window=300s]: (x - median) / (1.4826 * MAD + eps).",
        depends_on=(Dep(name="flow_depth_align_spot_struct100_300s", kind="col"),),
        feature_id=3284,
    ),

]