# etl/spec/s3/s3_pressure.py
# ========================================================================
# S3 Pressure Features
# Aggregated net order flow pressure metrics across multiple depth bands and
# time windows. These features combine add-rate and cancel-rate signals into
# net pressure indicators, then aggregate via rolling sums, means, and
# cross-band log-ratios.
# 
# Key concepts:
#   - net_add_*: Rolling sum of net_add_pressure (add_bid - cancel_bid) -
#     (add_ask - cancel_ask) over various windows (1s, 15s, 60s, 300s, 900s, 3600s)
#     at 2bps, 5bps, and 10bps bands.
#   - net_cancel_*: Rolling sum and rolling mean of net_cancel_pressure
#     (cancel_bid - cancel_ask) for detecting asymmetric cancellation flow.
#   - net_pressure_*: Rolling mean of net_add_pressure for smoothed pressure signals.
#   - net_pressure_logratio: Log-ratio of net pressure between adjacent depth
#     bands (2bps/5bps and 5bps/10bps). Detects whether pressure is concentrated
#     near the touch or distributed across deeper levels.
# 
# Dependencies: S2 net_add_pressure, net_cancel_pressure at 2/5/10 bps.
#
# Feature count: 72  (was 78; removed 6 × 3600s features)
# [FIX-3600] Removed all window_s=3600 features (net_add/net_cancel pressure _3600s rolling sums).
#            3600s rolling windows require 1h prior data even with context;
#            produce 99-100% NaN on 1h Parquet files. The 900s variants
#            provide equivalent microstructure regime coverage.
# Feature ID range: see individual entries
# ========================================================================

from typing import List
from etl.spec import FeatureSpec, Dep

S3_PRESSURE_FEATURES: List[FeatureSpec] = [
    FeatureSpec(
        name="net_add_fut_10bps_1s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Futures", "window_s": "1"},
        label="Pressure: net_add_fut_10bps_1s (Futures) [1s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_fut_10bps_1s over 1s window.",
        depends_on=(Dep(name="net_add_pressure_fut_10bps_1s", kind="col"),),
        feature_id=3285,
    ),
    FeatureSpec(
        name="net_add_fut_2bps_1s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Futures", "window_s": "1"},
        label="Pressure: net_add_fut_2bps_1s (Futures) [1s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_fut_2bps_1s over 1s window.",
        depends_on=(Dep(name="net_add_pressure_fut_2bps_1s", kind="col"),),
        feature_id=3286,
    ),
    FeatureSpec(
        name="net_add_fut_5bps_1s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Futures", "window_s": "1"},
        label="Pressure: net_add_fut_5bps_1s (Futures) [1s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_fut_5bps_1s over 1s window.",
        depends_on=(Dep(name="net_add_pressure_fut_5bps_1s", kind="col"),),
        feature_id=3287,
    ),
    FeatureSpec(
        name="net_add_fut_5bps_900s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Futures", "window_s": "900"},
        label="Pressure: net_add_fut_5bps_900s (Futures) [900s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_fut_5bps_1s over 900s window.",
        depends_on=(Dep(name="net_add_pressure_fut_5bps_1s", kind="col"),),
        feature_id=3288,
    ),
    FeatureSpec(
        name="net_add_pressure_fut_10bps_15s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Pressure: net_add_pressure_fut_10bps_15s (Futures) [15s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_fut_10bps_1s over 15s window.",
        depends_on=(Dep(name="net_add_pressure_fut_10bps_1s", kind="col"),),
        feature_id=3289,
    ),
    FeatureSpec(
        name="net_add_pressure_fut_10bps_300s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Futures", "window_s": "300"},
        label="Pressure: net_add_pressure_fut_10bps_300s (Futures) [300s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_fut_10bps_1s over 300s window.",
        depends_on=(Dep(name="net_add_pressure_fut_10bps_1s", kind="col"),),
        feature_id=3290,
    ),
    FeatureSpec(
        name="net_add_pressure_fut_10bps_60s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Pressure: net_add_pressure_fut_10bps_60s (Futures) [60s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_fut_10bps_1s over 60s window.",
        depends_on=(Dep(name="net_add_pressure_fut_10bps_1s", kind="col"),),
        feature_id=3291,
    ),
    FeatureSpec(
        name="net_add_pressure_fut_10bps_900s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Futures", "window_s": "900"},
        label="Pressure: net_add_pressure_fut_10bps_900s (Futures) [900s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_fut_10bps_1s over 900s window.",
        depends_on=(Dep(name="net_add_pressure_fut_10bps_1s", kind="col"),),
        feature_id=3292,
    ),
    FeatureSpec(
        name="net_add_pressure_fut_2bps_15s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Pressure: net_add_pressure_fut_2bps_15s (Futures) [15s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_fut_2bps_1s over 15s window.",
        depends_on=(Dep(name="net_add_pressure_fut_2bps_1s", kind="col"),),
        feature_id=3293,
    ),
    FeatureSpec(
        name="net_add_pressure_fut_2bps_60s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Pressure: net_add_pressure_fut_2bps_60s (Futures) [60s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_fut_2bps_1s over 60s window.",
        depends_on=(Dep(name="net_add_pressure_fut_2bps_1s", kind="col"),),
        feature_id=3294,
    ),
    FeatureSpec(
        name="net_add_pressure_fut_5bps_15s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Pressure: net_add_pressure_fut_5bps_15s (Futures) [15s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_fut_5bps_1s over 15s window.",
        depends_on=(Dep(name="net_add_pressure_fut_5bps_1s", kind="col"),),
        feature_id=3295,
    ),
    FeatureSpec(
        name="net_add_pressure_fut_5bps_300s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Futures", "window_s": "300"},
        label="Pressure: net_add_pressure_fut_5bps_300s (Futures) [300s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_fut_5bps_1s over 300s window.",
        depends_on=(Dep(name="net_add_pressure_fut_5bps_1s", kind="col"),),
        feature_id=3296,
    ),
    FeatureSpec(
        name="net_add_pressure_fut_5bps_60s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Pressure: net_add_pressure_fut_5bps_60s (Futures) [60s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_fut_5bps_1s over 60s window.",
        depends_on=(Dep(name="net_add_pressure_fut_5bps_1s", kind="col"),),
        feature_id=3297,
    ),
    FeatureSpec(
        name="net_add_pressure_spot_10bps_15s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Pressure: net_add_pressure_spot_10bps_15s (Spot) [15s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_spot_10bps_1s over 15s window.",
        depends_on=(Dep(name="net_add_pressure_spot_10bps_1s", kind="col"),),
        feature_id=3298,
    ),
    FeatureSpec(
        name="net_add_pressure_spot_10bps_300s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Spot", "window_s": "300"},
        label="Pressure: net_add_pressure_spot_10bps_300s (Spot) [300s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_spot_10bps_1s over 300s window.",
        depends_on=(Dep(name="net_add_pressure_spot_10bps_1s", kind="col"),),
        feature_id=3299,
    ),
    FeatureSpec(
        name="net_add_pressure_spot_10bps_60s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Pressure: net_add_pressure_spot_10bps_60s (Spot) [60s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_spot_10bps_1s over 60s window.",
        depends_on=(Dep(name="net_add_pressure_spot_10bps_1s", kind="col"),),
        feature_id=3300,
    ),
    FeatureSpec(
        name="net_add_pressure_spot_10bps_900s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Spot", "window_s": "900"},
        label="Pressure: net_add_pressure_spot_10bps_900s (Spot) [900s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_spot_10bps_1s over 900s window.",
        depends_on=(Dep(name="net_add_pressure_spot_10bps_1s", kind="col"),),
        feature_id=3301,
    ),
    FeatureSpec(
        name="net_add_pressure_spot_2bps_15s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Pressure: net_add_pressure_spot_2bps_15s (Spot) [15s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_spot_2bps_1s over 15s window.",
        depends_on=(Dep(name="net_add_pressure_spot_2bps_1s", kind="col"),),
        feature_id=3302,
    ),
    FeatureSpec(
        name="net_add_pressure_spot_2bps_60s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Pressure: net_add_pressure_spot_2bps_60s (Spot) [60s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_spot_2bps_1s over 60s window.",
        depends_on=(Dep(name="net_add_pressure_spot_2bps_1s", kind="col"),),
        feature_id=3303,
    ),
    FeatureSpec(
        name="net_add_pressure_spot_5bps_15s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Pressure: net_add_pressure_spot_5bps_15s (Spot) [15s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_spot_5bps_1s over 15s window.",
        depends_on=(Dep(name="net_add_pressure_spot_5bps_1s", kind="col"),),
        feature_id=3304,
    ),
    FeatureSpec(
        name="net_add_pressure_spot_5bps_300s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Spot", "window_s": "300"},
        label="Pressure: net_add_pressure_spot_5bps_300s (Spot) [300s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_spot_5bps_1s over 300s window.",
        depends_on=(Dep(name="net_add_pressure_spot_5bps_1s", kind="col"),),
        feature_id=3305,
    ),
    FeatureSpec(
        name="net_add_pressure_spot_5bps_60s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Pressure: net_add_pressure_spot_5bps_60s (Spot) [60s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_spot_5bps_1s over 60s window.",
        depends_on=(Dep(name="net_add_pressure_spot_5bps_1s", kind="col"),),
        feature_id=3306,
    ),
    FeatureSpec(
        name="net_add_spot_10bps_1s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Spot", "window_s": "1"},
        label="Pressure: net_add_spot_10bps_1s (Spot) [1s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_spot_10bps_1s over 1s window.",
        depends_on=(Dep(name="net_add_pressure_spot_10bps_1s", kind="col"),),
        feature_id=3307,
    ),
    FeatureSpec(
        name="net_add_spot_2bps_1s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Spot", "window_s": "1"},
        label="Pressure: net_add_spot_2bps_1s (Spot) [1s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_spot_2bps_1s over 1s window.",
        depends_on=(Dep(name="net_add_pressure_spot_2bps_1s", kind="col"),),
        feature_id=3308,
    ),
    FeatureSpec(
        name="net_add_spot_5bps_1s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Spot", "window_s": "1"},
        label="Pressure: net_add_spot_5bps_1s (Spot) [1s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_spot_5bps_1s over 1s window.",
        depends_on=(Dep(name="net_add_pressure_spot_5bps_1s", kind="col"),),
        feature_id=3309,
    ),
    FeatureSpec(
        name="net_add_spot_5bps_900s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Spot", "window_s": "900"},
        label="Pressure: net_add_spot_5bps_900s (Spot) [900s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_add_pressure_spot_5bps_1s over 900s window.",
        depends_on=(Dep(name="net_add_pressure_spot_5bps_1s", kind="col"),),
        feature_id=3310,
    ),
    FeatureSpec(
        name="net_cancel_fut_10bps_1s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Futures", "window_s": "1"},
        label="Pressure: net_cancel_fut_10bps_1s (Futures) [1s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_cancel_pressure_fut_10bps_1s over 1s window.",
        depends_on=(Dep(name="net_cancel_pressure_fut_10bps_1s", kind="col"),),
        feature_id=3311,
    ),
    FeatureSpec(
        name="net_cancel_fut_2bps_1s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Futures", "window_s": "1"},
        label="Pressure: net_cancel_fut_2bps_1s (Futures) [1s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_cancel_pressure_fut_2bps_1s over 1s window.",
        depends_on=(Dep(name="net_cancel_pressure_fut_2bps_1s", kind="col"),),
        feature_id=3312,
    ),
    FeatureSpec(
        name="net_cancel_fut_5bps_1s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Futures", "window_s": "1"},
        label="Pressure: net_cancel_fut_5bps_1s (Futures) [1s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_cancel_pressure_fut_5bps_1s over 1s window.",
        depends_on=(Dep(name="net_cancel_pressure_fut_5bps_1s", kind="col"),),
        feature_id=3313,
    ),
    FeatureSpec(
        name="net_cancel_fut_5bps_900s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Futures", "window_s": "900"},
        label="Pressure: net_cancel_fut_5bps_900s (Futures) [900s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_cancel_pressure_fut_5bps_1s over 900s window.",
        depends_on=(Dep(name="net_cancel_pressure_fut_5bps_1s", kind="col"),),
        feature_id=3314,
    ),
    FeatureSpec(
        name="net_cancel_pressure_fut_2bps_15s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Pressure: net_cancel_pressure_fut_2bps_15s (Futures) [15s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_cancel_pressure_fut_2bps_1s over 15s window.",
        depends_on=(Dep(name="net_cancel_pressure_fut_2bps_1s", kind="col"),),
        feature_id=3315,
    ),
    FeatureSpec(
        name="net_cancel_pressure_fut_2bps_60s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Pressure: net_cancel_pressure_fut_2bps_60s (Futures) [60s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_cancel_pressure_fut_2bps_1s over 60s window.",
        depends_on=(Dep(name="net_cancel_pressure_fut_2bps_1s", kind="col"),),
        feature_id=3316,
    ),
    FeatureSpec(
        name="net_cancel_pressure_fut_5bps_15s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Pressure: net_cancel_pressure_fut_5bps_15s (Futures) [15s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_cancel_pressure_fut_5bps_1s over 15s window.",
        depends_on=(Dep(name="net_cancel_pressure_fut_5bps_1s", kind="col"),),
        feature_id=3317,
    ),
    FeatureSpec(
        name="net_cancel_pressure_fut_5bps_60s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Pressure: net_cancel_pressure_fut_5bps_60s (Futures) [60s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_cancel_pressure_fut_5bps_1s over 60s window.",
        depends_on=(Dep(name="net_cancel_pressure_fut_5bps_1s", kind="col"),),
        feature_id=3318,
    ),
    FeatureSpec(
        name="net_cancel_pressure_spot_2bps_15s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Pressure: net_cancel_pressure_spot_2bps_15s (Spot) [15s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_cancel_pressure_spot_2bps_1s over 15s window.",
        depends_on=(Dep(name="net_cancel_pressure_spot_2bps_1s", kind="col"),),
        feature_id=3319,
    ),
    FeatureSpec(
        name="net_cancel_pressure_spot_2bps_60s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Pressure: net_cancel_pressure_spot_2bps_60s (Spot) [60s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_cancel_pressure_spot_2bps_1s over 60s window.",
        depends_on=(Dep(name="net_cancel_pressure_spot_2bps_1s", kind="col"),),
        feature_id=3320,
    ),
    FeatureSpec(
        name="net_cancel_pressure_spot_5bps_15s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Pressure: net_cancel_pressure_spot_5bps_15s (Spot) [15s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_cancel_pressure_spot_5bps_1s over 15s window.",
        depends_on=(Dep(name="net_cancel_pressure_spot_5bps_1s", kind="col"),),
        feature_id=3321,
    ),
    FeatureSpec(
        name="net_cancel_pressure_spot_5bps_60s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Pressure: net_cancel_pressure_spot_5bps_60s (Spot) [60s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_cancel_pressure_spot_5bps_1s over 60s window.",
        depends_on=(Dep(name="net_cancel_pressure_spot_5bps_1s", kind="col"),),
        feature_id=3322,
    ),
    FeatureSpec(
        name="net_cancel_spot_10bps_1s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Spot", "window_s": "1"},
        label="Pressure: net_cancel_spot_10bps_1s (Spot) [1s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_cancel_pressure_spot_10bps_1s over 1s window.",
        depends_on=(Dep(name="net_cancel_pressure_spot_10bps_1s", kind="col"),),
        feature_id=3323,
    ),
    FeatureSpec(
        name="net_cancel_spot_2bps_1s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Spot", "window_s": "1"},
        label="Pressure: net_cancel_spot_2bps_1s (Spot) [1s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_cancel_pressure_spot_2bps_1s over 1s window.",
        depends_on=(Dep(name="net_cancel_pressure_spot_2bps_1s", kind="col"),),
        feature_id=3324,
    ),
    FeatureSpec(
        name="net_cancel_spot_5bps_1s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Spot", "window_s": "1"},
        label="Pressure: net_cancel_spot_5bps_1s (Spot) [1s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_cancel_pressure_spot_5bps_1s over 1s window.",
        depends_on=(Dep(name="net_cancel_pressure_spot_5bps_1s", kind="col"),),
        feature_id=3325,
    ),
    FeatureSpec(
        name="net_cancel_spot_5bps_900s",
        stage="S3",
        operator="derived.roll_sum",
        params={"market_scope": "Spot", "window_s": "900"},
        label="Pressure: net_cancel_spot_5bps_900s (Spot) [900s] (Binance)",
        group="Pressure",
        description="Rolling sum of net_cancel_pressure_spot_5bps_1s over 900s window.",
        depends_on=(Dep(name="net_cancel_pressure_spot_5bps_1s", kind="col"),),
        feature_id=3326,
    ),
    FeatureSpec(
        name="net_pressure_fut_10bps_15s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Pressure: net_pressure_fut_10bps_15s (Futures) [15s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_fut_10bps_1s over 15s window.",
        depends_on=(Dep(name="net_add_pressure_fut_10bps_1s", kind="col"),),
        feature_id=3327,
    ),
    FeatureSpec(
        name="net_pressure_fut_10bps_5s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Futures", "window_s": "5"},
        label="Pressure: net_pressure_fut_10bps_5s (Futures) [5s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_fut_10bps_1s over 5s window.",
        depends_on=(Dep(name="net_add_pressure_fut_10bps_1s", kind="col"),),
        feature_id=3328,
    ),
    FeatureSpec(
        name="net_pressure_fut_10bps_60s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Pressure: net_pressure_fut_10bps_60s (Futures) [60s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_fut_10bps_1s over 60s window.",
        depends_on=(Dep(name="net_add_pressure_fut_10bps_1s", kind="col"),),
        feature_id=3329,
    ),
    FeatureSpec(
        name="net_pressure_fut_2bps_15s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Pressure: net_pressure_fut_2bps_15s (Futures) [15s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_fut_2bps_1s over 15s window.",
        depends_on=(Dep(name="net_add_pressure_fut_2bps_1s", kind="col"),),
        feature_id=3330,
    ),
    FeatureSpec(
        name="net_pressure_fut_2bps_5s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Futures", "window_s": "5"},
        label="Pressure: net_pressure_fut_2bps_5s (Futures) [5s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_fut_2bps_1s over 5s window.",
        depends_on=(Dep(name="net_add_pressure_fut_2bps_1s", kind="col"),),
        feature_id=3331,
    ),
    FeatureSpec(
        name="net_pressure_fut_2bps_60s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Pressure: net_pressure_fut_2bps_60s (Futures) [60s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_fut_2bps_1s over 60s window.",
        depends_on=(Dep(name="net_add_pressure_fut_2bps_1s", kind="col"),),
        feature_id=3332,
    ),
    FeatureSpec(
        name="net_pressure_fut_5bps_15s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Pressure: net_pressure_fut_5bps_15s (Futures) [15s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_fut_5bps_1s over 15s window.",
        depends_on=(Dep(name="net_add_pressure_fut_5bps_1s", kind="col"),),
        feature_id=3333,
    ),
    FeatureSpec(
        name="net_pressure_fut_5bps_5s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Futures", "window_s": "5"},
        label="Pressure: net_pressure_fut_5bps_5s (Futures) [5s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_fut_5bps_1s over 5s window.",
        depends_on=(Dep(name="net_add_pressure_fut_5bps_1s", kind="col"),),
        feature_id=3334,
    ),
    FeatureSpec(
        name="net_pressure_fut_5bps_60s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Pressure: net_pressure_fut_5bps_60s (Futures) [60s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_fut_5bps_1s over 60s window.",
        depends_on=(Dep(name="net_add_pressure_fut_5bps_1s", kind="col"),),
        feature_id=3335,
    ),
    FeatureSpec(
        name="net_pressure_logratio_2bps_5bps_fut_15s",
        stage="S3",
        operator="derived.logratio",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Pressure: net_pressure_logratio_2bps_5bps_fut_15s (Futures) [15s] (Binance)",
        group="Pressure",
        description="Log ratio: log(net_add_pressure_fut_2bps_1s / net_add_pressure_fut_5bps_1s) at 15s resolution.",
        depends_on=(
            Dep(name="net_add_pressure_fut_2bps_1s", kind="col"),
            Dep(name="net_add_pressure_fut_5bps_1s", kind="col"),
        ),
        feature_id=3336,
    ),
    FeatureSpec(
        name="net_pressure_logratio_2bps_5bps_fut_1s",
        stage="S3",
        operator="derived.logratio",
        params={"market_scope": "Futures", "window_s": "1"},
        label="Pressure: net_pressure_logratio_2bps_5bps_fut_1s (Futures) [1s] (Binance)",
        group="Pressure",
        description="Log ratio: log(net_add_pressure_fut_2bps_1s / net_add_pressure_fut_5bps_1s) at 1s resolution.",
        depends_on=(
            Dep(name="net_add_pressure_fut_2bps_1s", kind="col"),
            Dep(name="net_add_pressure_fut_5bps_1s", kind="col"),
        ),
        feature_id=3337,
    ),
    FeatureSpec(
        name="net_pressure_logratio_2bps_5bps_fut_60s",
        stage="S3",
        operator="derived.logratio",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Pressure: net_pressure_logratio_2bps_5bps_fut_60s (Futures) [60s] (Binance)",
        group="Pressure",
        description="Log ratio: log(net_add_pressure_fut_2bps_1s / net_add_pressure_fut_5bps_1s) at 60s resolution.",
        depends_on=(
            Dep(name="net_add_pressure_fut_2bps_1s", kind="col"),
            Dep(name="net_add_pressure_fut_5bps_1s", kind="col"),
        ),
        feature_id=3338,
    ),
    FeatureSpec(
        name="net_pressure_logratio_2bps_5bps_spot_15s",
        stage="S3",
        operator="derived.logratio",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Pressure: net_pressure_logratio_2bps_5bps_spot_15s (Spot) [15s] (Binance)",
        group="Pressure",
        description="Log ratio: log(net_add_pressure_spot_2bps_1s / net_add_pressure_spot_5bps_1s) at 15s resolution.",
        depends_on=(
            Dep(name="net_add_pressure_spot_2bps_1s", kind="col"),
            Dep(name="net_add_pressure_spot_5bps_1s", kind="col"),
        ),
        feature_id=3339,
    ),
    FeatureSpec(
        name="net_pressure_logratio_2bps_5bps_spot_1s",
        stage="S3",
        operator="derived.logratio",
        params={"market_scope": "Spot", "window_s": "1"},
        label="Pressure: net_pressure_logratio_2bps_5bps_spot_1s (Spot) [1s] (Binance)",
        group="Pressure",
        description="Log ratio: log(net_add_pressure_spot_2bps_1s / net_add_pressure_spot_5bps_1s) at 1s resolution.",
        depends_on=(
            Dep(name="net_add_pressure_spot_2bps_1s", kind="col"),
            Dep(name="net_add_pressure_spot_5bps_1s", kind="col"),
        ),
        feature_id=3340,
    ),
    FeatureSpec(
        name="net_pressure_logratio_2bps_5bps_spot_60s",
        stage="S3",
        operator="derived.logratio",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Pressure: net_pressure_logratio_2bps_5bps_spot_60s (Spot) [60s] (Binance)",
        group="Pressure",
        description="Log ratio: log(net_add_pressure_spot_2bps_1s / net_add_pressure_spot_5bps_1s) at 60s resolution.",
        depends_on=(
            Dep(name="net_add_pressure_spot_2bps_1s", kind="col"),
            Dep(name="net_add_pressure_spot_5bps_1s", kind="col"),
        ),
        feature_id=3341,
    ),
    FeatureSpec(
        name="net_pressure_logratio_5bps_10bps_fut_15s",
        stage="S3",
        operator="derived.logratio",
        params={"market_scope": "Futures", "window_s": "15"},
        label="Pressure: net_pressure_logratio_5bps_10bps_fut_15s (Futures) [15s] (Binance)",
        group="Pressure",
        description="Log ratio: log(net_add_pressure_fut_10bps_1s / net_add_pressure_fut_5bps_1s) at 15s resolution.",
        depends_on=(
            Dep(name="net_add_pressure_fut_10bps_1s", kind="col"),
            Dep(name="net_add_pressure_fut_5bps_1s", kind="col"),
        ),
        feature_id=3342,
    ),
    FeatureSpec(
        name="net_pressure_logratio_5bps_10bps_fut_1s",
        stage="S3",
        operator="derived.logratio",
        params={"market_scope": "Futures", "window_s": "1"},
        label="Pressure: net_pressure_logratio_5bps_10bps_fut_1s (Futures) [1s] (Binance)",
        group="Pressure",
        description="Log ratio: log(net_add_pressure_fut_10bps_1s / net_add_pressure_fut_5bps_1s) at 1s resolution.",
        depends_on=(
            Dep(name="net_add_pressure_fut_10bps_1s", kind="col"),
            Dep(name="net_add_pressure_fut_5bps_1s", kind="col"),
        ),
        feature_id=3343,
    ),
    FeatureSpec(
        name="net_pressure_logratio_5bps_10bps_fut_60s",
        stage="S3",
        operator="derived.logratio",
        params={"market_scope": "Futures", "window_s": "60"},
        label="Pressure: net_pressure_logratio_5bps_10bps_fut_60s (Futures) [60s] (Binance)",
        group="Pressure",
        description="Log ratio: log(net_add_pressure_fut_10bps_1s / net_add_pressure_fut_5bps_1s) at 60s resolution.",
        depends_on=(
            Dep(name="net_add_pressure_fut_10bps_1s", kind="col"),
            Dep(name="net_add_pressure_fut_5bps_1s", kind="col"),
        ),
        feature_id=3344,
    ),
    FeatureSpec(
        name="net_pressure_logratio_5bps_10bps_spot_15s",
        stage="S3",
        operator="derived.logratio",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Pressure: net_pressure_logratio_5bps_10bps_spot_15s (Spot) [15s] (Binance)",
        group="Pressure",
        description="Log ratio: log(net_add_pressure_spot_10bps_1s / net_add_pressure_spot_5bps_1s) at 15s resolution.",
        depends_on=(
            Dep(name="net_add_pressure_spot_10bps_1s", kind="col"),
            Dep(name="net_add_pressure_spot_5bps_1s", kind="col"),
        ),
        feature_id=3345,
    ),
    FeatureSpec(
        name="net_pressure_logratio_5bps_10bps_spot_1s",
        stage="S3",
        operator="derived.logratio",
        params={"market_scope": "Spot", "window_s": "1"},
        label="Pressure: net_pressure_logratio_5bps_10bps_spot_1s (Spot) [1s] (Binance)",
        group="Pressure",
        description="Log ratio: log(net_add_pressure_spot_10bps_1s / net_add_pressure_spot_5bps_1s) at 1s resolution.",
        depends_on=(
            Dep(name="net_add_pressure_spot_10bps_1s", kind="col"),
            Dep(name="net_add_pressure_spot_5bps_1s", kind="col"),
        ),
        feature_id=3346,
    ),
    FeatureSpec(
        name="net_pressure_logratio_5bps_10bps_spot_60s",
        stage="S3",
        operator="derived.logratio",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Pressure: net_pressure_logratio_5bps_10bps_spot_60s (Spot) [60s] (Binance)",
        group="Pressure",
        description="Log ratio: log(net_add_pressure_spot_10bps_1s / net_add_pressure_spot_5bps_1s) at 60s resolution.",
        depends_on=(
            Dep(name="net_add_pressure_spot_10bps_1s", kind="col"),
            Dep(name="net_add_pressure_spot_5bps_1s", kind="col"),
        ),
        feature_id=3347,
    ),
    FeatureSpec(
        name="net_pressure_spot_10bps_15s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Pressure: net_pressure_spot_10bps_15s (Spot) [15s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_spot_10bps_1s over 15s window.",
        depends_on=(Dep(name="net_add_pressure_spot_10bps_1s", kind="col"),),
        feature_id=3348,
    ),
    FeatureSpec(
        name="net_pressure_spot_10bps_5s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Spot", "window_s": "5"},
        label="Pressure: net_pressure_spot_10bps_5s (Spot) [5s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_spot_10bps_1s over 5s window.",
        depends_on=(Dep(name="net_add_pressure_spot_10bps_1s", kind="col"),),
        feature_id=3349,
    ),
    FeatureSpec(
        name="net_pressure_spot_10bps_60s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Pressure: net_pressure_spot_10bps_60s (Spot) [60s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_spot_10bps_1s over 60s window.",
        depends_on=(Dep(name="net_add_pressure_spot_10bps_1s", kind="col"),),
        feature_id=3350,
    ),
    FeatureSpec(
        name="net_pressure_spot_2bps_15s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Pressure: net_pressure_spot_2bps_15s (Spot) [15s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_spot_2bps_1s over 15s window.",
        depends_on=(Dep(name="net_add_pressure_spot_2bps_1s", kind="col"),),
        feature_id=3351,
    ),
    FeatureSpec(
        name="net_pressure_spot_2bps_5s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Spot", "window_s": "5"},
        label="Pressure: net_pressure_spot_2bps_5s (Spot) [5s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_spot_2bps_1s over 5s window.",
        depends_on=(Dep(name="net_add_pressure_spot_2bps_1s", kind="col"),),
        feature_id=3352,
    ),
    FeatureSpec(
        name="net_pressure_spot_2bps_60s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Pressure: net_pressure_spot_2bps_60s (Spot) [60s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_spot_2bps_1s over 60s window.",
        depends_on=(Dep(name="net_add_pressure_spot_2bps_1s", kind="col"),),
        feature_id=3353,
    ),
    FeatureSpec(
        name="net_pressure_spot_5bps_15s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Spot", "window_s": "15"},
        label="Pressure: net_pressure_spot_5bps_15s (Spot) [15s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_spot_5bps_1s over 15s window.",
        depends_on=(Dep(name="net_add_pressure_spot_5bps_1s", kind="col"),),
        feature_id=3354,
    ),
    FeatureSpec(
        name="net_pressure_spot_5bps_5s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Spot", "window_s": "5"},
        label="Pressure: net_pressure_spot_5bps_5s (Spot) [5s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_spot_5bps_1s over 5s window.",
        depends_on=(Dep(name="net_add_pressure_spot_5bps_1s", kind="col"),),
        feature_id=3355,
    ),
    FeatureSpec(
        name="net_pressure_spot_5bps_60s",
        stage="S3",
        operator="derived.roll_mean",
        params={"market_scope": "Spot", "window_s": "60"},
        label="Pressure: net_pressure_spot_5bps_60s (Spot) [60s] (Binance)",
        group="Pressure",
        description="Rolling mean of net_add_pressure_spot_5bps_1s over 60s window.",
        depends_on=(Dep(name="net_add_pressure_spot_5bps_1s", kind="col"),),
        feature_id=3356,
    ),

]